### ISSUE TITLE
workflow_run trigger filters wrong branch following a previous workflow_run event

### ISSUE THREAD

**Issue by coryjoist** [actions/runner#1628] opened 2022-01-25 18:24 UTC
**Describe the bug**

`workflow_run` event branch filtering behaves differently depending whether the triggering workflow was itself triggered on a `push` or another different `workflow_run` event.

Assume we have three workflows chained together, workflow1 -> workflow2 -> workflow3.
- workflow1 triggers on a push, on any branch.
- workflow2 triggers on completion of workflow1, using branch filtering.
- workflow3 triggers on completion of workflow2, using branch filtering.

workflow2 will allow you to trigger based on the branch of the original push. However, workflow3 will ALWAYS trigger using the repository's default branch, even if using the exact same workflow configurations.

Relevant documentation
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#limiting-your-workflow-to-run-based-on-branches

**To Reproduce**
1. Fork github repo https://github.com/coryjoist/workflow_run_filter. Note that `develop` is the default branch.
2. Commit a change to README.md on the `develop` branch.
3. Observe that
```
workflow_run:
    branches:
    - develop
```
is respected for both the `develop-test` and `develop-deploy` actions.
4. Merge develop into master (or commit a change to README.md on the `master` branch.
5. Observe that
```
workflow_run:
    branches:
    - master
```
is respected for `master-test` BUT `develop-deploy` is triggered rather than `master-deploy` as configured in its workflow_run branch filtering. It is using the default branch rather than the branch filter defined in the workflow configuration.

**Expected behavior**
I expect that the branch filtering for
```
workflow_run:
    branches:
```
will always respect the branch the previous workflow acted upon, rather than sometimes using the branch the workflow file is referenced from.

## Runner Version and Platform
2.286.1

OS of the machine running the runner?
Ubuntu 20.04.3

## What's not working?
workflow_run branch filter reference value changes unexpectedly depending on previous workflow chain.

## Job Log Output
n/a

## Runner and Worker's Diagnostic Logs
n/a

**Comment by nikola-jokic** [comment] 2022-02-02 11:47
Hi @coryjoist, we have successfully reproduced this issue. We are investigating the root cause of this issue and we will get back to you as soon as possible.

**Comment by nikola-jokic** [comment] 2022-02-02 14:43
Hi @coryjoist, I can add now the explanation of why is this happening:
`workflow_run` events will always run on the **default branch**. A branch is not propagated across multiple levels of `workflow_run` events.

In this case:

- We have a push to master triggering a build workflow.

- This sends a  `workflow_run:completed `event, picked up by `predeploy-test` (as the build workflow’s branch was master) this workflows branch is `develop` — as this is the default branch. We can access the branch and metadata of the initial workflow (which ran on master) via the [event payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run).

- this sends another `workflow_run:completed` which is picked up by `develop-deploy` not `master-deploy` precisely because the branch that `predeploy-test` ran on was `develop` (the default branch) as documented!

**Comment by ethomson** [comment] 2022-02-02 19:50
I regret that I'm going to close this issue - this is not related to the runner application, this is part of the overall service.  Since we use this issue tracker to track bugs in the runner application itself, this is best served by https://github.community/c/code-to-cloud/52

**Closed by ethomson** 2022-02-02 19:50 UTC
Labels: bug

**Comment by coryjoist** [comment] 2022-02-03 15:15
Hi @nikola-jokic, thanks for looking at this! You're correct that the workflow referenced will always be off the default branch as documented. However, there is functionality to add branch filtering on the trigger, which doesn't actually work as advertised. Is always filtering off of whatever the default branch is.

@ethomson thanks for providing direction to a better authority on this

**Comment by lts-rad** [comment] 2023-02-10 17:40
This link is no longer working, @ethomson do you know which discussino this refers  to https://github.community/c/code-to-cloud/52 ?

**Comment by nikola-jokic** [comment] 2023-02-11 12:21
Hey @lts-rad,

You can use https://github.com/orgs/community/discussions/categories/actions-and-packages
