### ISSUE TITLE
Error: The directory is not empty.: '...\azure\login\v1\node_modules\...'

### ISSUE THREAD

**Issue by TheOnlyWei** [actions/runner#1436] opened 2021-10-26 22:13 UTC
**Describe the bug**
An occasional error occurs during "Set up job" step that is owned by Github Actions and not described in any user workflow file. This is the error:
```
Error: The directory is not empty. : 'C:\...\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
```
```
Error: The directory is not empty. : 'C:\...\_work\_actions\azure\login\v1\node_modules\semver'
```
This is for a workflow that runs many matrix jobs. There were around 26 jobs in total, and most of them run a step called `azure/login@v1`. The repository for this step is below:
https://github.com/Azure/login

**To Reproduce**
There is no consistent reproduction, nor do I know how to reproduce it since I don't own the "Set up job" step.

**Expected behavior**

I expect there to be no error. I am not sure why the "Set up job" step is expecting `C:\...\_work\_actions\azure\login\v1\node_modules\jest-circus\build` to be empty as I don't own "Set up job" step since it is run by default by Github Actions for all workflow jobs.

I log in a bunch of times in many jobs using azure/login, which might have contributed the the error. Here is the repository of the `azure/login@v1` step I use throughout the workflow file:
https://github.com/Azure/login

## Runner Version and Platform
Version of your runner?
'2.283.3'

OS of the machine running the runner? OSX/Windows/Linux/...
Windows Server 2019 Datacenter

## What's not working?
<img width="833" alt="github-actions-setup-job-error" src="https://user-images.githubusercontent.com/19400755/138969118-31bf6df9-a734-4979-9f74-852e4dbdbb95.png">

## Job Log 
Output
```
Error: The directory is not empty. : 'C:\...\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
```

Example build:
https://github.com/Azure-Samples/Hybrid-JavaScript-Samples/runs/4146640411?check_suite_focus=true

## Runner and Worker's Diagnostic Logs
There is only the worker log:
```
[2021-10-26 20:33:38Z INFO JobServerQueue] Job timeline record has been updated for the first time.
[2021-10-26 20:33:47Z ERR  JobExtension] Caught exception from JobExtension Initialization: System.IO.IOException: The directory is not empty. : 'C:\<PATH TO RUNNER>\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2021-10-26 20:33:47Z ERR  JobRunner] Job initialize failed.
[2021-10-26 20:33:47Z ERR  JobRunner] Caught exception from InitializeJob: System.IO.IOException: The directory is not empty. : 'C:\<PATH TO RUNNER>\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
```

I edited the log by shortening the path to runner with <PATH TO RUNNER>

**Comment by TheOnlyWei** [comment] 2021-11-09 01:14
This error is getting more and more frequent and breaking our builds, can someone take a look?

**Comment by TingluoHuang** [comment] 2021-11-09 03:26
does it always fail on the same file?
also, make sure to disable windows defender on the entire `C:\<PATH TO RUNNER>\_work` since it will hold the file handler and prevent the runner from accessing it.

**Comment by TheOnlyWei** [comment] 2021-11-09 18:38
@TingluoHuang It doesn't always fail on the same file as the example build and the two other examples I errors in the main post shows. I have turned off windows defender. I will let you know if I still see the issue.

**Comment by TingluoHuang** [comment] 2021-11-09 18:48
if it's not the same file every time, then it must be something on the machine holding the file handler randomly. Windows Defender is the most likely one.

**Comment by TheOnlyWei** [comment] 2021-11-15 18:15
Hi @TingluoHuang, I have added the folder containing all runners to the windows security exclusion, but I still got the same error in one of the builds, but it seem to be rarer now, although I am not sure. From our last 4 scheduled builds, there was only one of such failure now. This is the error:
```
Error: The directory is not empty. : 'C:\...\runners\org-actions-runner2\_work\_actions\azure\login\v1\node_modules'
```

**Comment by nikola-jokic** [comment] 2022-03-08 09:14
Hi @TheOnlyWei,

Since the issue is rare now, that is the indicator that another process is holding the file descriptor and not allowing the runner to access the file. Did you investigate which process is causing your problems?

Since the issue is not related to the runner, I am going to close this issue now, but if you need any assistance further, feel free to comment on it and we will try to help on this issue further 😊

Please, try to investigate which processes are accessing the file descriptor, and if stopping them for a moment while debugging solves your problem, it would be a clear indication that the runner is not causing this issue, and the issue is related to the other software running on the underlying host machine.

**Closed by nikola-jokic** 2022-03-08 09:14 UTC
Labels: bug
