### ISSUE TITLE
Service containers will sometimes assign different ports between IPv4 and IPv6

### ISSUE THREAD

**Issue by Nican** [actions/runner#2616] opened 2023-05-22 21:35 UTC
**Describe the bug**
My application will sometimes fail to connect to the redis service container inside of a GitHub action. The port is randomly assigned, and this bug is random. 

It looks like IPv4 and IPv6 sometimes get different ports, but `job.services.redis.ports[6379]` will return one entry or the other.

I can not find any information on how to force only IPv4, or figure out the correct listening address.

**To Reproduce**
1. Create a job with redis as a service container
2. Run the job on a self-hosted instance
3. Sometimes the application will fail to connect to the redis container.

Redis service defined as follow:
```yaml
      redis:
        image: redis:latest
        ports:
          - 6379/tcp
```

And then our service gets the port with an environment variable:
```yaml
      - run: npm run test:e2e:api:cover
        env:
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
```

**Expected behavior**
Possible solutions:
1. Force IPv4 only
2. Verify that IPv4 and IPv6 are listening on the same ports

## Runner Version and Platform
Version of your runner? 
Runner from actions-runner-linux-x64-2.303.0.tar.gz 

OS of the machine running the runner? Ubuntu 22.04 

## What's not working?
![image](https://github.com/actions/runner/assets/796294/6773356d-39af-447f-be79-7a5b7c16f68a)

**Comment by nikola-jokic** [comment] 2023-08-08 12:28
Hey @Nican,

The runner is not assigning ports to the container. The docker is. Runner only invokes docker commands here :relaxed: 
As you can see from the command log, the command executed is using the ports for docker create.

> I can not find any information on how to force only IPv4, or figure out the correct listening address.

To get around this problem, you should probably use [port mappings](https://docs.docker.com/network/#published-ports) here.

I will close this issue now since the runner is not responsible for assigning ports. It just uses your input as part of the command, and it is up to the docker to interpret it. But feel free to comment on it if you need any more input :relaxed:

**Closed by nikola-jokic** 2023-08-08 12:28 UTC
Labels: bug

**Comment by Nican** [comment] 2023-08-09 14:03
Hello @nikola-jokic, 

Thank you for taking your time to respond to my issue, and providing details on your reasoning.

Granted, Runner is not responsible for assigning the ports, but using `job.services.redis.ports[6379]` is part of the Runner specification. 

Docker may be responsible for randomly assigning ports, but Runner is still responsible for communicating to the application job what port was chosen for the service container.

Maybe there needs to be new variables to specify what port has been used. 
For example: 

- `job.services.redis.ports[6379]` would return `32833` to keep current behavior. 
- `job.services.redis.ports[6379].ipv4` would return `32834` for the assigned ipv4 port. 
- `job.services.redis.ports[6379].ipv6` would return `32833` for the assigned ipv6 port.

**Comment by nikola-jokic** [comment] 2023-08-09 14:19
Hey @Nican,

Based on the [issue in moby](https://github.com/moby/moby/issues/42442), it seems like having different ports for ipv4 and ipv6 is not expected behavior. :relaxed:
