### ISSUE TITLE
Event is triggering for every tag without matching the pattern

### ISSUE THREAD

**Issue by tharindu-dif** [actions/runner#1699] opened 2022-02-18 18:01 UTC
I have setup a mobile deployment for on create tag with specific regex pattern. But the deployment is starting for every tag regardless the pattern. Following is my yml code snippet.

```
on:
   create:
     tags:
       - '^v(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)(\()(\d+)(\))$'
```
Then I have tried with the simplest pattern which was mentioned in the documentation.

```
on:
   create:
     tags:
       -v*
```
But still the same results. It was triggering for every tag was created.

**To Reproduce**
Add one of above trigger to your yml file and create a new tag named "test"

**Expected behavior**
Deployment event should not have been started.

**Comment by ruvceskistefan** [comment] 2022-02-21 07:53
Hi @tharindu-dif,
Thanks for filing this issue! We are working on reproducing the issue, so we will get back to you as soon as we have more informations.

**Comment by ruvceskistefan** [comment] 2022-02-21 10:31
I have successfully reproduced the problem you described and I think I have a solution. The problem is that the filter in `create` will not prevent the workflow from starting when pushing the tag to a remote repository. The solution is to use event `push`, ie to make your yml file look like this (yml code snippet):
```
on:
  push:
    tags:
      - v*
```
@tharindu-dif does this work for you, ie. does this solve the problem you described?

**Comment by tharindu-dif** [comment] 2022-02-21 11:08
> I have successfully reproduced the problem you described and I think I have a solution. The problem is that the filter in `create` will not prevent the workflow from starting when pushing the tag to a remote repository. The solution is to use event `push`, ie to make your yml file look like this (yml code snippet):
> 
> ```
> on:
>   push:
>     tags:
>       - v*
> ```
> 
> @tharindu-dif does this work for you, ie. does this solve the problem you described?

Hi! Yeah seems like it's the problem. But still not working for above regex. Is there any way we can adopt regex for this as well?

**Comment by ruvceskistefan** [comment] 2022-02-21 11:45
I'm sorry, but I didn't understand you now, which part doesn't work for you? With the suggested change, when I try to push tag `test` to the repo, the workflow does not start, while when I push tag named `v1.1.1(1)` (which matches the first regex) the workflow starts. That's the behavior you want, isn't it?

**Comment by tharindu-dif** [comment] 2022-02-21 11:52
> I'm sorry, but I didn't understand you now, which part doesn't work for you? With the suggested change, when I try to push tag `test` to the repo, the workflow does not start, while when I push tag named `v1.1.1(1)` (which matches the first regex) the workflow starts. That's the behavior you want, isn't it?

Able to get it sorted as well. Following filters works for me
```
tags:
   - 'v[0-9]+.[0-9]+.[0-9]+'
```
```
tags:
   - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'
```

**Comment by ruvceskistefan** [comment] 2022-02-21 11:55
Great, thanks @tharindu-dif for the quick feedback! I will close this issue since we have solved the problem.

**Closed by ruvceskistefan** 2022-02-21 11:55 UTC
Labels: bug, awaiting-customer-response
