### ISSUE TITLE
apt update failed due to signing issue

### ISSUE THREAD

**Issue by elad-pticha** [actions/runner#3253] opened 2024-04-24 09:53 UTC
**Describe the bug**
`apt update` is failing in Linux distros due to the following error:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```

**To Reproduce**
1. Create a new workflow
2. Use `ubuntu-22.04` machine
3. Run `sudo apt-get update`

**Expected behavior**
`apt update` should not fail.

## Runner Version and Platform
Linux - ubuntu-22.04

## Job Log Output
```
2024-04-24T09:40:41.7131765Z Current runner version: '2.315.0'
2024-04-24T09:40:41.7155091Z ##[group]Operating System
2024-04-24T09:40:41.7155875Z Ubuntu
2024-04-24T09:40:41.7156182Z 22.04.4
2024-04-24T09:40:41.7156522Z LTS
2024-04-24T09:40:41.7156933Z ##[endgroup]
2024-04-24T09:40:41.7157286Z ##[group]Runner Image
2024-04-24T09:40:41.7157705Z Image: ubuntu-22.04
2024-04-24T09:40:41.7158176Z Version: 20240422.1.0
2024-04-24T09:40:41.7159162Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240422.1/images/ubuntu/Ubuntu2204-Readme.md
2024-04-24T09:40:41.7160609Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240422.1
2024-04-24T09:40:41.7161533Z ##[endgroup]
2024-04-24T09:40:41.7161913Z ##[group]Runner Image Provisioner
2024-04-24T09:40:41.7162388Z 2.0.369.1
2024-04-24T09:40:41.7162799Z ##[endgroup]
2024-04-24T09:40:41.7163768Z ##[group]GITHUB_TOKEN Permissions
2024-04-24T09:40:41.7165423Z Contents: read
2024-04-24T09:40:41.7165837Z Metadata: read
2024-04-24T09:40:41.7166465Z Packages: read
2024-04-24T09:40:41.7166957Z ##[endgroup]
2024-04-24T09:40:41.7170232Z Secret source: Actions
2024-04-24T09:40:41.7170969Z Prepare workflow directory
2024-04-24T09:40:41.7864903Z Prepare all required actions
2024-04-24T09:40:41.8135817Z Complete job name: run
2024-04-24T09:40:41.9222414Z ##[group]Run sudo apt-get update
2024-04-24T09:40:41.9223041Z [36;1msudo apt-get update[0m
2024-04-24T09:40:41.9611127Z shell: /usr/bin/bash -e {0}
2024-04-24T09:40:41.9611732Z ##[endgroup]
2024-04-24T09:40:42.3428390Z Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
2024-04-24T09:40:42.3430169Z Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
2024-04-24T09:40:42.3431940Z Err:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
2024-04-24T09:40:42.3434066Z   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
2024-04-24T09:40:42.3435865Z Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
2024-04-24T09:40:42.3437672Z Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
2024-04-24T09:40:42.3439920Z Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
2024-04-24T09:40:42.3442160Z Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
2024-04-24T09:40:42.6366705Z Get:7 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1610 kB]
2024-04-24T09:40:42.6373127Z Hit:13 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
2024-04-24T09:40:42.6676659Z Get:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [303 kB]
2024-04-24T09:40:42.6680229Z Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1830 kB]
2024-04-24T09:40:42.7082475Z Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [311 kB]
2024-04-24T09:40:42.7157852Z Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1070 kB]
2024-04-24T09:40:42.7160127Z Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [244 kB]
2024-04-24T09:40:42.8299925Z Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [27.2 kB]
2024-04-24T09:40:42.8407016Z Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [16.2 kB]
2024-04-24T09:40:43.1324607Z Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1392 kB]
2024-04-24T09:40:43.1338583Z Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [243 kB]
2024-04-24T09:40:43.1340360Z Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1768 kB]
2024-04-24T09:40:43.1341929Z Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [299 kB]
2024-04-24T09:40:43.1344043Z Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [848 kB]
2024-04-24T09:40:43.1346026Z Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [163 kB]
2024-04-24T09:40:47.5501129Z Reading package lists...
2024-04-24T09:40:47.5575832Z E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
2024-04-24T09:40:47.5578638Z E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
2024-04-24T09:40:47.5626132Z ##[error]Process completed with exit code 100.
2024-04-24T09:40:47.5907106Z Cleaning up orphan processes
```

**Comment by AdriVanHoudt** [comment] 2024-04-24 10:09
This is probably a duplicate of https://github.com/actions/runner-images/issues/9733

**Closed** 2024-05-20 11:02 UTC
Labels: bug
