### ISSUE TITLE
Action fails to start when the repository containing it contains a broken symlink

### ISSUE THREAD

**Issue by niieani** [actions/runner#1341] opened 2021-09-14 23:47 UTC
**Describe the bug**
Action fails to start when the repository containing it contains a symlink that cannot be resolved based on the files in the repository alone. The symlink has nothing to do with the action, it's just as long as your repo has a symlink that doesn't resolve, the "Setup job" will return an error.

**To Reproduce**
1. Create a repo with any Github Action
2. Commit a symlink that cannot be resolved with git files alone (i.e. symlink broken directly after checkout)
3. Try using the action

**Expected behavior**

The action runs as intended, since the symlink has nothing to do with it.

## Runner Version and Platform

'2.281.1'

Linux

## What's not working?

<img width="941" alt="Screen Shot 2021-09-14 at 4 42 42 PM" src="https://user-images.githubusercontent.com/563469/133348156-1b8fd93a-7611-4922-9e6d-b451c0b4fced.png">

## Job Log Output

Same as visible in the image, nothing else present in the logs.

**Comment by TingluoHuang** [comment] 2021-09-16 04:49
We fail to unzip the downloaded archive file since it contains a broken link.

**Comment by ruvceskistefan** [comment] 2022-02-17 13:14
Hi @niieani,
Since @TingluoHuang explained what the problem is, I'm going to close this issue. If this is still a problem for you, feel free to contact us again and reopen this issue.

**Comment by niieani** [comment] 2022-02-17 22:51
Just because you know the explanation, doesn't mean the problem is solved. The behavior is invalid. Github repositories can contain broken symlinks, and that is completely valid - e.g. those symlinks might only become valid once dependencies are installed. Unzipping of the repo should be run in a way that does not fail on broken symlinks.

**Comment by ruvceskistefan** [comment] 2022-02-18 10:01
Hi @niieani,
I reopened this issue and tried to reproduce it. I created a repository with a broken symlink and tried to perform the action, as you described. For me, the setup went without problems. Did you try to do the same on the newer version of the runner?

**Comment by niieani** [comment] 2022-02-18 23:55
@ruvceskistefan Can you link to your reproduction repo?

**Comment by ruvceskistefan** [comment] 2022-02-21 07:49
Of course, here is a [repo](https://github.com/ruvceskistefan/symlink-issue) with a symlink that references a file that is not within that repository.

**Closed** 2022-03-04 10:01 UTC
Labels: bug, awaiting-customer-response
