### ISSUE TITLE
LD_LIBRARY_PATH is modified when running Docker, causing issues

### ISSUE THREAD

**Issue by polm** [actions/runner#781] opened 2020-11-02 04:26 UTC
Sorry but I'm not sure this is the right repo to file this against. If there's a better repo let me know.

**Describe the bug**

A Docker container run via Github Actions has the `LD_LIBRARY_PATH` modified and that causes issues. For example, cloning a git repo with an https url causes libcurl related errors.

**To Reproduce**

Git clone with an https url in a Docker container run from a Github Action.

**Expected behavior**

I expect LD_LIBRARY_PATH to not be modified, or for that to be explained somewhere, but I haven't been able to find it.

## Runner Version and Platform
Version of your runner? It's hosted on Github Actions, not sure.

OS of the machine running the runner? Linux

## What's not working?

Git clone for https urls doesn't work, exits with error.

## Job Log Output

> /usr/local/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

https://github.com/polm/fugashi/runs/1291141895?check_suite_focus=true

**Comment by polm** [comment] 2020-11-02 04:27
Oh, for more details please see this issue, where this was discovered. 

https://github.com/pypa/manylinux/issues/812

**Comment by TingluoHuang** [comment] 2020-11-02 15:22
Looks like those variable are set by https://github.com/actions/setup-python/blob/main/src/find-python.ts#L121

**Comment by polm** [comment] 2020-11-03 06:56
Thanks, I will follow up there.

**Comment by polm** [comment] 2020-11-11 05:42
I checked with actions/setup-python and someone on that project says the issue is not with the setting of environment variables, but with the env vars being passed from the outer environment into the Docker container. 

https://github.com/pypa/manylinux/issues/812#issuecomment-725211079

It does seem odd that env vars would automatically go to the Docker container. Can you shed any light on that behavior?

**Comment by TingluoHuang** [comment] 2021-04-23 03:00
I am going to close this since the root cause is https://github.com/actions/setup-python/issues/159

**Closed by TingluoHuang** 2021-04-23 03:00 UTC
Labels: bug
