### ISSUE TITLE
Allow action runners inside of docker to use `container` feature

### ISSUE THREAD

**Issue by ScottPierce** [actions/runner#755] opened 2020-10-14 19:23 UTC
**Describe the enhancement**
When using https://github.com/myoung34/docker-github-actions-runner I run into the following error: 
```
Container feature is not supported when runner is already running inside container. 
```

Running docker inside of docker is a common paradigm that I was able to accomplish easily in gitlab. It's far easier to manage your runners with kubernetes or plain old docker-compose than it is to maintain a fleet of VMs. Please support using `container` when running github actions from a runner in docker.

**Comment by fishpen0** [comment] 2022-03-11 19:49
This issue looks related/ is a dupe of : https://github.com/actions/runner/issues/406

**Closed** 2022-10-20 13:49 UTC
Labels: enhancement

**Comment by ScottPierce** [comment] 2022-10-21 08:34
@nikola-jokic can you link the ticket that this ticket is a duplicate of so that myself and the 16 people who have thumbsed up this ticket can follow it for updates?

Thanks!

**Comment by nikola-jokic** [comment] 2022-10-21 11:21
Hey @ScottPierce, thanks for reaching out! Could you be so kind to post and link this feature on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback)? The page is actively monitored and putting +1 can help us to prioritize it.
We will try to keep this board scoped to the runner only, and the feedback page should be the one with proposals around extending it to support DinD in this case. :relaxed:
