### ISSUE TITLE
Add support for binding a service container to host network

### ISSUE THREAD

**Issue by Lctrs** [actions/runner#261] opened 2020-01-08 14:26 UTC
**Describe the enhancement**

Selenium containers needs to be binded to host network. Looking at the documentation, I don't think this is supported yet.

**Code Snippet**

```yaml
jobs:
  my-job:
    services:
      my-service:
        image: "my-image:latest"
        network: host
```

**Comment by TingluoHuang** [comment] 2020-01-08 18:00
@Lctrs we create a bridge docker network for each job run which should make your service container connected to the host network. Can you share some examples of what's not working?

@dakale FYI

**Comment by Lctrs** [comment] 2020-02-14 12:39
Hi @TingluoHuang,

Sorry for the late reply.

You can see my attempts here : https://github.com/Lctrs/mink-panther-driver/pull/92/files

To be more clear, let's me explain what I'm trying to achieve.

My test setup contains : 
- a web server running on the host (the VM)
- a selenium standalone chrome node running in a docker container

My test suite controls the selenium server and tells it to access pages served by the web server. Problem is that the selenium server can't talk to the web server since they are not on the same network. So my test suite fails currently when using the `services` feature.
I had to hack a [script](https://github.com/Lctrs/mink-panther-driver/blob/master/.github/workflows/continuous-integration.yml#L255) to mimick its behavior.

From what I found on the internet, this seems to be a recurring problem with Docker.

**Comment by David-VTUK** [comment] 2021-05-04 20:52
Would also like to see this - I run a job in a runner than spins up a http server to host cloud-init data for Packer builds - by default it will listen on the containers bridge address which, by design, cannot be accessed externally. Having an option to use host networking would be awesome.

**Comment by nikola-jokic** [comment] 2022-02-08 09:17
Hi @David-VTUK and @Lctrs,

Are you still seeing this issue? If you have, could you please provide an example project or a guide on how I could reproduce this on the newer versions? Should I be using this attempt: https://github.com/Lctrs/mink-panther-driver/pull/92/files?

Thanks!

**Comment by Lctrs** [comment] 2022-02-08 09:23
Hi @nikola-jokic. I don't have this use case anymore .

**Comment by nikola-jokic** [comment] 2022-02-08 09:25
Thank you so much for your answer! 

I will close this issue now, but if you experience any issues like this, feel free to open a new one!

**Closed by nikola-jokic** 2022-02-08 09:25 UTC
Labels: enhancement, Runner :heart: Container, awaiting-customer-response
