### ISSUE TITLE
Badge always incorrectly displayed as "failing"

### ISSUE THREAD

**Issue by mihaigalos** [actions/runner#1830] opened 2022-04-17 19:48 UTC
[This](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg) badge is shown as "failing" but the [tasks' statuses](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml) are all green.

**Describe the bug**
The badge was green since CD pipeline is prechecked before running, meaning it normally should never fail. The badge for it was green and it suddenly went to red - "failing", even though all constituent tasks are succeeding.

**To Reproduce**
See 1st paragraph.

**Expected behavior**
The badge is green when all tasks successful, red when at least one fails.

## Runner Version and Platform
Full yaml snapshot available [here](https://github.com/mihaigalos/aim/blob/2e9dff70d9a0df97ee6f4b25b8e9d9656e067339/.github/workflows/cd.yaml).

Simplified yaml:
```yaml
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch: # Run with Run Workflow button in GitHub Action Job.
    inputs:
      is_manual_cd:
        default: true
        description: Manual trigger

jobs:
  common-assertions:
    runs-on: ubuntu-latest
```

## OS of the machine running the runner?
Linux

**Comment by ruvceskistefan** [comment] 2022-04-19 12:04
Hi @mihaigalos,
Thanks for the reported issue! We will try to reproduce it, and I'll get back to you when I have more information or a solution.

**Comment by TingluoHuang** [comment] 2022-04-19 14:08
We break our elasticsearch index on workflow run results. 😭 
The rebuild just finished, so this problem should go away. 🙇

**Comment by mihaigalos** [comment] 2022-04-19 14:10
Sounds good, any test to guarantee this regression will never happen again? :sweat_smile:

**Comment by ruvceskistefan** [comment] 2022-04-19 14:50
During the reproduction of the bug I saw that the problem go away, and than I saw a comment written by @TingluoHuang, which further explained everything. I'm going to close this issue, feel free to comment again or reopen it if this happens again.

@mihaigalos thanks again for reporting this issue and @TingluoHuang thanks for quick response and explanation!

**Comment by mihaigalos** [comment] 2022-04-19 15:08
@ruvceskistefan, the ELS breakage is a symptom and I don't understand the root cause.
I suspect it is not fixed and will happen again.

Would advise against closing this issue or at least guarding against future regressions with a test. What do you think?

**Comment by ruvceskistefan** [comment] 2022-04-19 16:09
Makes sense, I'll reopen it and we're going to investivate the root cause.

**Comment by TingluoHuang** [comment] 2022-04-20 14:48
From what I understand, the ELS issue is outside the scope of the runner itself.
@ruvceskistefan and I don't have the full context of the ELS issue since we both primarily work on the runner itself.

I asked around to other teams and it looks like the root cause is an int32 overflow on the search index. 😭 
There will be an incident review internally for this error and repair items to make sure this won't happen again.

@mihaigalos do you mind if I close this runner issue since the issue is truly out of scope for the runner? 🙇 

You can post to https://github.community/c/code-to-cloud/github-actions/41 if you need more info or RCA about the ELS issue.

**Comment by mihaigalos** [comment] 2022-06-12 16:25
This is still manifesting with the exact same conditions as in the initial bug report.

**Comment by mihaigalos** [comment] 2022-07-17 04:53
Hi, any updates here? [This](https://github.com/mihaigalos/aim/actions/runs/2683081741) succeeded, badge is red.

**Comment by mihaigalos** [comment] 2022-08-10 19:14
Up.

**Comment by JonasVautherin** [comment] 2022-08-22 22:15
Same here, the github badges don't work for me.

**Comment by sepulvedablanco-inditex** [comment] 2022-10-13 09:17
+1

**Comment by micwoj92** [comment] 2022-10-13 09:23
I wish GitHub was 100% Free/Libre and open-source software, then skilled hackers from all around the world could fix this problem.

**Comment by MrVauxs** [comment] 2022-10-20 18:34
Same [here](https://github.com/Pf2eToolsOrg/Pf2eTools/actions/runs/3285686286/jobs/5413018043).

[![Build and Deploy](https://github.com/Pf2eToolsOrg/Pf2eTools/actions/workflows/main.yml/badge.svg)](https://github.com/Pf2eToolsOrg/Pf2eTools/actions/workflows/main.yml)

**Comment by moloch--** [comment] 2022-10-21 16:17
Same problem here: 
[![Build & Test](https://github.com/BishopFox/sliver/actions/workflows/go.yml/badge.svg)](https://github.com/BishopFox/sliver/actions/workflows/go.yml)

**Comment by MrVauxs** [comment] 2022-10-24 12:29
> Same problem here: [![Build & Test](https://github.com/BishopFox/sliver/actions/workflows/go.yml/badge.svg)](https://github.com/BishopFox/sliver/actions/workflows/go.yml)

Not anymore, the irony.

**Comment by mihaigalos** [comment] 2022-10-24 19:03
Mine still red at the moment:
[![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)

**Comment by TingluoHuang** [comment] 2022-10-24 19:12
Make sure to use the branch filter in your badge URL, by default, the badge is rendered for workflow run against your repository's default branch.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter

**Comment by mihaigalos** [comment] 2022-10-24 19:49
> Make sure to use the branch filter in your badge URL, by default, the badge is rendered for workflow run against your repository's default branch.
> https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter

Still red with explicit branch to `main`:
```
[![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg?branch=main)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)
```
[![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg?branch=main)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)

**Comment by TingluoHuang** [comment] 2022-10-24 19:54
@mihaigalos Your `main` branch didn't run the workflow for the past few months, and the last time it runs was failed.
![image](https://user-images.githubusercontent.com/1750815/197615455-e32ccf61-fa4a-4fa9-aade-542a8a008942.png)

**Comment by mihaigalos** [comment] 2022-10-24 20:08
Thanks for the clarification, this is true.
My CD pipeline is triggered on a tag. That way I tag a new version and automatically create a deployment.

I therefore need the default branch or some way of telling the badge to use `main` branch but be triggered by the tag.
In this screenshot, `1.7.x` were all successful merges to master with successful deployments. They however don't have `main` runs, why?:
![image](https://user-images.githubusercontent.com/16443090/197618812-ff84c072-035c-41a3-9294-0925c37a8dad.png)

**Comment by MrVauxs** [comment] 2022-10-24 20:54
We have the same problem. Our actions are ran on tags, so when switching to tag branches, it passes. 
But making a badge that isn't stuck to just one version is impossible.

**Comment by TingluoHuang** [comment] 2022-10-24 20:57
Please report this to https://github.com/orgs/community/discussions/categories/actions-and-packages since the runner (this repository) itself doesn't have knowledge about the badge.

**Comment by MrVauxs** [comment] 2022-10-24 21:16
> Same [here](https://github.com/Pf2eToolsOrg/Pf2eTools/actions/runs/3285686286/jobs/5413018043).
> 
> [![Build and Deploy](https://github.com/Pf2eToolsOrg/Pf2eTools/actions/workflows/main.yml/badge.svg)](https://github.com/Pf2eToolsOrg/Pf2eTools/actions/workflows/main.yml)

As a note, I just recently deleted a failed workflow run on `main`, the only one that ever existed. Now with the badge running on default, it looks like it just grabs... whatever is latest?

**Comment by mihaigalos** [comment] 2022-10-25 05:49
Worth a try. I've deleted the whole 180+ runs for my pipeline (No checkmoxes so had to do ClickOps 180*3 times. Sigh.)
No result, badge is still red.

**Comment by mihaigalos** [comment] 2022-10-25 05:54
Also, `main` is red (see below). No idea why, now there are runs since I've deleted them all:

[![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg?branch=main)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)
```
[![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg?branch=main)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)
```

**Comment by MrVauxs** [comment] 2022-10-26 00:44
Love how these update regardless of what you said. Both now show no status.

**Comment by sorenwacker** [comment] 2022-11-07 17:27
Same problem.

**Comment by mihaigalos** [comment] 2022-11-08 09:12
I removed all previous runs on `main` and successfuly got a green badge.

**Comment by ruvceskistefan** [comment] 2022-11-22 15:10
@mihaigalos, I'm glad that it worked for you. I'll close this issue, if you are still getting the same error you can reopen it.

**Closed by ruvceskistefan** 2022-11-22 15:10 UTC
Labels: bug

**Comment by lunatidalscents** [comment] 2022-11-27 22:40
Build a blank yml build badge and apply the correct code

**Comment by wireless90** [comment] 2022-12-02 08:07
> Worth a try. I've deleted the whole 180+ runs for my pipeline (No checkboxes so had to do ClickOps 180*3 times. Sigh.) No result, badge is now "no status" in the create status badge page: ![image](https://user-images.githubusercontent.com/16443090/197693305-5e538ec1-7b27-449e-a668-5c7b666f1b73.png)
> 
> .. but it's _red_ when I consume it i.e. here!: [![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)
> 
> ```
> [![CD](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml/badge.svg)](https://github.com/mihaigalos/aim/actions/workflows/cd.yaml)
> ```

thanks worked
