### ISSUE TITLE
[Windows] Runner failing to extract project - Path too long 

### ISSUE THREAD

**Issue by RAORelewise** [actions/runner#1746] opened 2022-03-11 08:23 UTC
**Describe the bug**
After succesfully setting up the first runner for our docs website, i moved on to the next. And here the extraction of the project is failing, as the path exceeds the max length allowed on windows.

`Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'C:\actions-runner-my-r
elewise\_work\my.relewise.com\my.relewise.com\main\b7fc4a2e-4d2a-4ec4-a651-46d82e1b6b6c\brianhdk-my.relewise.com-77928d
6004bfaa38b59effe973533d51b9455863\src\Infrastructure.Database.Migrations\M1636740[26](https://github.com/brianhdk/my.relewise.com/runs/5507992461?check_suite_focus=true#step:2:26)2_RemoveColumnsFromTriggersTables.c
s'."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\a ...`

I noticed the path that the runner is building, is somehow including 2 GUIDs.. 

Path:
C:\actions-runner-my-relewise\_work\my.relewise.com\my.relewise.com\b7fc4a2e-4d2a-4ec4-a651-46d82e1b6b6c\brianhdk-my.relewise.com-77928d6004bfaa38b59effe973533d51b9455863

Why is it doing this? Where are these 2 "GUID" folders coming from? The path it creates for our docs site is:

C:\actions-runner\_work\docs.relewise.com\docs.relewise.com

No double nested GUID folders.

the .tar file it downloads is: b7fc4a2e-4d2a-4ec4-a651-46d82e1b6b6c.tar.gz where is this guid coming from?

**Expected behavior**
Shouldnt extract into these crazy long paths.

## Runner Version and Platform
2-288.1

Windows server 2019

**Comment by ruvceskistefan** [comment] 2022-03-11 10:36
Hi @RAORelewise,
Thanks for filling this issue! We will try to reproduce the bug, so I will get back to you as soon as I have some news.

**Comment by TingluoHuang** [comment] 2022-03-11 15:16
@RAORelewise can you share some log/YAML for your workflow run?
we need to figure out who is creating `C:\actions-runner-my-relewise_work\my.relewise.com\my.relewise.com\b7fc4a2e-4d2a-4ec4-a651-46d82e1b6b6c\brianhdk-my.relewise.com-77928d6004bfaa38b59effe973533d51b9455863` first.

**Comment by RAORelewise** [comment] 2022-03-16 13:16
[_diag.zip](https://github.com/actions/runner/files/8262386/_diag.zip)

@TingluoHuang Is it these logs?

**Comment by ruvceskistefan** [comment] 2022-03-16 13:43
Yes, that's it, but can you send just a log of that problematic workflow run and YAML file of the workflow? Here you send the logs of all the workflows runs, so we don't know where the problem is.

**Comment by RAORelewise** [comment] 2022-03-16 13:46
@ruvceskistefan 

Workflow file:

`name: .NET 6 Deploy to IIS

on: 
  push:
    branches:
      - master

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up .NET 6
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x'
          include-prerelease: true
    
    - name: Build with dotnet
      run: dotnet build src/Website/ --configuration Release

    - name: dotnet publish 
      run: dotnet publish src/Website/ -c Release -o my.relewise.com.webapp

    - name: Stop IIS Website
      run: Stop-WebSite my.relewise.com
      
    - name: Stop IIS Worker pool
      run: Stop-WebAppPool my.relewise.com
         
    - name: Wait for worker pool to stop
      uses: juliangruber/sleep-action@v1
      with:
        time: 3s
      
    - name: Copy over new website
      run: |
        Remove-Item -path C:/inetpub/wwwroot/my.relewise.com/ClientApp/dist -recurse
        Copy-Item ./my.relewise.com.webapp/* C:/inetpub/wwwroot/my.relewise.com -Recurse -Force
    
    - name: Start IIS worker pool
      run: Start-WebAppPool my.relewise.com
    
    - name: Start IIS Website
      run: Start-WebSite my.relewise.com
`

The workflow has never run successfully, so I would assume all of them have an error

**Comment by ruvceskistefan** [comment] 2022-03-16 13:54
Thanks @RAORelewise, we're investigating your issue. I'll get back to you as soon as I have more information.

**Comment by RAORelewise** [comment] 2022-03-17 08:01
@ruvceskistefan We have 2 subdomains that runs on the server IIS machine, using the exact same workflow (different locations ofc), that work flawlessly. Only the my.relewise.com domain has those 2 random GUID's in their path. So we are a little confused as to where the origin of them are coming from 😄

**Comment by ruvceskistefan** [comment] 2022-03-17 09:12
To be honest, I'm confused too 😄
I'll try to understand the cause of the problem and I'll get back to you as soon as I have more information. Thanks for the additional explanation.

**Comment by Jaybomb** [comment] 2022-05-03 12:02
I'm also getting this error, here's my workflow yml:

`name: On Push
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build action
    runs-on: runner-group-a
    steps:
      - uses: actions/checkout@master`
      
Error:
`Exception calling "ExtractToDirectory" with "2" argument(s): "The specified path, file name, or both are too long. The 
fully qualified file name must be less than 260 characters, and the directory name must be less than [24](https://github.schneider-electric.com/EM-SPD-NMC-R2/svn/runs/119378?check_suite_focus=true#step:2:24)8 characters."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PathTooLongException`
   
Path getting created on runner:
C:\actions-runner\_work\svn\svn\95c07055-ccbf-4975-9156-71618b15e04d\EM-SPD-NMC-R2-svn-288ef63e5d4653c52f574aae7b4df357c238ab7a

Zipfile:
95c07055-ccbf-4975-9156-71618b15e04d.tar.gz

**Comment by anitakrueger** [comment] 2022-06-22 22:19
This seems to happen only when `git` is not installed on the machine.

```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Writing archive to disk
Extracting the archive
```

After installing `git`, the checkout action worked fine.

**Comment by tGrothmannFluffy** [comment] 2022-06-29 09:00
I am seeing the same issue on my runner:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\Administrator\actions-runner\_work\REDACTED_local\REDACTED_local\40b62b0c-7a92-48d1-a78a-6e43543e2580.tar.gz', 'C:\Users\Administrator\actions-runner\_work\REDACTED_local\REDACTED_local\40b62b0c-7a92-48d1-a78a-6e43543e2580')"
```

```
Exception calling "ExtractToDirectory" with "2" argument(s): "The specified path, file name, or both are too long. The 
fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\U ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PathTooLongException
Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

**Comment by tGrothmannFluffy** [comment] 2022-06-29 11:47
thanks,

I also managed to fix the issue using:
https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html

**Comment by jason-oc** [comment] 2022-06-29 15:24
> This seems to happen only when `git` is not installed on the machine.
> 
> ```
> The repository will be downloaded using the GitHub REST API
> To create a local Git repository instead, add Git 2.18 or higher to the PATH
> Downloading the archive
> Writing archive to disk
> Extracting the archive
> ```
> 
> After installing `git`, the checkout action worked fine.

Yup, we got around it by just installing git on the runner. When git is installed it doesn't do this nonsense with the archive and does a clone instead which does cloney things which are better for the environment.

**Comment by surajsalunkhe** [comment] 2023-01-30 11:58
> thanks,
> 
> I also managed to fix the issue using: https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html

solution works for me

**Comment by ruvceskistefan** [comment] 2023-02-10 11:50
Hey all,
I'm glad to hear that you've found solutions that work for you.

Regarding this issue, firstly it would be good if you register a runner with the shortest path possible.
Additionally, this is not a runner issue but an issue with tools that use old `windows-api` which has this problem.

I'll close this issue, if it should be open feel free to reopen it at any time.

**Closed by ruvceskistefan** 2023-02-10 11:50 UTC
Labels: bug, Runner Bug

**Comment by primostasis123** [comment] 2024-01-09 11:06
I have just recently encounter this problem. but I cant  just change the registry to fix the "problem" especially in production..
any alternatives? like create a new path instead?

**Comment by mzanoni** [comment] 2024-01-09 11:31
You can install the git cli and restart the runner service. That also fixes the problem.

**Comment by danielscatigno-ncpc** [comment] 2024-12-16 15:04
What about a Non Self-Hosted runner? what can we do?

**Comment by AnnaLewis123** [comment] 2025-06-14 07:21
When a runner (such as GitLab Runner, Jenkins, or other CI/CD tools) fails to extract a project on Windows due to "path too long" errors, it’s usually because Windows restricts file paths to 260 characters.

Long Path Tool helps you:

Extract files and projects with long directory paths

Bypass the default Windows path limit

Avoid errors during build, clone, or extraction processes

**Comment by annalopezz** [comment] 2026-02-24 06:12
I recommend using the Long Path Tool to resolve this issue.
