### ISSUE TITLE
Workflow doesn't get triggered on repository creation

### ISSUE THREAD

**Issue by alexlemaire** [actions/runner#673] opened 2020-08-21 13:45 UTC
**Describe the bug**
I have a workflow set on some of my template repositories that should get triggered on `push`. I'm seeing an inconsistency in terms of behavior when creating a new repository from my templates: this workflow is sometimes not triggered on the initial commit (`First commit`)

**To Reproduce**
1. Create a template repository
2. Add a new workflow that should get triggered on push (except on the template repository) such as:
```
name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    if: github.repository != 'user/your-template-repository'
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo "Hello World!"
```
3. Create a new repository based on this template
4. Sometimes the workflow `init` will run inside of the new repository, but sometimes it doesn't

**Expected behavior**
The `push` trigger should always start the workflow on repository creation from template

## Runner Version and Platform
`2.272.0`

OS of the machine running the runner? `ubuntu-latest`

**Comment by shawnwhit** [comment] 2020-11-13 21:12
Seeing the same issue as well.

**Comment by dskvr** [comment] 2021-01-07 02:18
It would be swell if this were addressed, templates generally need some special work done on them.

**Comment by gagoar** [comment] 2021-02-09 00:40
We are seeing the same issue in our organization

**Comment by colinsr** [comment] 2021-02-18 18:17
Bump => My workflows are hit or miss when creating a new project from a template in company's Org as well.
My current workaround when the workflow is a dud involves pushing a commit on the branch I'm targeting.
Certainly leaves a "not ready for primtetime" taste in my mouth TBH.
:confused:

**Comment by RostiMelk** [comment] 2021-05-26 20:34
Bump. Experiencing this issue using the `on: create` trigger as well.

**Comment by sakula-fidelity-factory** [comment] 2021-08-05 01:07
same here.
My workaround for now is waiting 5 to 10 seconds before triggering the workflow.

**Comment by nikola-jokic** [comment] 2022-07-11 13:36
Hey everyone,

Sorry for the late response. If you are still experiencing the same issue, please, post this to the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site which is actively monitored. The issue is not related to the runner itself, but the platform more generally, since the workflow never landed on the runner.  Using this site ensures that we route your problem to the correct team.

I am going to close this issue since it is not related to the runner. If you think it is related, feel free to comment on it or re-open this issue :relaxed:

**Closed by nikola-jokic** 2022-07-11 13:36 UTC
Labels: bug
