### ISSUE TITLE
support risc-v platform Architecture in self-hosted runner

### ISSUE THREAD

**Issue by szhen11** [actions/runner#2247] opened 2022-11-09 06:16 UTC
**Describe the enhancement**
do we plan or have support risc-v platform Architecture in self-hosted runner? There are some RISC-V platforms want to be setup as github self-hosted runners for building and testing.

**Code Snippet**
NA

**Additional information**
NA

**Comment by nikola-jokic** [comment] 2022-11-10 10:35
Hey @szhen11,

This issue is actually a duplicate of https://github.com/actions/runner/issues/2157
Also, please refer to this comment for more information: https://github.com/actions/runner/issues/2157#issuecomment-1268226862

**Closed by nikola-jokic** 2022-11-10 10:35 UTC
Labels: enhancement
