### ISSUE TITLE
runner for windows/x86

### ISSUE THREAD

**Issue by camptatopenmars** [actions/runner#1721] opened 2022-03-01 16:27 UTC
I have a windows device driver that I'm testing using self-hosted CI/CD pipelines - eventually feeding into the windows HLK test automation.  While not common anymore, there are still a number of x86 devices in the real world and x86 remains a supported architecture for window 10.  Since kernel drivers must be the same architecture as the kernel I am not able to test our x86 driver build in the same CI/CD pipeline since there is no github runner for x86.... which is unfortunate.

**Comment by nikola-jokic** [comment] 2022-03-01 16:39
Hi @camptatopenmars,

This issue is a duplicate of #423. I will close it now since the enhancement has been added to the project board. You can put 👍 to the issue I have referenced which helps us prioritize enhancement requests 😊

**Closed by nikola-jokic** 2022-03-01 16:39 UTC
Labels: enhancement
