### ISSUE TITLE
choco install ghostscript fails with access denied

### ISSUE THREAD

**Issue by carygravel** [actions/runner#1430] opened 2021-10-22 08:07 UTC
**Describe the bug**

I've been using `choco install ghostscript` in an action for months with no problem. In the last couple of days, it has started [failing](https://github.com/carygravel/Perl-PDF-Builder/runs/3973198335?check_suite_focus=true) with `Access to the path 'C:\ProgramData\chocolatey\lib\Ghostscript.app\tools\gs9550w64.exe' is denied`.

**To Reproduce**
1. Go to https://github.com/carygravel/Perl-PDF-Builder/runs/3973198335?check_suite_focus=true
2. ReRun the action
3. See error

**Expected behavior**
I would expect ghostscript to install cleanly.

## Runner Version and Platform
Windows latest

## What's not working?
The install

## Job Log Output
https://github.com/carygravel/Perl-PDF-Builder/runs/3973198335?check_suite_focus=true

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment] 2022-03-02 14:13
Hey @carygravel,

I looked at the issue, and it seems like it is working now. The step you mentioned is being executed. Could you please tell me if you are still seeing this issue?

**Comment by carygravel** [comment] 2022-03-03 19:27
[It looks as though it is working now](https://github.com/carygravel/Perl-PDF-Builder/runs/5412166726?check_suite_focus=true).

Unfortunately, the same workflow has [developed an unrelated problem installing Readonly](https://github.com/carygravel/Perl-PDF-Builder/runs/5412166625?check_suite_focus=true), which really should have been trivial.

**Comment by nikola-jokic** [comment] 2022-03-04 10:20
Hey @carygravel,

Could you please tell me if this issue is related to the hosted runner? While reading it, it seems to me that the underlying host is causing you problems, but I am not entirely sure. And could you please turn on debugging so we can review the execution log and confirm where the root cause of the issue is happening?

**Comment by nikola-jokic** [comment] 2022-03-08 08:50
Hi @carygravel, since this issue is related to the underlying host, and we are trying to keep the issues related to the runner repository itself here, I am going to close this one.

Since I have seen that you are using hosted runners, please post this issue to the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose), to ensure the correct team sees this 😊. Thank you!

**Closed by nikola-jokic** 2022-03-08 08:50 UTC
Labels: bug, awaiting-customer-response
