### ISSUE TITLE
Scheduler running twice few minutes to hour between each other

### ISSUE THREAD

**Issue by Hanrider8** [actions/runner#1266] opened 2021-08-17 12:27 UTC
Hello, I have scheduler action in my project which should trigger once a day (I am ok with delay) and send via curl request to one of my endpoint but somehow I am getting confirmation message from this endpoint twice each day right now almost one hour between each other.

here is my yaml file: 

> name: App reminder
on:
  schedule:
    - cron: '20 15 * * *'
jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Match reminder
        run: curl https://myurl.com/api/cron

log of action from yesterday: 

> Run curl https://myurl.com/api/cron
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     4  100     4    0     0      4      0  0:00:01 --:--:--  0:00:01     4
100     4  100     4    0     0      4      0  0:00:01 --:--:--  0:00:01     4
 true

notification from endpoint: 
![image](https://user-images.githubusercontent.com/20664583/129725165-c78e0342-86a0-4354-96d5-1714439553d6.png)

Could you please tell me where issue is ? If I call my endpoint normally I get only one notification.

**Comment by nikola-jokic** [comment] 2022-03-28 07:54
Hi @Hanrider8,

Thank you for submitting this issue. I have been able to reproduce the delay but I believe that two notifications are executed because the service called the runner incorrectly. Since this issue is not related to the runner itself, but rather to the platform in general, I will close this issue now. Please, if you experience the same issue again, post this feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team.

**Closed by nikola-jokic** 2022-03-28 07:54 UTC
Labels: bug
