### ISSUE TITLE
Actions are 800% slower

### ISSUE THREAD

**Issue by asarkar** [actions/runner#818] opened 2020-11-24 08:32 UTC
**Describe the bug**

A Gradle build that takes 1m 7s on my 2016 Macbook Pro, 16 GB, 2.9 GHz Quad-Core Intel Core i7, takes 8m 33s on GitHub.

**Expected behavior**
I expect builds to take _ressoanably comparable_ time. I understand I'm a personal user and not paying, but 1m vs 8m is not deprioritization, it's agony. 

## Runner Version and Platform
Don't know. Does the link below help?

OS of the machine running the runner? Don't know. Does the link below help?

## What's not working?
Already described.

## Job Log Output
https://github.com/asarkar/okgrpc/actions/runs/380603827

## Runner and Worker's Diagnostic Logs
https://github.com/asarkar/okgrpc/actions/runs/380603827

**Comment by Cyberbeni** [comment] 2020-11-25 08:47
https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

The free users get the same runners as the paying ones. Use caching and parallelise if you want to speed up your workflow.

**Comment by ethomson** [comment] 2022-02-04 16:27
I'm sorry that you're disappointed with the speed - be sure that you're [caching dependencies](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows) between runs.  If it's just a matter of horsepower, one option is that you can run GitHub Actions on [your own runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).  In the future, we'll have [more powerful options](https://github.com/github/roadmap/issues/161) for your hosted builds.

Either way, this is not a bug in the runner application, so I'm going to close this issue.  Feedback about GitHub Actions should go to the [GitHub feedback site](https://github.com/github/feedback/discussions/8473).

**Closed by ethomson** 2022-02-04 16:27 UTC
Labels: bug

**Comment by felix314159** [comment] 2025-06-17 12:47
Still relevant
