### ISSUE TITLE
Updates to ActionManager error message.

### ISSUE THREAD

**Issue by wtphilbrook** [actions/runner#1806] opened 2022-04-04 20:02 UTC
Suggesting an update to `/Users/will.philbrook/Repos/runner/src/Runner.Worker/ActionManager.cs` lines 507 + 1093 `InvalidOperationException` and `NotSupportedException` to include a note about file structure. 

The `./.github/actions/{action_name}/action.yml` structure seems to be required but is not well documented in the docs or in this error message.

The below would do the trick and would have saved me a few hours of head-banging:
```If using a local action, ensure this file structure exists: `./.github/actions/{action_name}/action.yml`"```

**Comment by ruvceskistefan** [comment] 2022-04-05 06:21
Hi @wtphilbrook,

Thanks for the reported enhancement! We will consider your proposal and possibly create a PR with the required changes. Can you just send me the URL to the workflow run, to see in what situation did you get those error messages?

**Comment by Im2451soon** [comment] 2022-04-05 06:23
uR주소는 모르겠어요.
모든 피트코인 상장에 제 계정으로 메일만 바꿔 거래하는걸 확인했습니다

**Comment by wtphilbrook** [comment] 2022-04-05 15:01
Oh yeah for sure!

[Here's an example of it working correctly.](https://github.com/wtphilbrook/action-test/actions/runs/2096954140)

[Here's an example of it failing with the above error.](https://github.com/wtphilbrook/action-test/actions/runs/2096966071)
```Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/action-test/action-test/.github/actions/heyworld'. Did you forget to run actions/checkout before running your local action?```

[Here's another example when using a slightly different file path.](https://github.com/wtphilbrook/action-test/actions/runs/2096968782)
☝️ This one is probably the best example of the error being confusing.
```Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/action-test/action-test/.github/actions/action.yml'. Did you forget to run actions/checkout before running your local action? ```

The workflow files for both of these are in two separate branches on that throwaway repo:
[Working](https://github.com/wtphilbrook/action-test/tree/working)
[Not Working](https://github.com/wtphilbrook/action-test/tree/not-working)

**Comment by ruvceskistefan** [comment] 2022-04-05 15:15
Great, thank you. I'll investigate everything you've sent, so I'll get back to you as soon as I have some news.

**Comment by ruvceskistefan** [comment] 2022-04-05 16:17
The problem is in your workflow file, but now I see where the confusion is.

In the [working](https://github.com/wtphilbrook/action-test/tree/working) example, in the `helloworld.yml` file, in `uses` part you specify the path to the directory where `action.yml` file is located: `uses: ./.github/actions/heyworld`.

In the [not working](https://github.com/wtphilbrook/action-test/tree/not-working) example, in the same workflow file, in `uses` part you specify the path of the `action.yml` file: `uses: ./.github/actions/action.yml`.

It's only necessary to specify the path of the directory where `action.yml` file is located, so in not working example you should just change uses to: `uses: ./.github/actions`.

I'm going to close this issue since this part is documented. Fell free to ask or reopen it if there is anything else unclear.

**Closed by ruvceskistefan** 2022-04-05 16:17 UTC
Labels: enhancement, Runner Feature, awaiting-customer-response

**Comment by wtphilbrook** [comment] 2022-04-05 16:22
Oh! That makes sense now that you spell it out. I still think there's an argument for updating that thrown exception in `Runner.Worker/ActionManager.cs` to be a bit more clear as to the issue, as it's a bit of a red herring.

Regardless, this post will hopefully help others who ran into the same issues as me 👍

**Comment by ruvceskistefan** [comment] 2022-04-05 16:28
We will consider a change in the error message if there are more users with a similar problem. Thanks for the reported issue and enhancement suggestion!
