### ISSUE TITLE
Unhelpful error message when writing malformed data to $GITHUB_ENV

### ISSUE THREAD

**Issue by jbzdarkid** [actions/runner#1596] opened 2022-01-07 15:41 UTC
**Describe the bug**
When writing a particular string to `$GITHUB_ENV`, the runner throws a nullref, i.e. `Object reference not set to an instance of an object.`

**To Reproduce**
See https://github.community/t/nullref-when-writing-to-github-env-from-python/221606 . The following python code reproduces the issue.
```py
import environ
with open(environ['GITHUB_ENV'], 'a') as f:
  subcomment = """\
Please verify the following diffs:
- [ ] All articles ran in 0:00:56.697371: [en](https://wiki.tf/d/3106540) [ar](https://wiki.tf/d/3106518) [cs](https://wiki.tf/d/3106519) [da](https://wiki.tf/d/3106520) [de](https://wiki.tf/d/3106521) [es](https://wiki.tf/d/3106522) [fi](https://wiki.tf/d/3106523) [fr](https://wiki.tf/d/3106524) [hu](https://wiki.tf/d/3106525) [it](https://wiki.tf/d/3106526) [ja](https://wiki.tf/d/3106527) [ko](https://wiki.tf/d/3106528) [nl](https://wiki.tf/d/3106529) [no](https://wiki.tf/d/3106530) [pl](https://wiki.tf/d/3106531) [pt](https://wiki.tf/d/3106532) [pt-br](https://wiki.tf/d/3106533) [ro](https://wiki.tf/d/3106534) [ru](https://wiki.tf/d/3106535) [sv](https://wiki.tf/d/3106536) [tr](https://wiki.tf/d/3106537) [zh-hans](https://wiki.tf/d/3106538) [zh-hant](https://wiki.tf/d/3106539)
- [ ] Wanted templates ran in 0:00:37.264911: [en](https://wiki.tf/d/3106541)"""
  f.write('GITHUB_COMMENT<<EOF')
  f.write(subcomment)
  f.write('EOF')
```

**Expected behavior**
The bug here is about a lack of newline after the EOF marker. So, I would expect an error which says something like "malformed EOF marker", or "EOF marker too long". A very precient error might say "EOF marker missing newline".

## Runner Version and Platform
Runner version 2.285.1, Ubuntu 20.04.3

## What's not working?
https://github.com/jbzdarkid/TFWiki-scripts/runs/4728629242?check_suite_focus=true

## Job Log Output
```
2022-01-06T15:26:24.2881206Z ##[group]Run python master.py pull_request
2022-01-06T15:26:24.2882292Z [36;1mpython master.py pull_request[0m
2022-01-06T15:26:24.2930406Z shell: /usr/bin/bash -e {0}
2022-01-06T15:26:24.2930893Z env:
2022-01-06T15:26:24.2931483Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
2022-01-06T15:26:24.2932252Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
2022-01-06T15:26:24.2933714Z   WIKI_USERNAME: ***
2022-01-06T15:26:24.2934234Z   WIKI_PASSWORD: ***
2022-01-06T15:26:24.2934678Z ##[endgroup]
2022-01-06T15:26:24.4627453Z ##[error]Unable to process file command 'env' successfully.
2022-01-06T15:26:24.4642131Z ##[error]Object reference not set to an instance of an object.
2022-01-06T15:26:24.4820362Z ##[group]Run peter-evans/find-comment@v1
2022-01-06T15:26:24.4820930Z with:
2022-01-06T15:26:24.4821305Z   issue-number: 13
2022-01-06T15:26:24.4821857Z   comment-author: github-actions[bot]
2022-01-06T15:26:24.4822902Z   token: ***
2022-01-06T15:26:24.4823414Z   repository: jbzdarkid/TFWiki-scripts
2022-01-06T15:26:24.4823954Z   direction: first
2022-01-06T15:26:24.4824355Z env:
2022-01-06T15:26:24.4824913Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
2022-01-06T15:26:24.4825643Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
2022-01-06T15:26:24.4826209Z ##[endgroup]
```

**Comment by ruvceskistefan** [comment] 2022-02-03 10:58
Hi @jbzdarkid,
Have you tried the same thing on a newer runner version?

When I try to reproduce the issue, I get an error message: `Error: Invalid environment variable value. Matching delimiter not found 'EOFsome subcomment test test testEOF'`(I just use a different subcommand string). I can change the error message so that it ends with an "EOF marker missing newline".

Please just confirm to me if on the newer version of the runner you get the same error message as me.

**Comment by jbzdarkid** [comment] 2022-02-03 11:52
Made a branch for this repro, re-ran the action. Same error message.
https://github.com/jbzdarkid/TFWiki-scripts/actions/runs/1789247416
```
2022-02-03T11:51:28.7959538Z Waiting for a runner to pick up this job...
2022-02-03T11:51:29.5486495Z Job is waiting for a hosted runner to come online.
2022-02-03T11:51:33.6164291Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2022-02-03T11:51:37.9452786Z Current runner version: '2.287.1'
2022-02-03T11:51:37.9483509Z ##[group]Operating System
2022-02-03T11:51:37.9484183Z Ubuntu
2022-02-03T11:51:37.9484661Z 20.04.3
2022-02-03T11:51:37.9484968Z LTS
2022-02-03T11:51:37.9485353Z ##[endgroup]
2022-02-03T11:51:37.9485807Z ##[group]Virtual Environment
2022-02-03T11:51:37.9486233Z Environment: ubuntu-20.04
2022-02-03T11:51:37.9486709Z Version: 20220131.1
2022-02-03T11:51:37.9487377Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220131.1/images/linux/Ubuntu2004-Readme.md
2022-02-03T11:51:37.9488250Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220131.1
2022-02-03T11:51:37.9488790Z ##[endgroup]
2022-02-03T11:51:37.9489283Z ##[group]Virtual Environment Provisioner
2022-02-03T11:51:37.9489762Z 1.0.0.0-main-20220128-1
2022-02-03T11:51:37.9490177Z ##[endgroup]
...
2022-02-03T11:51:45.5897243Z ##[endgroup]
2022-02-03T11:51:45.7479073Z ##[error]Unable to process file command 'env' successfully.
2022-02-03T11:51:45.7490763Z ##[error]Object reference not set to an instance of an object.
```

**Comment by ruvceskistefan** [comment] 2022-02-03 14:37
@jbzdarkid Thanks for replying and reproducing the error, I'm working on it, o I'll let you know as soon as there's any progress.

**Comment by ruvceskistefan** [comment] 2022-02-10 11:15
Hi @jbzdarkid,

I researched the bug you reported and noticed that you don't get the same two errors for the two examples you posted.
I did a reproduction of the minimal working example you posted in the first comment, to determine that the problem is really a lack of newline after the EOF marker. This is definitely the cause of the bug, but the runner handles this problem appropriately, as you can see from the job log output below:
```2022-02-10T10:29:06.3443640Z ##[group]Run python3 -u scripts/env_example.py
2022-02-10T10:29:06.3444010Z [36;1mpython3 -u scripts/env_example.py[0m
2022-02-10T10:29:06.3704770Z shell: /bin/bash -e {0}
2022-02-10T10:29:06.3705030Z env:
2022-02-10T10:29:06.3705300Z   pythonLocation: /Users/runner/hostedtoolcache/Python/3.10.2/x64
2022-02-10T10:29:06.3705590Z ##[endgroup]
2022-02-10T10:29:06.4351790Z ##[error]Unable to process file command 'env' successfully.
2022-02-10T10:29:06.4367250Z ##[error]Invalid environment variable value. Matching delimiter not found 'EOFsome subcomment test test testEOF'
2022-02-10T10:29:06.4543580Z Post job cleanup.
```

Here is the Python code that I used in the minimal reproduction example:

```
from os import environ

with open(environ['GITHUB_ENV'], 'a') as f:
  subcomment = "some subcomment test test test"
  f.write('GITHUB_COMMENT<<EOF')
  f.write(subcomment)
  f.write('EOF')
```

Are you sure that the second example has the same cause of the error as the first one? If the cause is not the same, I can close this issue and you can report a new one. From my research, it seems to me that the lack of a new line after the EOF marker is not a problem, but I wanted to check with you too.

**Comment by jbzdarkid** [comment] 2022-02-10 12:58
> I researched the bug you reported and noticed that you don't get the same two errors for the two examples you posted.

What do you mean? I get this error message for both runs:
`##[error]Object reference not set to an instance of an object.`

> I did a reproduction of the minimal working example you posted in the first comment, to determine that the problem is really a lack of newline after the EOF marker. This is definitely the cause of the bug, but the runner handles this problem appropriately, as you can see from the job log output below:

I don't know why you felt the need to change the python code, but if you use different python code you will get a different error.
This particular issue is specific to this python code -- in particular, I'm pretty sure it's required that the malformed string contains newlines and markdown links.

> Are you sure that the second example has the same cause of the error as the first one?

I'm not sure why you think the two examples are different -- it's the same python. I made a branch from the commit in the initial issue and fixed a slight issue in the YAML, but the repro was untouched.

**Comment by ruvceskistefan** [comment] 2022-02-10 14:32
Okay, now I see. I thought the problem was specifically the lack of a new line after the EOF marker and that the `subcomment` string itself is not important. Thanks for the clarification, I am working on solving the problem.

**Comment by ruvceskistefan** [comment] 2022-02-15 07:39
Hi @jbzdarkid,
I created a PR that will close the described issue. Thanks again for your contribution and further explanation of the bug!

**Closed** 2022-02-24 11:13 UTC
Labels: bug
