### ISSUE TITLE
Workflows suddenly failing with "Error in fetching the workflow file"

### ISSUE THREAD

**Issue by nmargaritis** [actions/runner#2304] opened 2022-12-06 16:02 UTC
**Describe the bug**
We experience a fail with workflows paths during builds while using reusable workflows. The files are unchanged and some workflows fail with the aforementioned parse error. It fails on different paths every-time and some times it does not fail. This is on a pipeline that has been stable for the past year or so.

For example this is from 30mins ago
![Screenshot 2022-12-06 at 17 54 55](https://user-images.githubusercontent.com/7851375/205961155-9e1d7819-d6d1-41e5-8053-cbd63909175b.png)

while this is from 15mins ago, same path fails in the first and succeeds in the other attempt. Files are unchanged.
![Screenshot 2022-12-06 at 17 55 36](https://user-images.githubusercontent.com/7851375/205961277-80f9f766-7a81-475c-a182-59e0379f4549.png)

For example
```
- error parsing called workflow "./.github/workflows/build-node.yml": error in fetching the workflow file
- error parsing called workflow "./.github/workflows/push-docker-images.yml": error in fetching the workflow file
```

**To Reproduce**
1. Trigger reusable workflows
3. See error from time to time / does not happen every time

**Expected behavior**
Files and paths are correct. They worked for a year without this and it is been like 3 hours that 50% of the builds fail with a different path parse error. The same workflows work as well, it is not consistent or a problem of paths.

## Runner Version and Platform
Version of your runner? github managed - ubuntu latest - 2.299.1

OS of the machine running the runner? Linux

## What's not working?
![Screenshot 2022-12-06 at 17 54 55](https://user-images.githubusercontent.com/7851375/205960709-8de3fd88-b4a1-4abc-8392-dab2b3184458.png)
![Screenshot 2022-12-06 at 17 54 38](https://user-images.githubusercontent.com/7851375/205960715-61ff9141-3659-41a5-9b9f-85e335d8bc1d.png)

**Comment by crisbal** [comment] 2022-12-06 16:29
This also happened to me on some self-hosted runners, with runner 2.299.1

**Comment by dligthart** [comment] 2022-12-07 09:03
We are experiencing the same issue also using a self hosted runner.

**Comment by 1itachi** [comment] 2022-12-07 18:50
we are also experiencing this issue, if we close and reopen the PR then the workflow gets picked up again.

**Comment by pexa-afarrugia** [comment] 2022-12-09 03:32
ditto

**Comment by nikola-jokic** [comment] 2022-12-14 15:51
Hey everyone!

Thank you for reporting it! We are aware of this issue, and we are tracking it internally. It does not seem to be a runner issue, so I will be closing it here. That does not mean that the issue is resolved as of today, but rest assured we are working on it.

**Closed by nikola-jokic** 2022-12-14 15:51 UTC
Labels: bug

**Comment by shinsenter** [comment] 2024-01-25 22:53
Any update in 2024? This also happened to me.
