### ISSUE TITLE
Job step logs aren't expandable after run is complete

### ISSUE THREAD

**Issue by ajschmidt8** [actions/runner#2387] opened 2023-01-19 21:22 UTC
**Describe the bug**

I've recently noticed that the logs for some job steps aren't expandable after the job has been completed.

This issue has only appeared within the last day and has happened across several job runs in more than one repository.

I've included links to some of the jobs that I've identified are affected by the issue below.

Here is a screenshot demonstrating the issue ([job link](https://github.com/rapidsai/rmm/actions/runs/3961882200/jobs/6787907533)):

![image](https://user-images.githubusercontent.com/7400326/213561576-adc58bb0-1098-4972-947f-366740122ba5.png)

**To Reproduce**
1. Navigate to any of the job URLs below
2. Observe that `C++ build` job step is not expandable

Job URLs;

- https://github.com/rapidsai/rmm/actions/runs/3961882200/jobs/6787907533
- https://github.com/rapidsai/rmm/actions/runs/3960478794/jobs/6784735717
- https://github.com/rapidsai/cugraph/actions/runs/3960467947/jobs/6784706560
- https://github.com/rapidsai/cugraph/actions/runs/3960087734/jobs/6783805676
- https://github.com/rapidsai/cugraph/actions/runs/3959918630/jobs/6783407922
- https://github.com/rapidsai/cugraph/actions/runs/3959219413/jobs/6781798148

**Expected behavior**
All job steps should be expandable

## Runner Version and Platform

Version `2.301.1` on Linux

## What's not working?

Described above

## Job Log Output

N/A

## Runner and Worker's Diagnostic Logs

N/A

**Comment by ruvceskistefan** [comment] 2023-01-23 13:12
Hey @ajschmidt8,
Thanks for reporting issue, I would assume that this is related to your build script. Could you add 

```
- name: C++ build
        run: |
          ${{ inputs.build_script }}
          echo test
```

to see if it will expand or we need to investigate further.

**Comment by ajschmidt8** [comment] 2023-01-23 18:55
@ruvceskistefan, I'm not sure that it's related to our build script. It has worked perfectly fine in the past. The issue started out of the blue.

The issue is also intermittent. For instance, here's a newer run of one of the problematic workflows that I posted above in which the `C++ build` step is expandable.

- https://github.com/rapidsai/rmm/actions/runs/3963389802/jobs/6811306170

There were no changes made to our shared workflow that would cause this to start working again.

**Comment by ruvceskistefan** [comment] 2023-03-13 07:40
Hey @ajschmidt8,
I've checked the last few jobs, and it seems that the problem is not happening anymore so I'll close this issue, feel free to reopen it if this happens again and we'll investigate it further.

**Closed by ruvceskistefan** 2023-03-13 07:40 UTC
Labels: bug, awaiting-customer-response

**Comment by ajschmidt8** [comment] 2023-07-13 15:51
@ruvceskistefan, for what it's worth we're still experiencing the issue occasionally.

Unfortunately the latest incidents are in private repositories that I can't link here.

**Comment by ajschmidt8** [comment] 2023-08-02 23:29
@ruvceskistefan, can we get this re-opened?

@dillon-cullinan mentioned that he is exhibiting the same problem here: https://github.com/actions/runner/issues/886#issuecomment-1654754462
