### ISSUE TITLE
workflow fails on Run actions/setup-node@v1

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#702] opened 2020-09-14 05:54 UTC
Associated GitHub Community ticket: https://github.community/t/ci-started-to-fail-on-run-actions-setup-node-v1/131883

The customer is using CI workflow to generate NPM package. Recently, the workflow started to fail when running actions/setup-node@v1 .
The customer said that they did not changed any configurations of workflow.
The following is the error message:
```js
Run actions/setup-node@v1
  with:
    node-version: 12
    registry-url: https://npm.pkg.github.com/
    scope: @ierp-ai
    always-auth: false
##[error]No such file or directory
##[debug]System.ComponentModel.Win32Exception (2): No such file or directory
##[debug]   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
##[debug]   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
##[debug]   at System.Diagnostics.Process.Start()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Run actions/setup-node@v1
```

I also tested the **`setup-node v1`** action with the similar inputs on my side, but did not reproduce the issue. The action can work fine without any errors.

**Comment by hross** [comment] 2020-09-14 10:08
Transferred this to the https://github.com/actions/runner repo since it seems related to the release.

**Comment by khhhum** [comment] 2020-09-14 10:22
@BrightRan in your tests: https://github.com/TestWorkflowsRML/GHA-Syntax/actions/runs/253535466/workflow you are using the newer v2.x versions of the github checkout action. But the original poster, as well as us are using "v1"

**Comment by khhhum** [comment] 2020-09-14 11:57
upgrading to v2 of the github checkout action seems to have solved the issue for us. Would like to understand why :)

**Comment by flesicek** [comment] 2020-09-14 12:33
I resolved my failing CI with 2 changes:
1. As @khhhum suggested, changed checkout to version 2 from version 1. -> Why there is such dependency, no idea and if you have breaking change, it must be somehow communicated

2. There is another breaking change, originally when setting `working-directory` in `run` command, CI would change the directory and stay there for all consequent actions, now the working directory is always root so I need to rewrite the workflow -> again why there is such a breaking change without communication ...

🤔

**Comment by dnorth98** [comment] 2020-09-14 14:06
Glad to have found this issue as we were seeing the same problem.  I can also confirm that updating to checkout v2 AND changing the working dir inside each step fixes the problem.

Now the drag of updating the workflows in 100+ repos.  I'd also love to know why the breaking change in checkout v1.

**Comment by thboop** [comment] 2020-09-14 15:40
Sorry to hear you are encountering issues. We are working on a fix for this bug and will update this issue with more information as soon as it is available!

**Comment by thboop** [comment] 2020-09-14 17:52
Sorry to hear all of you are encountering this!

I have good news, we are working on rolling out a new runner version to fix this issue, and should be rolled out to all customers as soon as we can safely do so in the next day or two!

In the meantime, you should be able to upgrade to `actions/checkout@v2` to fix this issue. 
Something to note, [actions/checkout@v2 no longer sets the github workspace to the path input](https://github.com/actions/checkout/blob/main/adrs/0153-checkout-v2.md#path), which means you may need to manually set the [working directory for your runs step](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun)

We strongly recommend using `actions/checkout@v2` and you should upgrade as soon as it is feasible for you to do so. 

We have also identified the missing test that would have covered this use case, and will address that gap.

**Comment by flesicek** [comment] 2020-09-14 19:14
Thank you @thboop for the update and your effort 👍

**Comment by dnorth98** [comment] 2020-09-14 20:01
Thanks @thboop for the update and the fix!  I did indeed sweep all of our repos this morning and switched to checkout v2 and added a `cd` to each of the steps where we needed to set the folder. 

I guess the plus is I've got most of our repos using checkout v2 (and took the time to update to cache v2 at the same time!)

Thanks again!

**Comment by khhhum** [comment] 2020-09-15 11:15
in our case, bugs in the v2 checkout actions prevents us from upgrading. But I can confirm that the new release of the github runner fixes the problem with v1 for us.

**Comment by thboop** [comment] 2020-09-15 19:08
The new Runner is rolled out! I'm going to close this issue but please let me know if you are still seeing problems and we can reopen this issue and address them!

**Closed by thboop** 2020-09-15 19:08 UTC
