### ISSUE TITLE
`PATH` variable not being updated

### ISSUE THREAD

**Issue by maifeeulasad** [actions/runner#2293] opened 2022-12-01 17:44 UTC
**Describe the bug**
`PATH` variable is not being updated

**To Reproduce**

 - `export PATH="${PATH}:$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin"`, `export PATH=$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin:$PATH` after running either of these, it succeeds
 - but when I do echo, it doesn't return me the newly updated path.

**Expected behavior**
`PATH` variable should have been updated

## Runner Version and Platform
 - Version of your runner?
  - I guess the latest one, not sure, but most probably `Runner Image, Version: 20221119.2`

 - OS of the machine running the runner? OSX/Windows/Linux/...
   -  `ubuntu-20.04.5`

## What's not working?
`PATH` variable is not being updated

![image](https://user-images.githubusercontent.com/29339330/205122037-c7cf1ded-479d-4fe0-8ede-3fa5d5fd9c61.png)

## Job Log Output
Job: https://github.com/maifeeulasad/unmukto/actions/runs/3590283087/jobs/6043518013

Look under `echo` section.

 CI instruction: https://github.com/maifeeulasad/unmukto/blob/c32497cf1154aa7860fc0a6008569f3d20d4f4db/.github/workflows/build.yaml

## Runner and Worker's Diagnostic Logs
n/a

**Comment by maifeeulasad** [comment] 2022-12-01 17:47
I have even tested it on with a simpler job. Ref: https://github.com/maifeeulasad/action-echo/actions/runs/3595020623/jobs/6054003707

**Comment by nikola-jokic** [comment] 2022-12-02 09:10
Hey @maifeeulasad,

So the reason for this is that each script step is written to a file, which later gets executed by the shell you choose, or the default one that would apply. Everything you write in a step is going to be written there. So if you write `export PATH=$PATH:/your/path`, it is going to be exported to the rest of the commands that are being invoked by that script.

In other words, all exports are visible only to that script, and the scripts that are being called from it. It will not modify the environment of the entire job. It is only scoped to the step.

You can expose PATH on your workflow level like the following:
```yaml
name: Export PATH to all steps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      PATH: $PATH:/path/you-would-like
    steps:
    - ...
```

I will close this issue, since this is by design. I hope this helps and feel free to comment on it if I did not explain it well :relaxed:

**Closed by nikola-jokic** 2022-12-02 09:10 UTC
Labels: bug
