### ISSUE TITLE
Service installation does not work on Fedora

### ISSUE THREAD

**Issue by 2bdkid** [actions/runner#1193] opened 2021-07-06 20:39 UTC
**Describe the bug**
Using the included `svc.sh` to configure a startup service does not work as expected

**To Reproduce**
1. Run `sudo ./svc.sh install`

**Expected behavior**
The service to start without errors

## Runner Version and Platform
Latest

OS of the machine running the runner? OSX/Windows/Linux/...
Fedora x64

## What's not working?
Please include error messages and screenshots.

```
[brady@fedora github-actions-runner]$ sudo ./svc.sh start

/etc/systemd/system/actions.runner.2bdkid-fedora-kernel.desktop.service
× actions.runner.2bdkid-fedora-kernel.desktop.service - GitHub Actions Runner (2bdkid-fedora-kernel.desktop)
     Loaded: loaded (/etc/systemd/system/actions.runner.2bdkid-fedora-kernel.desktop.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-07-06 16:36:56 EDT; 5ms ago
    Process: 3879 ExecStart=/home/brady/.local/opt/github-actions-runner/runsvc.sh (code=exited, status=203/EXEC)
   Main PID: 3879 (code=exited, status=203/EXEC)
        CPU: 2ms

Jul 06 16:36:56 fedora.local systemd[1]: Started GitHub Actions Runner (2bdkid-fedora-kernel.desktop).
Jul 06 16:36:56 fedora.local systemd[3879]: actions.runner.2bdkid-fedora-kernel.desktop.service: Failed to locate executable /home/brady/.local/opt/github-actions-runner/runsvc.sh: Permission denied
Jul 06 16:36:56 fedora.local systemd[3879]: actions.runner.2bdkid-fedora-kernel.desktop.service: Failed at step EXEC spawning /home/brady/.local/opt/github-actions-runner/runsvc.sh: Permission denied
Jul 06 16:36:56 fedora.local systemd[1]: actions.runner.2bdkid-fedora-kernel.desktop.service: Main process exited, code=exited, status=203/EXEC
Jul 06 16:36:56 fedora.local systemd[1]: actions.runner.2bdkid-fedora-kernel.desktop.service: Failed with result 'exit-code'.
```
## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by fhammerl** [comment] 2021-07-12 12:37
Hi @2bdkid , this looks like an access problem, perhaps a selinux problem to boot. I believe the problem is trying to start a system service with a binary that's in a user's personal directory (`/home/brady/.local/opt/github-actions-runner/runsvc.sh`), which is not allowed in SELinux. 

You can temporarily bypass SELinux at your own risk with `sudo setenforce 0`, I believe that would let you run the service, then you can turn it back on.

**Comment by 2bdkid** [comment] 2021-07-12 13:09
Ok, I moved the service file to `~/.local/share/systemd/user/` and started it as a systemd user service and it works fine. Maybe that should be an install option in the future.

**Comment by fhammerl** [comment] 2021-07-19 14:00
I'm closing this issue now as would not classify it as a bug. Feel free to refer to it in a feature-request or PR.

**Closed by fhammerl** 2021-07-19 14:00 UTC
Labels: bug

**Comment by vorburger** [comment] 2024-10-19 13:57
see #3186 (& #3104).
