### ISSUE TITLE
safe_sleep function...

### ISSUE THREAD

**Issue by mathieu-aubin** [actions/runner#1673] opened 2022-02-09 06:14 UTC
**Describe the bug**
Seems like the function does achieve correct sleep times when neother sleep nor ping are present

i have taken the liberty of writing a little script showing the effects of the current code and a suggestion on how to essentially fix, under recent bash version, using SECONDS bash internal timer

the script i wrote can be found here https://0x0.st/oXL1.txt

Feel free to do whatever with this but as i said, it doesnt seem to work currently (if both ping and sleep are missing) so thats a good enough reasom to either FIX or remove useless code

Thanks!

**Comment by mathieu-aubin** [comment] 2022-02-09 06:15
oh, thats in
src/Misc/layoutroot/run-helper.sh.template

**Comment by ruvceskistefan** [comment] 2022-02-09 08:19
Hi @mathieu-aubin,
Thanks for filing this issue! I'm reproducing it now and I'll get back to you as soon as possible!

**Comment by mathieu-aubin** [comment] 2022-02-09 08:35
[![asciicast](https://asciinema.org/a/HSzeAOlQEqaNppQA7gqMRrzfQ.svg)](https://asciinema.org/a/HSzeAOlQEqaNppQA7gqMRrzfQ)

**Comment by ruvceskistefan** [comment] 2022-02-09 10:52
Thanks @mathieu-aubin for the very detailed description of the problem and the proposed solution! We're considering a solution so I'll probably create PR that will close this issue.

**Comment by mathieu-aubin** [comment] 2022-02-09 14:00
I could do a PR quick but honestly, i wanted to have confirmation beforehand. If the function is useless since ANY and EVERY places runners can be installed does for sure contain `sleep` command, there just is no need to keep the code.

Otherwise, remove the multiple IF checks and just use the method i proposed as a "no dependency, internal solution".

SECONDS variable has been in bash for... well.. 25+ years so i think you are safe with such a solution.

**Comment by ruvceskistefan** [comment] 2022-02-09 17:39
I created a PR that should close this issue. Thank you @mathieu-aubin for your contribution!

**Comment by ruvceskistefan** [comment] 2022-03-01 16:49
Hi @mathieu-aubin,
Due to the [feature request](https://github.com/actions/runner/issues/1698) to use `safe_sleep` instead of standard `sleep` function in all bash scripts, I created a new [PR](https://github.com/actions/runner/pull/1707) (already merged to the main). This PR contains changes that were in the previously linked PR (just in the new bash script), as well as those additional requests. Therefore, I will close this issue. Please feel free to reopen it if you think it is necessary.
Thanks again for your contribution and suggestions!

**Closed by ruvceskistefan** 2022-03-01 16:49 UTC
Labels: bug

**Comment by mathieu-aubin** [comment] 2022-03-01 17:25
that was some complicated netting for such trivial (and problem fixing, yet only potential) addition!

Take care and keep it up!
