### ISSUE TITLE
Android emulator on macos blank screenshots and videos

### ISSUE THREAD

**Issue by kopax-polyconseil** [actions/runner#2287] opened 2022-11-30 12:06 UTC
**Describe the bug**

We use GitHub action for end to end testing for iOS and Android app, in case of failure, we take screenshots and video of the tests.

It works fine locally for both iOS and Android, in GitHub action, it works with iOS simulator, but on Android, the screenshots and video are transparent and black

- Issue was reported to appium https://github.com/appium/appium/issues/17837 , but they advised us to ask here.
- Duplicate also here https://github.com/wix/Detox/issues/3578

**To Reproduce**

See below for workflow, this is an example of workflow that have the problem : https://github.com/pass-culture/pass-culture-app-native/actions/runs/3574751323

**Expected behavior**
We expect to have proper screenshots and video of our app

## Runner Version and Platform

`macos-12`

## What's not working?

This is how it look like for the screenshots
![image](https://user-images.githubusercontent.com/77674046/204536866-98d297de-90b4-4716-b725-0879831baa0f.png)

This is the video shot in CI:

<video src="https://user-images.githubusercontent.com/77674046/204561099-597271b2-9bcd-4b68-ba41-e7273432b2b6.mp4"></video>
This is the video log: [wdio-0-0-Video-reporter.log](https://github.com/appium/appium/files/10114136/wdio-0-0-Video-reporter.log)

## Job Log Output

- github action workflow: https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/.github/workflows/e2e-android-app.yml
- code to do screenshot: https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/e2e/config/wdio.shared.conf.ts#L159-L174

## Runner and Worker's Diagnostic Logs

Appium log : https://github.com/pass-culture/pass-culture-app-native/actions/runs/3573959420/jobs/6008640936

**Comment by ayush547** [comment] 2022-12-14 06:40
Try setting the avd to use "-gpu host", this solved my issue.
`nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot -no-audio -gpu host -no-boot-anim -qemu -m 2048 > /dev/null 2>&1 &
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'`

**Comment by kopax-polyconseil** [comment] 2022-12-14 13:41
I have tried to use with action https://github.com/ReactiveCircus/android-emulator-runner:

- `-gpu host -no-boot-anim`
- `-no-snapshot -no-audio -gpu host -no-boot-anim -qemu -m 2048`
- `-gpu host -no-boot-anim -qemu -m 2048`
- `-gpu host -qemu`
- `-gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim`

Nothing worked, with `-gpu host`, in macos runner, I don't even suceed to start the emulateur. Do you have any clue ?

**Comment by kopax-polyconseil** [comment] 2022-12-14 13:42
> Try setting the avd to use "-gpu host", this solved my issue. `nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot -no-audio -gpu host -no-boot-anim -qemu -m 2048 > /dev/null 2>&1 & $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'`

**Comment by ayush547** [comment] 2022-12-14 14:25
This is the script I am using, you could try this, worked on macos-latest (11 atm)
        #!/usr/bin/env bash

        # Install AVD files
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;default;x86_64'

        # Create emulator
        echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -d 19 --package 'system-images;android-27;default;x86_64'

         # list emulator
        echo "Available emulator"
        $ANDROID_HOME/emulator/emulator -list-avds

        if false; then
        emulator_config=~/.android/avd/android_emulator.avd/config.ini
          # The following is to support empty OR populated config.ini files,
          # the state of which is dependant on the version of the emulator used (which we don't control),
          # Replace existing config (NOTE we're on MacOS so sed works differently!)
        sed -i .bak 's/hw.lcd.density=.*/hw.lcd.density=420/' "$emulator_config"
        sed -i .bak 's/hw.lcd.height=.*/hw.lcd.height=1920/' "$emulator_config"
        sed -i .bak 's/hw.lcd.width=.*/hw.lcd.width=1080/' "$emulator_config"
          # Or, add new config
        if ! grep -q "hw.lcd.density" "$emulator_config"; then
          echo "hw.lcd.density=420" >> "$emulator_config"
        fi
        if ! grep -q "hw.lcd.height" "$emulator_config"; then
          echo "hw.lcd.height=1920" >> "$emulator_config"
        fi
        if ! grep -q "hw.lcd.width" "$emulator_config"; then
          echo "hw.lcd.width=1080" >> "$emulator_config"
        fi
        echo "Emulator settings ($emulator_config)"
        cat "$emulator_config"
        fi

        echo "Starting emulator"

        # Start emulator in background
        nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot -no-audio -gpu host -no-boot-anim -qemu -m 2048 > /dev/null 2>&1 &
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

        #list online device/emulator
        $ANDROID_HOME/platform-tools/adb devices

        echo "Emulator started"

**Comment by nikola-jokic** [comment] 2022-12-15 09:56
Hey @kopax-polyconseil,

When you say it works locally, does it mean that this works when you run the self-hosted runner? And also, does it work on macos-11?

If that is the case, it would be great if you can post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it.
This does seem to me like a machine permission issue, but I'm not sure. Please let us know if you are seeing this issue on the self-hosted machine, or if is it maybe related to the hosted machine not having permission to do this

**Comment by kopax-polyconseil** [comment] 2022-12-15 10:56
Hello @nikola-jokic , thanks a lot for your reply!

> When you say it works locally, does it mean that this works when you run the self-hosted runner? 

When I say it work locally, it means it work on my linux system (I usually do Android development on linux, but it also work well for iOS development on my macbook), both without runner being involved. 

> And also, does it work on macos-11?

Do you mean a runner running on macos-11 ? 

> If that is the case, it would be great if you can post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it.
This does seem to me like a machine permission issue, but I'm not sure. Please let us know if you are seeing this issue on the self-hosted machine, or if is it maybe related to the hosted machine not having permission to do this

Sure, I am not sure my macbook machine is macos 11, but I can definitely try to run a self hosted runner and check the results.

**Comment by kopax-polyconseil** [comment] 2022-12-15 10:58
@ayush547 thanks for sharing the whole action. 

> This is the script I am using, you could try this, worked on macos-11

Do you  mean the runner macos-11 offered by github action ?

I can see you have a bunch of `hw.lcd` which I probably don't have, may I ask for the results of the `cat "$emulator_config"` so I can compare both of our configuration. Thanks

**Comment by ayush547** [comment] 2022-12-15 13:08
@kopax-polyconseil Yes talking about the hosted macos-11.
The cat command did not get hit, you should be good to go without that section added.

**Comment by kopax-polyconseil** [comment] 2022-12-15 13:09
Hi @ayush547 sorry your message is to broad for me to understand it.

> The cat command did not get hit,

What do you mean ? scripts fail before ?

>  you should be good to go without that section added.

What section are you referring to ? For you I don't need to setup in `hw.lcd` ?

**Comment by nikola-jokic** [comment] 2022-12-19 08:44
Hey, I will close this issue now since it is not related to the runner, but feel free to comment on it :relaxed:
I hope you have resolved your issue :relaxed:

**Closed by nikola-jokic** 2022-12-19 08:44 UTC
Labels: bug, awaiting-customer-response

**Comment by kopax-polyconseil** [comment] 2022-12-20 10:50
> Hey, I will close this issue now since it is not related to the runner, but feel free to comment on it relaxed I hope you have resolved your issue relaxed

Hello @nikola-jokic, I got the same reaction here when asking the appium team https://github.com/appium/appium/issues/17837#issuecomment-1331365186 , for them it is related to the runner configuration, see https://github.com/appium/appium/issues/17837#issuecomment-1331365186

To me, it is unclear where to ask for support, and everyone close any trace of problem prior resolution while problem is widely affecting everyone.

**Comment by nikola-jokic** [comment] 2022-12-20 11:16
Hey @kopax-polyconseil,

The issue is being closed since it is not related to the runner. As pointed out, this affects the machine running your runner, so [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) repository is the place to go.
The runner basically runs what you tell it to run. If the machine does not support that action, it won't be executed. The same issue would be with a docker action if you don't have a docker installed on your machine.

This issue is the same. If the runner running on your machine does not have a support to execute a command, the command will fail (either with exit code or not executing what you have expected). That is why I suggested that you post the issue to the VirtualEnvironments. The repository is maintaining images running hosted runners. So they can provide better explanation or help you fix your issue
