### ISSUE TITLE
Failed to resolve action download info. Error: The operation was canceled.

### ISSUE THREAD

**Issue by abitrolly** [actions/runner#876] opened 2020-12-21 15:21 UTC
I see this failing build - https://github.com/mindsdb/mindsdb_native/runs/1576684338

![image](https://user-images.githubusercontent.com/8781107/102791997-eaf68500-43b8-11eb-9509-2df741907eea.png)

The error message is not explaining where the problem is. The workflow file seems to be https://github.com/mindsdb/mindsdb_native/actions/runs/430459772/workflow

**Comment by kdambekalns** [comment] 2021-01-21 08:15
That is probably caused by a used action no longer existing…

**Comment by abitrolly** [comment] 2021-01-21 09:11
```
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
```
Only two of those are at the failing job there.

**Comment by TingluoHuang** [comment] 2021-04-23 19:27
Sorry, I can't find the log anymore, I am going to close this for now, free feel to reopen if this happened again.

**Closed by TingluoHuang** 2021-04-23 19:27 UTC
Labels: bug
