### ISSUE TITLE
MacOs M1 Github Runner Service times out when running manually in terminal session

### ISSUE THREAD

**Issue by F-WRunTime** [actions/runner#2117] opened 2022-09-09 19:06 UTC
**Describe the bug**
The runner does not start on the M1 as expected. The service does not register properly with launchctl under a user domain. 
Running run.sh as a user ultimately will timeout if tried to run in an indefinite terminal session. 

**To Reproduce**
1. Follow Github provided installation [instructions](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners) for MacOs
```
2. Run ./run.sh
 Roughly within 30 minutes or less the script will disconnect / reconnect aborting workflow actions and anything running when a disconnect occurs.
```
2022-09-09 18:12:49Z: Runner reconnected.
2022-09-09 18:22:05Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.
```

**Expected behavior**
Service remains connected

## Runner Version and Platform
2.296.1

**Comment by ruvceskistefan** [comment] 2022-09-12 13:04
Hey @F-WRunTime  thank you for the report we are digging into this issue.

Can you give us more information on when this is occurring (runner failing to pick up new jobs or disconnecting in the middle of jobs or some other case)

**Comment by pilif** [comment] 2022-09-13 07:32
We're also seeing mysterious timeout errors, this time on Arch Linux ARM64 (Asahi Linux on a MacMini).

The runners are stuck at the "Authentication" phase and looking at the diag log, it's timing out a GET request. However, if I issue a GET request to that URL with curl, I get an immediate response.

This started happening only very recently.

Debug log:

```
[2022-09-13 07:30:27Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO HostContext] Well known config file 'Credentials': '/usr/local/var/github-runners/1/.credentials'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO HostContext] Well known config file 'Runner': '/usr/local/var/github-runners/1/.runner'
[2022-09-13 07:30:27Z INFO Listener] Runner is built for Linux (Arm64) - linux-arm64.
[2022-09-13 07:30:27Z INFO Listener] RuntimeInformation: Linux 5.19.0-asahi-5-1-ARCH #1 SMP PREEMPT_DYNAMIC Sat, 20 Aug 2022 09:23:11 +0000.
[2022-09-13 07:30:27Z INFO Listener] Version: 2.296.2
[2022-09-13 07:30:27Z INFO Listener] Commit: 21c30edf1e7a80e041649848ea1d91b885a8762e
[2022-09-13 07:30:27Z INFO Listener] Culture:
[2022-09-13 07:30:27Z INFO Listener] UI Culture:
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO Listener] Validating directory permissions for: '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO CommandLineParser] Parse
[2022-09-13 07:30:27Z INFO CommandLineParser] Parsing 15 args
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: False
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding Command: configure
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: url
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding option 'url': 'https://github.com/xxxx'
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: token
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding option 'token': '***'
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: name
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding option 'name': 'armci1-1'
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: work
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding option 'work': '/usr/local/var/github-runners/1/_work'
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: labels
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding option 'labels': 'baremetal'
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: runnergroup
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding option 'runnergroup': 'Default'
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: unattended
[2022-09-13 07:30:27Z INFO CommandLineParser] parsing argument
[2022-09-13 07:30:27Z INFO CommandLineParser] HasArgs: True
[2022-09-13 07:30:27Z INFO CommandLineParser] arg: replace
[2022-09-13 07:30:27Z INFO CommandLineParser] Adding flag: unattended
[2022-09-13 07:30:27Z INFO Listener] Arguments parsed
[2022-09-13 07:30:27Z INFO Runner] ExecuteCommand
[2022-09-13 07:30:27Z INFO ConfigurationStore] currentAssemblyLocation: /usr/local/var/github-runners/1/bin/Runner.Listener.dll
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO ConfigurationStore] binPath: /usr/local/var/github-runners/1/bin
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO ConfigurationStore] RootFolder: /usr/local/var/github-runners/1
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO HostContext] Well known config file 'Runner': '/usr/local/var/github-runners/1/.runner'
[2022-09-13 07:30:27Z INFO ConfigurationStore] ConfigFilePath: /usr/local/var/github-runners/1/.runner
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO HostContext] Well known config file 'Credentials': '/usr/local/var/github-runners/1/.credentials'
[2022-09-13 07:30:27Z INFO ConfigurationStore] CredFilePath: /usr/local/var/github-runners/1/.credentials
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO HostContext] Well known config file 'MigratedCredentials': '/usr/local/var/github-runners/1/.credentials_migrated'
[2022-09-13 07:30:27Z INFO ConfigurationStore] MigratedCredFilePath: /usr/local/var/github-runners/1/.credentials_migrated
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Bin': '/usr/local/var/github-runners/1/bin'
[2022-09-13 07:30:27Z INFO HostContext] Well known directory 'Root': '/usr/local/var/github-runners/1'
[2022-09-13 07:30:27Z INFO HostContext] Well known config file 'Service': '/usr/local/var/github-runners/1/.service'
[2022-09-13 07:30:27Z INFO ConfigurationStore] ServiceConfigFilePath: /usr/local/var/github-runners/1/.service
[2022-09-13 07:30:27Z INFO CommandSettings] Flag 'help': 'False'
[2022-09-13 07:30:27Z INFO CommandSettings] Flag 'version': 'False'
[2022-09-13 07:30:27Z INFO CommandSettings] Flag 'commit': 'False'
[2022-09-13 07:30:27Z INFO CommandSettings] Flag 'check': 'False'
[2022-09-13 07:30:27Z INFO CommandSettings] Command 'configure': 'True'
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE:
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-09-13 07:30:27Z INFO Terminal] WRITE: |
[2022-09-13 07:30:27Z INFO Terminal] WRITE: Self-hosted runner registration
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE:                         |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-09-13 07:30:27Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-09-13 07:30:27Z INFO ConfigurationManager] ConfigureAsync
[2022-09-13 07:30:27Z INFO ConfigurationStore] IsConfigured()
[2022-09-13 07:30:27Z INFO ConfigurationStore] IsConfigured: False
[2022-09-13 07:30:27Z INFO ConfigurationManager] Is configured: False
[2022-09-13 07:30:27Z INFO CommandSettings] Arg 'url': 'https://github.com/xxxxx'
[2022-09-13 07:30:27Z INFO CommandSettings] Remove url from Arg dictionary.
[2022-09-13 07:30:27Z INFO CommandSettings] Arg 'token': '***'
[2022-09-13 07:30:27Z INFO CommandSettings] Remove token from Arg dictionary.
[2022-09-13 07:30:28Z INFO ConfigurationManager] Http response code: OK from 'POST https://api.github.com/actions/runner-registration'
[2022-09-13 07:30:28Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2022-09-13 07:30:28Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2022-09-13 07:30:28Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-09-13 07:30:28Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2022-09-13 07:30:28Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-09-13 07:30:28Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2022-09-13 07:30:28Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-09-13 07:24:58Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<<some id that's probably private>>/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2022-09-13 07:24:58Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<<some id that's probably private>>/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2022-09-13 07:24:58Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2022-09-13 07:24:58Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2022-09-13 07:24:58Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-09-13 07:24:58Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-09-13 07:25:38Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<<some id that's probably private>>/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 100 seconds.
[2022-09-13 07:25:38Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2022-09-13 07:25:38Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-09-13 07:25:59Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<<some id that's probably private>>/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2022-09-13 07:25:59Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<<some id that's probably private>>/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2022-09-13 07:25:59Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2022-09-13 07:25:59Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2022-09-13 07:25:59Z INFO RunnerServer] Catch exception during connect. 4 attempt left.
[2022-09-13 07:25:59Z INFO RunnerServer] Catch exception during connect. 4 attempt left.
[2022-09-13 07:25:59Z ERR  RunnerServer] System.TimeoutException: The HTTP request timed out after 00:01:00.
```

**Comment by pilif** [comment] 2022-09-13 09:03
Update: this turns out to be caused by an IPv6 routing issue on our end. forcing the runner's machine to do IPv4 only fixes it. I'm now working on getting IPv6 fixed and then I'll report back.

What's interesting is that some of the API calls seemed to have succeeded - those are probably not using IPv6 yet, whereas githubusercontent.com is.

**Comment by pilif** [comment] 2022-09-13 09:17
can confirm: Fixing IPv6 has fixed the problem for us.

The confusion arose because one request was fine but then the ones to githubusercontent.com failed and also that when I tried with `curl`, it was silently falling back to trying v4 once v6 was unsuccessful. 

You *could* add support for v6 to `api.github.com` to make this fail completely and you *should* probably add support to trying over v4 when v6 fails.

**Comment by ruvceskistefan** [comment] 2022-09-26 10:25
@pilif Thank you for your report and explanation for given issue. Since i't not runner bug I'll close it. Feel free to reopen if there are more cases on runner side.

**Closed by ruvceskistefan** 2022-09-26 10:25 UTC
Labels: bug, awaiting-customer-response

**Comment by jkruse14** [comment] 2023-02-19 12:47
> Update: this turns out to be caused by an IPv6 routing issue on our end. forcing the runner's machine to do IPv4 only fixes it. I'm now working on getting IPv6 fixed and then I'll report back.
> 
> What's interesting is that some of the API calls seemed to have succeeded - those are probably not using IPv6 yet, whereas githubusercontent.com is.

It looks like I'm running into this same issue - how do you ensure the runner's machine is doing IPv4 only? We have both enabled in our networking on AWS

**Comment by jkruse14** [comment] 2023-02-22 12:02
Removing the IPv6 assignment fixed my issue, too! I created subnets without IPv6 (setting `assign_ipv6_address_on_creation` to `false`) and the issue was then resolved and authentication took place.

Side note: originally, `amazon-linux-extras` just hung during the start up when trying to install docker. The resolved that issue as well.
