### ISSUE TITLE
Runner not using latest update, keeps trying to update to already installed update

### ISSUE THREAD

**Issue by TheOnlyWei** [actions/runner#1736] opened 2022-03-07 20:44 UTC
**Describe the bug**
Github runner tries to download and update to new 2.288.1 version from 2.287.1 for Windows. The download exits, so I have to execute run.cmd again. But when I run it again, it uses the old 2.287.1 and attempts to download 2.288.1 version again (it is already installed as I can see it in the Github Actions runner folder). Therefore, I cannot run Github Actions runner anymore.

**To Reproduce**
Run run.cmd from runner version 2.287.1.

**Expected behavior**
The Github runner should update and start running. Instead, it stops running after failing to update to 2.288.1. This is probably because 2.288.1 is already installed.

## Runner Version and Platform
2.287.1 is being recognized, but 2.288.1 is installed as well.

OS of the machine running the runner? OSX/Windows/Linux/...
Windows Server 2016 Datacenter 64-bit

## What's not working?
Output of run.cmd:
```
PS C:\azurestack-sdk-ci\runners\actions-runner-0> .\run.cmd

√ Connected to GitHub

Current runner version: '2.287.1'
2022-03-07 19:19:47Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.288.1 runner
PS C:\azurestack-sdk-ci\runners\actions-runner-0>
```

## Job Log Output
No jobs were run.

## Runner and Worker's Diagnostic Logs
One of the errors in the Runner_...log file in the  _diag/ log directory:
```
[2022-03-07 19:19:51Z INFO SelfUpdater] Version '2.288.1' of 'agent' package available in server.
[2022-03-07 19:19:51Z INFO SelfUpdater] Current running runner version is 2.287.1
[2022-03-07 19:19:51Z INFO SelfUpdater] An update is available.
[2022-03-07 19:19:51Z INFO Terminal] WRITE LINE: Runner update in progress, do not shutdown runner.
[2022-03-07 19:19:51Z INFO SelfUpdater] CloneDotnetRuntimeTime: 744ms
[2022-03-07 19:19:51Z INFO SelfUpdater] CloneExternalsTime: 104ms
[2022-03-07 19:19:51Z INFO SelfUpdater] RunnerPlatform: win-x64
[2022-03-07 19:19:51Z INFO Terminal] WRITE LINE: Downloading 2.288.1 runner
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Sending CTRL_C to process 2164.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Successfully send CTRL_C to process 2164.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Waiting for process exit or 7.5 seconds after CTRL_C signal fired.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Ignore Ctrl+C to current process.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Process exit successfully.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Process cancelled successfully through Ctrl+C/SIGINT.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Process Cancellation finished.
[2022-03-07 19:19:51Z INFO ProcessInvokerWrapper] Finished process 2164 with exit code -1073741510, and elapsed time 00:00:00.3848317.
[2022-03-07 19:19:51Z ERR  SelfUpdater] Fail to hash externals content: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.SelfUpdater.HashFiles(String fileFolder, CancellationToken token)
   at GitHub.Runner.Listener.SelfUpdater.CloneAndCalculateAssetsHash(String dotnetRuntimeCloneDirectory, String externalsCloneDirectory, CancellationToken token)
```

Another error in the log:
```
[2022-03-07 19:19:55Z INFO SelfUpdater] Download latest runner and unzip into runner root.
[2022-03-07 19:19:55Z INFO Terminal] WRITE LINE: Waiting for current job finish running.
[2022-03-07 19:19:55Z INFO Terminal] WRITE LINE: Runner update process finished.
[2022-03-07 19:19:55Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-03-07 19:19:55Z ERR  Terminal] WRITE ERROR: An error occurred: The handle is invalid.
[2022-03-07 19:19:55Z ERR  Listener] System.IO.IOException: The handle is invalid.
   at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode)
   at GitHub.Runner.Listener.SelfUpdater.UpdateRunnerUpdateStateAsync(String currentState)
   at GitHub.Runner.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveRunner, CancellationToken token)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
   at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by ruvceskistefan** [comment] 2022-03-08 08:38
Hi @TheOnlyWei,
Thanks for the reported issue. I have successfully reproduced the issue and I will now investigate in more detail. I will get back to you as soon as I have more information or solution to the problem.

**Comment by hognevevle** [comment] 2022-03-08 11:15
Any known workarounds?

**Comment by ruvceskistefan** [comment] 2022-03-08 12:39
The simplest workaround is to reinstall runner using the instructions for the new version (in this case 2.288.1). There is definitely a bug in `SelfUpdater`, we are working on solving it.

**Comment by TheOnlyWei** [comment] 2022-03-10 00:43
@ruvceskistefan I have a few organization-level runners that I do not have access to manage on Github, but I manage the runners on the VM where they are being run. As such I cannot reinstall the runners since that would require new access tokens. Is there a workaround for such cases without reinstalling?

**Comment by ChristopherHX** [comment] 2022-03-10 10:18
> Is there a workaround for such cases without reinstalling?

You could just keep the configuraton of the runner, but reinstall everything else I did this multiple times on linux/arm64. _Not related to a bug of actions/runner_

These powershell commands should do it on win-x64 for release 2.288.1. Use at your own risk.
```powershell
cd C:\azurestack-sdk-ci\runners\actions-runner-0
Remove-Item -Recurse bin -ErrorAction Ignore
Remove-Item -Recurse externals -ErrorAction Ignore
Remove-Item run.cmd -ErrorAction Ignore
Remove-Item config.cmd -ErrorAction Ignore
Remove-Item run-helper.* -ErrorAction Ignore
# Now instruction from the release page
# Download the latest runner package
Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.288.1/actions-runner-win-x64-2.288.1.zip -OutFile actions-runner-win-x64-2.288.1.zip
# Extract the installer
Add-Type -AssemblyName System.IO.Compression.FileSystem ;
[System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD\actions-runner-win-x64-2.288.1.zip", "$PWD")
```
You should just be able to run `run.cmd` after executing this, no need to run config.cmd again.

**Comment by ruvceskistefan** [comment] 2022-03-10 12:08
@TheOnlyWei I can't think of a workaround other than what @ChristopherHX wrote. The point of authentication is that a malicius user cannot do something like that what you want, so it is expected that you have to authenticate runner on GitHub.
Let me know the outcome if you try this workaround solution. We are working on solving the self-update bug, so I will let you know as soon as there is any news.

**Comment by ruvceskistefan** [comment] 2022-03-15 08:57
This is a known issue on the 2.277.1 version, so can you upgrade to the newer version using some of the workaround solutions?

**Comment by TheOnlyWei** [comment] 2022-03-15 19:25
@ruvceskistefan The workaround provided by @ChristopherHX  seems to be working, thanks for looking into this.

**Comment by ruvceskistefan** [comment] 2022-03-16 07:23
@TheOnlyWei Great, thanks for response. Since this is a problem that is already known and solved in next version of the runner, I will close this issue. Feel free reopen it if you have the same problem.

**Closed by ruvceskistefan** 2022-03-16 07:23 UTC
Labels: bug, Runner Auto-update :disappointed:, awaiting-customer-response
