### ISSUE TITLE
Different runner images used by containers in same job

### ISSUE THREAD

**Issue by MikeMcC399** [actions/runner#2812] opened 2023-08-30 12:02 UTC
This was submitted some months ago to https://github.com/orgs/community/discussions/52956, however there has been no feedback given there.

## Desired state

In the following snippet from a GitHub Actions workflow the GitHub-hosted runner image invoked by `containers` should always be the same version in the same job.

## Current state

During a recent rollout it has been observed that one container was invoked with the ubuntu-22.04 image [20230402.1](https://github.com/actions/runner-images/blob/releases/ubuntu22/20230402/images/linux/Ubuntu2204-Readme.md) and in the same job another container was invoked with the newer image [20230409.1](https://github.com/actions/runner-images/blob/releases/ubuntu22/20230409/images/linux/Ubuntu2204-Readme.md).

Testing with Cypress Cloud and Google Chrome failed because there were differences in the major version of Chrome in the two images.

When containers are started in the same job they should use a consistent image version throughout. An on-going rollout should not affect this. Either all containers should be started with the old image or with the new image, not a mixture of the two.

```yml
    test:
        runs-on: ubuntu-22.04
        strategy:
        matrix:
            containers: [1, 2]
```

It is related to:

- https://github.com/cypress-io/cypress/issues/25040
- https://github.com/cypress-io/github-action/issues/602
- https://github.com/cypress-io/github-action/issues/865

**Comment by benwells** [comment] 2023-08-31 21:06
Hey!  The runner team discussed this today and feel the @actions/runner-images-team team/repo may be the best home for this issue. I'm going to transfer to https://www.github.com/actions/runner-images

cc: @samvantran

**Comment by mikhailkoliada** [comment] 2023-09-01 09:47
@benwells actually looks like not, because the runner-images team is responsible for the image delivery itself, we are not involved in the workflow logic implementation changes

**Comment by benwells** [comment] 2023-09-06 16:25
We discussed this issue across multiple teams and wanted to provide a quick update here.  This is something that has come up before and involves a rather risky, fundamental change to underlying systems to accomplish any sort of improvement here.  We may consider this in the future but unfortunately there's no plans to fund this in the short or intermediate term. 

To give a bit more detail:

- From Actions backend and actions/runner side - matrixes produce multiple jobs and these services just request N separate VMs handle these N jobs. Actions backend, as currently designed, doesn't really consider any connections between these jobs when queueing them.
- Our provisioning service does have VMs with different image versions. This is by design because the deployment of new image takes multiple days.

Improvements involve, potentially:

- ...some improvements on Actions backend to queue matrixes jobs in "groups" and some changes provisioning-side to make sure that all jobs from group are assigned to VMs running the same image. 
- ...speed up deployment of VMs to update all VMs in parallel to make sure that we don't have VMs with different image versions at the same time.

I'm going to close this issue at this time, but encourage adding a request to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) to raise the awareness of product here for future prioritization.

**Closed by benwells** 2023-09-06 16:25 UTC
Labels: bug

**Comment by MikeMcC399** [comment] 2023-09-06 16:32
@benwells 

Thank you for considering this request.

> I'm going to close this issue at this time, but encourage adding a request to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) to raise the awareness of product here for future prioritization.

As I wrote in the original post, it was already submitted to https://github.com/orgs/community/discussions/52956 (on April 16, 2023) and so far has not received any feedback from product management. I will add a link in that posting to your assessment above.
