### ISSUE TITLE
actions should fail if an invalid Runner name is specified

### ISSUE THREAD

**Issue by Yaminyam** [actions/runner#2322] opened 2022-12-16 22:47 UTC
**Describe the bug**
If an invalid runner name is given as the runs-on argument, actions will stay loading forever.
I think actions should fail if you specify an invalid runner name.

ex)
https://github.com/Yaminyam/backend.ai/actions/runs/3716784740/jobs/6303496952

**To Reproduce**
Invalid runner name given to the runs-on argument.

**Expected behavior**
actions fail the action.

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
<img width="684" alt="image" src="https://user-images.githubusercontent.com/31057849/208201215-834eeecf-4962-431b-a433-30977200f05c.png">

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment] 2022-12-19 08:39
Hey @Yaminyam,

This is actually by design. You can schedule your workflows based on labels that you apply to your runners. In the time of writing a workflow file, you don't have to have runner registered in order to submit that file.
But aside from that, stopping workflow creation will not prevent runners going offline as well.
Let's say you have created a workflow that runs on some event. You have a runner registered, and it picks up a job no problem. After a while, runner exits for some reason, or is unable to talk to the service. Then, the workflow will still hang, because no runners are available to receive the job assigned to them.

When the runner comes online again, it will pick up the job that you have assigned to it.
I hope this clarifies why is it working this way :relaxed: 

If you feel like this could be a good feature, please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. This feature is related to the platform in general, so posting your feedback will help us route this to the correct team.

**Closed by nikola-jokic** 2022-12-19 08:39 UTC
Labels: bug
