### ISSUE TITLE
Support for PowerPC and Z series CPU architectures

### ISSUE THREAD

**Issue by kryptonite303** [actions/runner#296] opened 2020-01-21 17:27 UTC
**Describe the enhancement**
Support PowerPC and Z series CPU architectures for the runner

**Additional information**
According to the Linux System Prerequisites doc: [https://github.com/actions/runner/blob/master/docs/start/envlinux.md](url)
And this Pull Request: #184 
the runner supports x64 and ARM CPU architectures. 
I have jobs that run on several different architectures, including PowerPC and Z series.

**Comment by juliobbv** [comment] 2020-01-29 18:16
For reference for future readers of this issue: the actions runner uses .NET Core as a dependency. That means we can support the OS/CPU architectures that .NET Core itself currently supports.

https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md

Porting the runner to Go or Typescript will allow us to support a wider variety of OS/CPU arch combos.

**Comment by bryanmacfarlane** [comment] 2020-01-30 13:52
Dupe of #243 - please add a comment to that issue if you have specific requests.

**Closed by bryanmacfarlane** 2020-01-30 13:52 UTC
Labels: enhancement
