### ISSUE TITLE
why github runner takes too much time to establish?

### ISSUE THREAD

**Issue by sriedjx** [actions/runner#1249] opened 2021-08-05 16:50 UTC
**I'm creating cicd flow with multiple jobs(5)(sequential) in single yml file on `ubuntu-latest` runner. but it takes at least 3-4min to establish per job.**
Note: Each job dependent on previous job(`needs` functionality)
If i run single jobs in single yml file, then it works normally. but when i use multiple jobs i'm facing the problem.
Kindly let me know, do i need to use any other runner or is there any way to run normally.

**Comment by TingluoHuang** [comment] 2021-08-05 17:33
https://www.githubstatus.com/incidents/7p1nnvkgh96y

**Comment by sriedjx** [comment] 2021-08-05 18:49
I'm still facing same problem

**Comment by sriedjx** [comment] 2021-08-05 19:01
still facing almost same problem, first job is taking almost 5min to establish runner

**Comment by TingluoHuang** [comment] 2021-08-05 19:06
do you mind sharing a link to your run?

**Comment by sriedjx** [comment] 2021-08-05 19:42
Thanks, issue got fixed

**Comment by sriedjx** [comment] 2021-08-06 15:04
same issue , but this time each Job taking 5min to establish

**Comment by nikola-jokic** [comment] 2022-02-14 08:26
Hi everyone, since it is confirmed that the issue has been fixed, and there has been a long time without interaction, I will now close this issue.

**Closed by nikola-jokic** 2022-02-14 08:26 UTC
Labels: bug, awaiting-customer-response
