### ISSUE TITLE
Docker actions create files and directories with root:root ownership, breaking later steps

### ISSUE THREAD

**Issue by travisdowns** [actions/runner#1282] opened 2021-08-21 04:37 UTC
**Describe the bug**
Files created by a docker-based action are owned by `root:root` which means they can't be modified by subsequent actions or steps running as the default `runner` user.

**To Reproduce**
I made a [repro in a repo](https://github.com/travisdowns/gha-docker-issue). 

The docker action writes a file hello, and a step outside the action writes hello-outside. You can see their permissions in the actions output:

~~~
 id outside the container: uid=1001(runner) gid=121(docker) groups=121(docker),4(adm),101(systemd-journal)
total 0
-rw-r--r-- 1 root   root   0 Aug 21 04:31 hello
-rw-r--r-- 1 runner docker 0 Aug 21 04:31 hello-outside
~~~

**Expected behavior**
The ownership of files created inside and outside of a docker container action should be the same, or at least the permissions should be set appropriately so the files aren't "off limits" to the runner user.

## Runner Version and Platform
Current Linux hosted github runner.

This is similar to #434 but that issue talks about self-hosted runners on two consecutive runs. This issue happens entirely within one run.

**Comment by j3parker** [comment] 2021-08-24 13:07
See #434

**Comment by travisdowns** [comment] 2021-08-24 16:42
@j3parker right, I linked #434 at the bottom, but I feel the discussion there is mostly specific to the self-hosted runner case where a given action conflicts with its next run on the same machine. There are workaround there (e.g., removing the files) that aren't appropriate in the general case.

**Comment by yoannchaudet** [comment] 2022-02-08 06:13
👋 Is there a good workaround for that already?

We are having the exact same ask in https://github.com/actions/jekyll-build-pages/issues/18.

**Comment by nikola-jokic** [comment] 2022-03-10 11:52
Hey @travisdowns,

I have reproduced your issue. If your Dockerfile does not have specified `USER`, it will run as root. That file owner will be later correlated with the UID of the system, which causes the file to be created as a `root`. If you have your account with UID for example 1000 on your host machine, and you create a user in your `Dockerfile` with the same UID, the owner of the file will be the same as the one mapped from your system.

In other words, UID inside the Docker will correlate with file creation with the UID of users on the host machine.

In my case, I have user `nikola` with UID 1000. If I tweak your `Dockerfile` a bit, with:
```
FROM ubuntu:20.04

COPY entrypoint.sh /entrypoint.sh

RUN useradd test

USER test

ENTRYPOINT ["/entrypoint.sh"]
```
Then, my action would take place as a test user, assigned with 1000 UID, which creates a file that is later owned by my host user with UID 1000 (`nikola`). If you correlate the user running the runner, and Dockerfile action creating that file, the correct permissions would be set and I imagine that you would not have any problems with the file permissions.

**Comment by nikola-jokic** [comment] 2022-03-10 12:18
I will close this issue now since everything was related to issue #434. Feel free to comment further here, but I feel that everything is contained inside the issue mentioned, and we are aware of this. And since this issue is also linked, I don't think it should be a problem to find it

**Closed by nikola-jokic** 2022-03-10 12:18 UTC
Labels: bug
