### ISSUE TITLE
Automatic upgrades fail to re-connect with GitHub on Mac

### ISSUE THREAD

**Issue by nick-invision** [actions/runner#935] opened 2021-01-22 20:13 UTC
## Issue
We have multiple organization-level self-hosted Mac runners that all experience the same issue every few weeks.  After an auto-upgrade, the new runner restarts successfully but appears as `offline` from the https://github.com/organizations/NAME/settings/actions page and no workflows can be processed until the new runner is restarted via `./svc.sh stop && ./svc.sh start`.

This happened today with the upgrade from v2.276.0->v2.276.1, and previously on 12/18.  Unsure which version the 12/18 upgrade was from (the logs are gone).

## To Reproduce
1. Download an older runner
2. Wait for the auto upgrade
3. Note that the upgrade succeeds and the runner restarts (as evidenced by the `./svc.sh status` output), but the organization Actions settings page shows the runner as offline and does not accept any new jobs

## Expected behavior
Once the upgrade complete and the runner restarts, it should be connected back to GitHub to prevent any downtime.

## Runner Version and Platform
* v2.276.1 (upgraded from 2.276.0) (all hosts are macOS Catalina 10.15.6, and all hosts experience this)

## What's not working?
Self-hosted runner does not reconnect to GitHub after upgrade.

## Runner and Worker's Diagnostic Logs
Runner (before and after) and SelfUpdate logs attached
[Update Logs.zip](https://github.com/actions/runner/files/5858325/Update.Logs.zip)

**Comment by TingluoHuang** [comment] 2021-01-25 17:21
in the `AFTER_Runner_xxxx` log

Looks like the runner machine lost internet access in the beginning.
```
[2021-01-22 19:01:35Z ERR  Terminal] WRITE ERROR: 2021-01-22 19:01:35Z: Runner connect error: nodename nor servname provided, or not known. Retrying until reconnected.
[2021-01-22 19:01:35Z INFO MessageListener] Sleeping for 30 seconds before retrying.
```

eventually recovered and start running jobs:
```
[2021-01-22 19:02:05Z INFO MessageListener] Session created.
[2021-01-22 19:02:05Z INFO Terminal] WRITE LINE: 2021-01-22 19:02:05Z: Runner reconnected.
[2021-01-22 19:02:05Z INFO Terminal] WRITE LINE: 2021-01-22 19:02:05Z: Listening for Jobs
```

**Comment by nick-invision** [comment] 2021-01-26 00:59
To fix the issue, I just trigger reboots of the hosts. It's possible that's what you are seeing in the logs.

These runners have been up nonstop for months, with the only two unexpected interruptions occurring right after the runners were upgraded.  If it were on a single host or runner I could accept that it's a connectivity issue, but the fact that it happened to 100% of our hosts (all running in MacStadium) makes me suspect something related to the runner upgrade process.

**Comment by TingluoHuang** [comment] 2021-01-26 01:28
@nick-invision how did you reboot the host? the runner logs are from the same file which means the runner process never exits.
Every time you start the runner process it will create a new log file.

**Comment by nick-invision** [comment] 2021-01-26 01:48
@TingluoHuang I reboot the host via SSH, which means the `AFTER_Runner_*` logs would be from post-reboot.  Once rebooted, runners reconnect without issue and have been running fine ever since.

**Comment by TingluoHuang** [comment] 2021-01-26 02:41
@nick-invision the network error I found is from the `AFTER_Runner_*` log you provide, which means even after the reboot, the runner still has a network issue for about 60 seconds.

the old version runner exit and start its finial upgrade process at (from the `BEFORE_Runner_*` log):
```
[2021-01-22 18:39:15Z INFO Terminal] WRITE LINE: Runner will exit shortly for update, should back online within 10 seconds.
```

the newer version runner kicks in at (from the `AFTER_Runner_* log`):
```
[2021-01-22 19:01:34Z INFO Listener] Version: 2.276.1
```

Do you happen to have any runner log to indicate what was the runner doing during that time window?
`18:39:15` -> `19:01:34`

**Comment by nick-invision** [comment] 2021-01-26 02:52
No, the before/after runner logs that I attached were the logs available from that date.

It doesn't seem like we are getting anywhere with this.  If/when it happens again, before I reboot is there anything I can provide from the runner or host to better track down why this is happening to all of our runners?

**Comment by TingluoHuang** [comment] 2021-01-26 03:23
@nick-invision maybe `~/Library/Logs/actions.runner.*`, it should contain the service log.

**Comment by nick-invision** [comment] 2021-01-26 04:19
This is interesting, the first runner had nothing in `stderr.log` but lots of this error in `stdout.log`:

```
2021-01-22 18:09:44Z: Running job: REDACTED
2021-01-22 18:14:13Z: Job REDACTED completed with result: Succeeded
Runner update in progress, do not shutdown runner.
Downloading 2.276.1 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
Runner listener exited with error code 3
Runner listener exit because of updating, re-launch runner in 5 seconds.

... (repeated hundreds of times until reboot)

Starting Runner listener with startup type: service
Started listener process
Runner listener exited with error code null
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
.path=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
Starting Runner listener with startup type: service
Started listener process
Started running service
2021-01-22 19:01:35Z: Runner connect error: nodename nor servname provided, or not known. Retrying until reconnected.

√ Connected to GitHub

2021-01-22 19:02:05Z: Runner reconnected.
2021-01-22 19:02:05Z: Listening for Jobs
2021-01-22 19:02:09Z: Running job: REDACTED
```

It appears to have done this first after upgrading to 2.273.0 (2020-08-24), then again 2.273.6 (2020-11-03), 2.274.1 (2020-11-09), 2.275.0 (2020-12-17).  See attached,`abbreviated-redacted-stdout.log` just has repetitious/seemingly uninteresting lines truncated with `...`, `redacted-stdout.log` is the whole log.  Job names are the only thing that have been changed/redacted.
[redacted-stdout-logs.zip](https://github.com/actions/runner/files/5871147/redacted-stdout-logs.zip)

**Comment by TingluoHuang** [comment] 2021-01-26 04:41
@nick-invision base on 
```
Starting Runner listener with startup type: service
Started listener process
Runner listener exited with error code null
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
Runner listener exited with error code null
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
.path=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
Starting Runner listener with startup type: service
```

Looks like the service tries to launch the runner process, but it failed for some reason, so it stuck in a loop.
Unfortunately, we didn't log anything when the process fails to starts, we should fix that.

**Comment by TingluoHuang** [comment] 2021-02-01 04:08
Added PR to trace process error.

**Comment by kevindumanoir** [comment] 2021-02-02 13:25
@TingluoHuang It is the same error as described in https://github.com/actions/runner/issues/743

> This is a tricky one. We do have the same issue at Fabernovel and here's what we discovered :
> 
> - The service watchdog is run from `runsvc.sh`. It is a node.js script invoked using a specific version of Node.JS, located at `<YOUR_ACTIONS_RUNNER_PATH>/externals/node12/bin/node`. There's one important thing to remember : **externals is a symbolic link**
> - The service watchdog `RunnerService.js` fails to spawn subprocess because Apple System Policy, `syspolicyd`, considers `<YOUR_ACTIONS_RUNNER_PATH>/externals.X.A/node12/bin/node` as a malware. 🤯 
> - `node` is considered as a malware, because the binary file, loaded in RAM, cannot be found on the hard drive.
> - `node` cannot be found because the binary **doesn't exist anymore**: We do have invoked `node` from `externals` folder, but after the update the symbolic link has been updated : it now points to the new version of actions runner, i.e. `externals.X.X`. The thing is, when the service started the watchdog, it used `node` executable from `externals.X.A`. And yes, it seems this folder does not exists anymore.
> - This folder does not exist anymore because after every update, actions runner only keeps binaries from version `n - 1`. When updating to version `n+1`, folders `externals-(n-1)` and `bin-(n-1)` are deleted.
> 
> **Conclusion** : this issue occurs when, after launching service in runner actions version N, the runner auto-updates a second time.
> 
> So, how can we deal with it ? Obviously, Apple cannot rely on a symbolic path to check malware behavior of a program. Here is some non-exhaustive ideas:
> - Force node watchdog to exit when an update succeeded. It might be possible to let it exit with a specific status code, which will be interpreted as a watchdog reboot request from `runsvc.sh`
> - Keep `externals.X.X` folder for the currently used node process (not really a good idea imo)
> - Explain how to disable the syspolicyd (meh, not good either)
> - Rely on launchctl to keep Runner.Listener process alive (.i.e remove node watchdog), [by eventually rely on `SuccessfulExit`](https://superuser.com/a/127103/1032389)
> - Let Runner exit with code 0 or 1 when an update finished successfully, so we can rely on implemented logic in watchdog. Or let error code 3 stop the watchdog

**Comment by kevindumanoir** [comment] 2021-02-23 10:35
Any updates about this issue ?

**Comment by thboop** [comment] 2021-09-09 13:27
This should be resolved now, @kevindumanoir are you still seeing this issue? If so, we can reopen it

Looks to be a dupe of https://github.com/actions/runner/issues/743

**Closed by thboop** 2021-09-09 13:27 UTC
Labels: bug, needs-investigation

**Comment by kevindumanoir** [comment] 2021-09-22 17:25
@thboop  Sorry for the very long delay. Yes, it seems the issue is resolved on our runners, with previous external folders downloaded during the upgrade !
