### ISSUE TITLE
nesting group-endgroup workflow commands

### ISSUE THREAD

**Issue by andreineculau** [actions/runner#802] opened 2020-11-12 12:21 UTC
**Describe the bug**
Disclaimer: this might be a bug on the web frontend of Github Actions, but I have no idea where to report such bugs.

I am trying to use `::group::` and `::endgroup::` but the UI is confusing with nested groups. See details below.

**To Reproduce**

```
echo "::group::Wrapper"

echo "Wrapper begin"

echo "::group::Foo"
echo "Foo"
echo "::endgroup"

echo "Something"

echo "::group::Bar"
echo "Bar"
echo "::endgroup"

echo "Wrapper end"

echo "::endgroup::"
```

should be a reproducible snippet.

My actual build is https://github.com/rokmoln/support-firecloud/runs/1390151835?check_suite_focus=true#step:10:20

and the raw logs show

```
2020-11-12T11:49:27.8802160Z 11:49:27 [DO  ] Building...
2020-11-12T11:49:27.8805635Z ##[group]work-support-firecloud-support-firecloud-building
2020-11-12T11:49:27.8807942Z               > work-support-firecloud-support-firecloud-building
2020-11-12T11:49:27.8808756Z 
2020-11-12T11:49:27.8816470Z make[1]: Entering directory '/home/runner/work/support-firecloud/support-firecloud'
2020-11-12T11:49:28.1481071Z 
2020-11-12T11:49:28.1493809Z 11:49:28 [DO  ] Generating BUILD...
2020-11-12T11:49:28.1496163Z ##[group]work-support-firecloud-support-firecloud-generating-build
2020-11-12T11:49:28.1498510Z               > work-support-firecloud-support-firecloud-generating-build
2020-11-12T11:49:28.1499723Z 
2020-11-12T11:49:28.2640783Z 
2020-11-12T11:49:28.2643097Z               < work-support-firecloud-support-firecloud-generating-build
2020-11-12T11:49:28.2644640Z ##[endgroup]
2020-11-12T11:49:28.2656525Z 11:49:28 [DONE] Generating BUILD...
2020-11-12T11:49:28.2657112Z                 in 0 seconds
2020-11-12T11:49:28.2657435Z 
2020-11-12T11:49:28.4093908Z 
2020-11-12T11:49:28.4104975Z 11:49:28 [DO  ] Generating VERSION...
2020-11-12T11:49:28.4107301Z ##[group]work-support-firecloud-support-firecloud-generating-version
2020-11-12T11:49:28.4109658Z               > work-support-firecloud-support-firecloud-generating-version
2020-11-12T11:49:28.4111062Z 
2020-11-12T11:49:28.5241563Z 
2020-11-12T11:49:28.5243730Z               < work-support-firecloud-support-firecloud-generating-version
2020-11-12T11:49:28.5245349Z ##[endgroup]
2020-11-12T11:49:28.5257243Z 11:49:28 [DONE] Generating VERSION...
2020-11-12T11:49:28.5257839Z                 in 0 seconds
2020-11-12T11:49:28.5258388Z 
2020-11-12T11:49:28.5259812Z make[1]: Leaving directory '/home/runner/work/support-firecloud/support-firecloud'
2020-11-12T11:49:28.6347962Z 
2020-11-12T11:49:28.6349969Z               < work-support-firecloud-support-firecloud-building
2020-11-12T11:49:28.6351202Z ##[endgroup]
2020-11-12T11:49:28.6362789Z 11:49:28 [DONE] Building...
2020-11-12T11:49:28.6363358Z                 in 1 seconds
```

and it looks like the group/endgroup markers are set correctly.

**Expected behavior**
I expect groupings to be properly nested.

## Runner Version and Platform
Version of your runner? 2.274.1

OS of the machine running the runner? Linux

## What's not working?
It looks like the `##[group]work-support-firecloud-support-firecloud-generating-build` (first nested group) acts as a `##[endgroup]` for `##[group]work-support-firecloud-support-firecloud-building` (the wrapper group).

Similarly the content after `2020-11-12T11:49:28.5257243Z 11:49:28 [DONE] Generating VERSION...` and the following `#endgroup#` (the wrapper group) is not folded.

![Screenshot 2020-11-12 at 13 18 33](https://user-images.githubusercontent.com/708161/98939339-945c7800-24e9-11eb-8f75-e7be4286d319.png)

## Job Log Output
See above.

## Runner and Worker's Diagnostic Logs
N/A

**Comment by Cyberbeni** [comment] 2020-11-25 16:44
I think this is a feature request, not a bug.

I also think it would be useful to be able to create groups inside of groups and also run 2 groups parallelly (my use case is a typescript action, where the used commands also produce "uncontrolled" output inside @actions/exec), getting the output from them under the correct group. So something like this:

```
group 1: {
    group 1.1: {
        messages...
    }
    group 1.2: {
        messages...
    }
}
group 2: {
    group 2.1: {
        messages...
    }
    group 2.2: {
        messages...
    }
}
```
Where group 1 is started before group 2 but order of group 1.x and group 2.x and the messages inside them don't matter, they would all show in the appropriate place on the online log viewer.

**Comment by nikola-jokic** [comment] 2022-07-15 10:31
Hi @andreineculau,

Could you please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback)? As you said, the runner is correctly executing commands, so the feedback can ensure that maintainers of the board route the feedback to the correct team.
The issue does make sense to me, but since it is not related to the runner, I will close it now.

**Closed by nikola-jokic** 2022-07-15 10:31 UTC
Labels: bug

**Comment by oli-obk** [comment] 2022-12-07 10:06
The feature is tracked at https://github.com/actions/toolkit/issues/1001
