### ISSUE TITLE
Required status check job is skipped when one of the dependent job fails

### ISSUE THREAD

**Issue by jaymalasinha** [actions/runner#2566] opened 2023-04-25 19:54 UTC
**Describe the bug**
When one of the required dependent jobs fail in the workflow, the job requiring it is skipped.
- job "results" needs jobs `needs: [build-one, build-two, test, test-more]` 
- when job "test" fails, "results" is skipped
- as "results" is a required status check for merge, it allows merging with failed dependent job

**To Reproduce**
Create the following workflow file:

```---
name: build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-requisite:
    runs-on: ubuntu-latest
    steps:
      - name: Get Req
        id: get-req
        run: echo "get req"

  build-one:
    name: build one
    runs-on: ubuntu-latest
    needs: pre-requisite
    steps:
      - run: echo "build-one"

  build-two:
    name: build two
    runs-on: ubuntu-latest
    needs: pre-requisite
    steps:
      - run: echo "build-two"

  test:
    name: Test initial
    needs:
      - pre-requisite
      - build-two
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing builds"
          exit 1

  test-more:
    name: Test more
    needs:
      - pre-requisite
      - build-two
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test more"

  results:
    runs-on: ubuntu-latest
    needs:
      - build-one
      - build-two
      - test
      - test-more
    steps:
      - run: echo "Workflows have succeeded!"
 ```
The job "results" is a required status check for merge.   When the job "test" fails the job "results" is skipped

**Expected behavior**
The job "results" needs "test" to succeed, so I would expect it to not be skipped, as skipped status check allows merge. 
Expect "results" to be skipped if any of the dependent jobs are skipped, like if "test" is skipped, but expect it to fail if any of the dependent jobs fail.

## Runner Version and Platform
Current runner version: '2.303.0'

Ubuntu
 22.0[4](https://github.com/jaymalasinha/myghactions/actions/runs/4801356760/jobs/8543448699#step:1:4).2
 LTS

Runner Image Provisioner
  2.0.139.1

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu

## What's not working?
![image](https://user-images.githubusercontent.com/14876649/234387479-c10d7b4d-f109-4099-a688-aa6a83252685.png)

**Comment by jaymalasinha** [comment] 2023-04-26 16:42
> echo "Workflows have succeeded!"

Thank you @ChristopherHX for the workaround.  With the workaround, If the _pre-requisite_ job is skipped _results_ get no check status.

**Comment by jaymalasinha** [comment] 2023-04-26 17:42
updated the workaround to force fail for both failure and cancelled conditions

```
results:
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    needs: [build-one, build-two, test, test-more]
    steps:
      - run: |
          echo "Some workflows have failed!"
          exit 1
```
![image](https://user-images.githubusercontent.com/14876649/234658465-eed8d7f7-ca01-4f67-84f9-9e0a22782248.png)

That seems to work by skipping "results" job when "pre-requisite" job is skipped

**Comment by ruvceskistefan** [comment] 2023-04-27 11:39
Hey @jaymalasinha,
I see you have figured out how to fix your workflow for your case, I'll close this issue. If you think we need to reopen it just let me know.

**Closed by ruvceskistefan** 2023-04-27 11:39 UTC
Labels: bug

**Comment by marcispauls** [comment] 2024-04-17 06:52
same issue there, seems some breaking changes happened

**Comment by saiichihashimoto** [comment] 2024-05-09 21:23
The workaround didn't work for me. While it failed when the dependent job failed, it also skipped when the dependent job succeeded, which is a massive regression.

**Comment by zorzella-tome** [comment] 2024-06-10 16:37
The workaround is an ugly hack. I would love to have a proper way of doing this.

**Comment by deanmalmgren** [comment] 2025-03-06 11:55
I just ran into the same unexpected behavior and made an unexpected broken contribution to our dev branch that brought development to a halt. If an upstream dependency fails, maybe using a `cancelled` status for the downstream jobs would be more appropriate so that they don't pass status checks?

**Comment by gstokkink** [comment] 2025-03-29 09:04
@ruvceskistefan can you please consider re-opening this issue in the light of the comments above?

**Comment by FelixGV** [comment] 2025-06-20 20:40
Looks like this bug is a feature 😅 ...

> Note
> 
> A job that is skipped will report its status as "Success". It will not prevent a pull request from merging, even if it is a required check.

Source: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution

**Comment by FelixGV** [comment] 2025-07-09 17:40
I worked on coping with this quirk a few weeks ago for the [Venice](http://github.com/linkedin/venice) project's GitHub actions, so here is a dump of my learnings. It is basically a re-hash of the above posts, so nothing new really, but maybe the summary will help someone else in the future.

So, the situation is that if you go to your repo's Settings, then Branches, then Edit the rules for a given branch, and then check the `Require status checks to pass before merging` box, when you add tasks to the list just below that, the behavior may not be intuitive. It work the following way:

1. If the task succeeds, then merging can proceed.
2. If the task fails, then merging is blocked.
3. If the task is skipped, however, then merging can still proceed. This is the part people may find unintuitive, though it appears to be intentional, as it is spelled out explicitly in the GH docs (see my other post just above).

The issue with the skipping behavior (point 3) is that if the task you want to use as the required status check is dependent on the completion of other upstream tasks, and those upstream tasks fail, then the downstream task will get skipped, and therefore merging will be permitted. In other words, let's say you have tasks `A`, `B` and `C` which you all want to succeed, and you define a task `D` with `needs: [A, B, C]`, then using `D` as your required status check will NOT prevent merging if any of `A`, `B` or `C` fail, which is almost certainly not what you wanted.

There are at least two solutions to this (and probably more still, so feel free to comment if you see glaring omissions...).

**Always run the task and verify upstream statuses**

One way is to configure the downstream task to NOT get skipped when the upstreams fail. Then in the action's body, you need to check the status of each upstream job explicitly. This is what we used to do in some of our workflows before (see [here](https://github.com/linkedin/venice/blob/583b2629ab99e15ae0b1730bce35377c630688f7/.github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml#L145)). The downside is needing to maintain those checks manually, so that whenever you add a new upstream task in the `needs` array, you also add the corresponding check in the action's body. Done manually, this could be error-prone, though it could be scripted.

**Lean into skipping**

Another way is to make the downstream task run only if the upstream tasks fail or get cancelled, and then have the downstream task simply fail, whenever it does run. When upstream tasks succeed, then the downstream would get skipped, and that is treated as a success. This is what we ended up doing for now (see [here](https://github.com/linkedin/venice/blob/b9885d907f5cdff5ea38e81aea95d18c443cac33/.github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml#L147)). This is simple to maintain in the sense that there is no need for an explicit check for each of the upstream tasks, but it may look a bit weird since you would always see some tasks getting skipped on successful CI runs. The confusion can be alleviated via naming, for example, we renamed those tasks from `[...]CompletionCheck` to `[...]FailureAlert`. If the failure alert gets skipped, that's a good thing.

I hope this helps!

**Comment by mochallouf** [comment] 2025-11-14 15:33
Any chance to reopen this issue?
