### ISSUE TITLE
Output is buffered and lost if the program aborts

### ISSUE THREAD

**Issue by Geod24** [actions/runner#1235] opened 2021-08-03 08:32 UTC
**Describe the bug**

When a program exits abruptly (`assert`, `abort`...), some buffered output seems to be lost.

**To Reproduce**

Consider the following C code:
```C
#include <stdlib.h>
#include <stdio.h>

int main ()
{
    printf("Please flush after yourself\n");
    abort();
}
```

Running it locally has the expected behavior, both with a TTY and a redirection:
```shell
% gcc test.c && ./a.out
Please flush after yourself
[1]    25804 abort      ./a.out
% gcc test.c && ./a.out > somefile.txt
[1]    25837 abort      ./a.out > somefile.txt
% cat somefile.txt
Please flush after yourself
```

The output is visible, since the `printf` calls contains a `\n`, stdout is flushed.
However in Github CI, no output is visible:
<img width="1314" alt="Screen Shot 2021-08-03 at 17 28 59" src="https://user-images.githubusercontent.com/2180215/127983862-de6a679a-4cf7-4845-a15c-fb198e96ada9.png">

[The run in question](https://github.com/Geod24/github-actions-test/runs/3228703818)

**Expected behavior**

`stdout` should have been flushed when `printf` saw a `\n`.

## Runner Version and Platform
Version of your runner: 2.279.0
OS of the machine running the runner? ubuntu-latest (20.04)

**Comment by nikola-jokic** [comment] 2022-03-14 10:44
Hi @Geod24,

I was able to reproduce this issue. Thanks for filing this! It turns out that the `System.Diagnostics.Process` is not reading the stdout in your particular case. I tried it on Debian-based distribution, which is similar to Ubuntu. We are using it to invoke your command `gcc test.c && ./a.out`, and the Process would not read the stdout in your particular example.

Sorry I could not help you with it. I will close this issue now since we cannot change it inside the runner.

**Closed by nikola-jokic** 2022-03-14 10:44 UTC
Labels: bug

**Comment by Geod24** [comment] 2022-03-14 11:36
So... `res-wontfix` ?

Wouldn't there be a way to drain or set a buffer size for `stdout` (and stderr) here ? I am not familiar with how C# does this on Linux, but I expect it's a combination of `pipe` / `dup2` / `fork`.

If the problem is that `stdout` is not read before the process crashes, and cannot be read afterwards, as I understand from your message, perhaps the fds are not being polled frequently enough ? It would seem weird that output that made it to a pipe just vanished. In this example it's a single line, but the bug was encountered on an `assert` handler that prints a stack trace with many newlines, so it not being flushed was very far down my list of hypothesis.

**Comment by sswam** [comment] 2024-07-23 16:24
In C you can use `setvbuf(stdout, NULL, _IONBF, 0);` to mark stdout to be unbuffered,
or `setvbuf(stream, NULL, _IOLBF, 0);` to mark stdout to be line buffered.

Check the manpage for setvbuf(3).
