### ISSUE TITLE
Windows runner loses identity after self-update

### ISSUE THREAD

**Issue by MatisseHack** [actions/runner#1123] opened 2021-05-27 21:36 UTC
**Describe the bug**

If the runner starts using impersonation (e.g. a scheduled task run under a logged out user) and the runner self-updates, the resulting process does not keep the full user profile loaded. Workflows using certain Windows cryptographic APIs will fail until the runner process is restarted.

**To Reproduce**

1. Create a local user account (e.g. runneruser)
2. Make sure that user is not logged in (so that their profile is not already loaded)
3. Install a version of the Actions Runner that is at least one version older than the latest
4. Configure the runner with GitHub.com using the `config.cmd` file
5. Launch the runner with impersonation (for example using a Scheduled Task, passing in the user’s credentials)
6. Run a workflow, which will cause the runner to self-update before execution
7. Any workflows run after this point will fail if they need access to certain Windows cryptographic APIs
8. Stop the currently executing runner process and launch it again using a scheduled task
9. Run the same workflow again. Note that the workflow now runs fine.

**Expected behavior**

Workflows should not fail or exhibit different behavior after the runner updates

## Runner Version and Platform

Windows runner 2.277.1 (updating to 2.278.0)

## What's not working?

The update completes successfully, but workflows using certain Windows cryptographic APIs will fail when run by the new runner process. For example, this line of PowerShell:

```powershell
New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("key.pfx", "")
```

Will fail with:

```
Exception calling ".ctor" with "2" argument(s): "The specified network password is not correct."
```

[This example workflow](https://github.com/MatisseHack/pfx/blob/main/.github/workflows/pfx.yml) is a good demonstration of the issue.

**Comment by ericsciple** [comment] 2021-05-28 16:35
are you using windows scheduler because you need an interactive logged in session (e.g. for ui testing)?

i wonder if we should add first class support to the runner config to enable autologon/autostartup

**Comment by MatisseHack** [comment] 2021-05-28 17:29
For the moment we don't have a hard requirement to have an interactive session so we could get around this issue by configuring the runner as a service. It is an odd edge case though that took us a while to figure out.

**Comment by fhammerl** [comment] 2021-06-03 15:05
Windows version: 20H2 (Windows 10 Desktop)

I ran `run.cmd` as a Scheduled Task (config below), but I was unable to reproduce the issue. There might be more going on here that we don't fully understand.

![image](https://user-images.githubusercontent.com/31069338/120667489-d51fdc80-c48d-11eb-9118-6ae070bab66d.png)

**Comment by ericsciple** [comment] 2021-06-03 15:26
👋 hey @MatisseHack i sync'd w/ @fhammerl and we couldn't figure out how to repro the issue. We even ran `whoami` during the build to confirm the downstream process was running as the expected identity. Even after update, the process ran as the service account, and not the logged on user.

However it sounds like the customer has a path forward. The current solution for the scenario is the first class support to create a Windows Service which is built-in to the runner configuration experience.

Note, it can also be scripted if the customer is using automation to configure runners, you would need flags `--runasservice`, `--windowslogonaccount`, `--windowslogonpassword`, `--unattended`. We also allow any arg to be passed securely via env var (`ACTIONS_RUNNER_INPUT_<THE_ARG_NAME>`)

The findings on this issue/PR are awesome. I believe @fhammerl is going to continue digging in to consolidate the multiple restart-code-paths (basically continue with the review/testing of your PR).

**Comment by MatisseHack** [comment] 2021-06-03 20:06
What you are doing looks right from first glance! The main difference I see is that I was testing on a Windows Server 2019 Datacenter VM in Azure. I wouldn't think the behavior would be different, but it's possible. Other things to check:

* You are sure you are installing an older version of the runner and it is doing an update before running the workflow? Sounds like you checked this, but I've made this mistake more times than I'd care to admit 😂 
* Make sure the target user is logged out. It sounds like you are testing on a local machine, but if you are using RDP to log in as the service account on a remote machine, make sure you actually log out, not just close the RDP connection.
* Is this a fresh user account that has not run any cryptographic operations before? I don't think this is the issue because I was able to reproduce the issue even with a user that had loaded a PFX file many times, but might be good to check just to reduce the number of variables

Also note that it is expected that `whoami` returns the expected identity. After an update, the runner will restart as the same, correct user (the service account), but their profile will no longer be fully loaded.

I've had to reproduce the issue many times in my testing so I also have a script you can use to automate setting up a new VM and starting the runner. Maybe it can help us figure out what's different about our environments.

```powershell
$username = "runneruser"
$password = "[PASSWORD]"
$githubUrl = "[URL]"
$githubToken = "[TOKEN]"

# Create user
$securePassword = ConvertTo-SecureString $password -AsPlainText -Force
New-LocalUser -Name $username -Password $securePassword
Add-LocalGroupMember -Group "Administrators" -Member $username

# Install and configure runner
$runnerLocation = "C:\runner"
$zipFile = "${env:Temp}\runner.zip"
Invoke-WebRequest "https://github.com/actions/runner/releases/download/v2.277.1/actions-runner-win-x64-2.277.1.zip" -OutFile "$zipFile"
Expand-Archive "$zipFile" "$runnerLocation"
& "$runnerLocation\config.cmd" --unattended --url "$githubUrl" --token "$githubToken"

# Schedule to run
$action = New-ScheduledTaskAction -WorkingDirectory "$runnerLocation" -Execute "run.cmd"
$trigger = Get-CimClass "MSFT_TaskRegistrationTrigger" -Namespace "Root/Microsoft/Windows/TaskScheduler"
Register-ScheduledTask -TaskName "runnertask" -Action $action -Trigger $trigger -User $username -Password $password -RunLevel Highest -Force
```

**Comment by fhammerl** [comment] 2021-06-03 21:37
Definitely upgraded, successfully, from 2.277.1 updating to 2.278.0, then ran the workflow you linked.

> Make sure the target user is logged out. It sounds like you are testing on a local machine, but if you are using RDP to log in as the service account on a remote machine, make sure you actually log out, not just close the RDP connection.

Good point, although I ran `query user` and it only showed mine. Anyway, the script should be very helpful, I'll look into it on a VM that matches your OS.

**Comment by fhammerl** [comment] 2021-06-04 22:08
Small update @MatisseHack, using your script I managed to repro it on a Windows server VM, but never locally on Windows 10 (I wonder why that is, any guesses?). Anyways, this should make things easier to test.

**Comment by MatisseHack** [comment] 2021-06-05 00:03
I just spun up a Windows 10 VM in Azure and I can verify that the issue does not present itself. Must be some difference between Windows 10 and Windows Server 2019, but I have no idea why unfortunately. Very odd!

**Comment by TingluoHuang** [comment] 2021-06-05 02:07
🎉 we found a Windows bug.😂

**Comment by TingluoHuang** [comment] 2021-06-06 22:37
Few things we can try next:
- figure out whether this is only a runner issue or any dotnet core app have this issue. We can just create a sample dotnet core app that launch a process to invoke `start`
- figure out whether this is a dotnet core issue or windows issue, we can try to make a powershell script to repro this issue.

**Comment by MatisseHack** [comment] 2021-07-12 22:11
@fhammerl I noticed you opened an issue against dotnet. I love the clean repro you created!

I'd love to see the root cause solved, but not sure about the timeline for a fix in dotnet/windows. It also seems somewhat desirable to unify the update process for ephemeral and static runners regardless. Is there any appetite to merge #1124 in the meantime?

**Comment by fhammerl** [comment] 2021-07-22 09:27
Hi @MatisseHack, thank you for your patience on this one. I was hoping to get a response from the .NET team first, rather than a fix, but they've got their hands full just triaging issues. I merged your PR into the feature branch for now.

**Closed by fhammerl** 2021-07-22 09:27 UTC
Labels: bug
