### ISSUE TITLE
composite action does not allow for conditionals

### ISSUE THREAD

**Issue by davidkarlsen** [actions/runner#1283] opened 2021-08-21 12:47 UTC
**Describe the bug**
If a step in a composite-action uses `if` it fails:
```
rror: evryfs/composite-java-action/main/action.yaml (Line: 39, Col: 5): Unexpected value 'if'
Error: evryfs/composite-java-action/main/action.yaml (Line: 39, Col: 5): Unexpected value 'if'
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. evryfs/composite-java-action/main/action.yaml (Line: 39, Col: 5): Unexpected value 'if'
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load evryfs/composite-java-action/main/action.yaml
```

**To Reproduce**
1. Create a composite action using a conditional step

**Expected behavior**
It should work as in a normal workflow

## Runner Version and Platform
2.280.3

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
```
rror: evryfs/composite-java-action/main/action.yaml (Line: 39, Col: 5): Unexpected value 'if'
Error: evryfs/composite-java-action/main/action.yaml (Line: 39, Col: 5): Unexpected value 'if'
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. evryfs/composite-java-action/main/action.yaml (Line: 39, Col: 5): Unexpected value 'if'
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load evryfs/composite-java-action/main/action.yaml
```

## Job Log Output
See above

## Runner and Worker's Diagnostic Logs
N/A

**Comment by thboop** [comment] 2021-08-23 11:35
Dupe of https://github.com/actions/runner/issues/834

**Closed by thboop** 2021-08-23 11:35 UTC
Labels: bug
