### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by andreaskaris** [actions/runner#1727] opened 2022-03-03 12:59 UTC
**Describe the bug**

Hi there,

After enabling caching in our CI jobs, we hit an occurrence of "GitHub Actions has encountered an internal error when running your job.
" for a single run. I'm not sure if this is a one-off or if this is related to the recent changes to our workflow .yaml.

https://github.com/ovn-org/ovn-kubernetes/actions/runs/1925302153
~~~
 e2e (shard-conformance, noHA, local, ipv4, snatGW, 1br)
GitHub Actions has encountered an internal error when running your job.
~~~

I have seen other occurrences of this error message online (and in this issues section). The aforementioned error message is not very helpful. Is it possible to get an analysis of what happened during that specific run and in the future, could you relay a few more details about the error to the end user so that we can identify the source of the issue?

Thanks!

- Andreas

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? Linux

## What's not working?
Please include error messages and screenshots.

![image](https://user-images.githubusercontent.com/3291433/156569348-52c4bcc0-08c9-4a34-bf7a-875170b08be1.png)

![image](https://user-images.githubusercontent.com/3291433/156569420-f830bf1f-2234-4fa8-93ad-7d7309789493.png)

## Job Log Output
There are no logs.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment] 2022-03-03 16:01
Hi @andreaskaris,

This issue is related to the service, which failed to send the job to the runner. Since it is not related to the runner, I will close this issue now.

Please post this on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 

Thank you!

**Closed by nikola-jokic** 2022-03-03 16:01 UTC
Labels: bug

**Comment by andreaskaris** [comment] 2022-03-03 18:13
@nikola-jokic Thanks for the fast answer. In case you see this, and just to confirm: would this indicate that something was wrong with github itself? We are using github's own action runners, not our own. So if the service (github) failed to send the job to the runner (github runner), then this indicates an issue outside of our control and unrelated to our workflow configuration, correct?

**Comment by nikola-jokic** [comment] 2022-03-04 10:03
Hi @andreaskaris,

Since the workflow was executed on the second call, I would say that the workflow configuration was correct and that the issue is unrelated to it. We cannot fix it here, since the workflow never even got to the runner on the first run.

But thank you for raising this issue and please, post it to the community support forum. People monitoring the forum should know about it so we can fix it for you, and everyone that might experience the same problem 😊

**Comment by andreaskaris** [comment] 2022-03-04 16:40
Thank you so much!
