### ISSUE TITLE
config cannot handle symlinks

### ISSUE THREAD

**Issue by IceflowRE** [actions/runner#2342] opened 2022-12-26 20:48 UTC
**Describe the bug**
Iam inside a docker container based on this [image](https://github.com/actions/runner/blob/main/images/Dockerfile).
OS: `Linux/Ubuntu`
Version: `2.300.2`
Arch: `arm64`

Iam using symlinks for
- `.credentials`
- `.credentials_rsaparams`
- `.env`
- `.path`
- `.runner`

```
RUN mkdir /actions-runner-config/ \
&& touch /actions-runner-config/.credentials \
&& ln -s /actions-runner-config/.credentials .credentials \
&& touch /actions-runner-config/.credentials_rsaparams \
&& ln -s /actions-runner-config/.credentials_rsaparams .credentials_rsaparams \
&& touch /actions-runner-config/.env \
&& ln -s /actions-runner-config/.env .env \
&& touch /actions-runner-config/.path \
&& ln -s /actions-runner-config/.path .path \
&& touch /actions-runner-config/.runner \
&& ln -s /actions-runner-config/.runner .runner
```

Now i run
```
root@d12f802e0d14:/actions-runner# ./config.sh --url https://github.com/actions --token ?????????????????????? --unattended --disableupdate
```

```
[RUNNER 2022-12-26 20:46:30Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[RUNNER 2022-12-26 20:46:30Z INFO HostContext] Well known directory 'Bin': '/actions-runner/bin'
[RUNNER 2022-12-26 20:46:30Z INFO HostContext] Well known directory 'Root': '/actions-runner'
[RUNNER 2022-12-26 20:46:30Z INFO HostContext] Well known config file 'Credentials': '/actions-runner/.credentials'
[RUNNER 2022-12-26 20:46:31Z INFO HostContext] Well known directory 'Bin': '/actions-runner/bin'
[RUNNER 2022-12-26 20:46:31Z INFO HostContext] Well known directory 'Root': '/actions-runner'
[RUNNER 2022-12-26 20:46:31Z INFO HostContext] Well known config file 'Runner': '/actions-runner/.runner'
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
   at GitHub.Runner.Listener.Program.Main(String[] args)
./config.sh: line 81:    65 Aborted                 (core dumped) ./bin/Runner.Listener configure "$@"
```

**Comment by nikola-jokic** [comment] 2022-12-27 08:47
Hey @IceflowRE,

Thank you for submitting this! We will try to reproduce the issue and get back to you as soon as we can :relaxed:

**Comment by nikola-jokic** [comment] 2022-12-27 12:45
I reproduced the issue. The reason this is happening is that `HostContext` sees that `.runner` file exists and tries to use it. Since this file is empty, the object is null and an exception is thrown. Regardless of the fix, the existence of files will tell the runner that it has been configured, and you would still have to remove those files and re-configure.

I created PR https://github.com/actions/runner/pull/2343 fixing the NullReference exception, but it won't solve it for your use-case. Since this is by design, and you feel like your suggestion would be a good addition to the runner, please submit your feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) :relaxed: . The forum is actively monitored and using it will help us prioritize enhancements to the runner.

**Comment by IceflowRE** [comment] 2022-12-27 14:46
Thanks for the quick feedback!
For now i use a workaround. Configure first, then move the file and create the symlink after and finally run it.
Will publish a follow up later, when i get the time, to the Support Forum and also write about my experience using it with docker and docker compose.

**Comment by nikola-jokic** [comment] 2022-12-27 15:00
No problem :relaxed: 

By the way, this issue is not related to the container. The same thing would happen if you are using it on a host machine. The issue is that the runner expects no configuration files present at the time of configuration. So if you do have them, then the runner is considered configured, and you would need to remove it.

I will close this issue now, since the behaviour is expected, and my PR does not fix this issue. Just addresses the exception before we are able to print configuration failure :relaxed:

**Closed by nikola-jokic** 2022-12-27 15:00 UTC
Labels: bug, awaiting-customer-response
