### ISSUE TITLE
Matrix jobs dynamic output

### ISSUE THREAD

**Issue by caio-eiq** [actions/runner#2499] opened 2023-03-22 15:16 UTC
**Describe the bug**
When using the new dynamic output for matrix jobs feature released in the latest version the workflow won't start. The PR merged and released to [v2.303.0](https://github.com/actions/runner/releases/tag/v2.303.0) is #2477.

**To Reproduce**
1. Write a simple workflow with using Matrix
2. Define an output

(Example):

```
  deploy:
    needs: [pre-check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NAMES: ${{ fromJson(needs.pre-check.outputs.NAMES) }}
    outputs:
      ${{ matrix.NAMES }}_result: ${{ steps.matrix_output.outputs.JOB_STATUS }}
    steps:
      - name: Check status
         id: matrix_output
         run: "JOB_STATUS=FAILURE" >> $GITHUB_OUTPUT
```

**Expected behavior**
The dynamic `$matrix` variable should be supported to use in the `outputs` key as per the PR #2477 merged and released a couple of weeks ago.

## Runner Version and Platform
Version of your runner? **v2.303.0**

OS of the machine running the runner? **Linux (Ubuntu-latest)**

## What's not working?
The workflow won't even start since the `$matrix` variable can't be recognized.

ERROR:
```
Invalid workflow file: .github/workflows/dev.yml#L68)
The workflow is not valid. .github/workflows/dev.yml (Line: 68, Col: 7): Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.NAMES
```

**Comment by alvarezfr** [comment] 2023-03-23 11:31
I think this is not a bug, [they tell in the PR that there are still some changes to do on the server side](https://github.com/actions/runner/pull/2477#:~:text=job1.outputs%5B%22linux_x86_result%22%5D%20%7D%7D-,Please%20note%20that%3A%20Server%20side%20changes%20are%20still%20in%2Dprogess,-%F0%9F%91%8D). 

But they did not provide any ETA right now.

**Comment by ajaykn** [comment] 2023-03-24 01:37
@caio-eiq  Apologies for confusion. This feature is not released yet and ETA would be another 2-3 weeks.

We have updated the release notes and PR description to be more precise.
Please check: https://github.com/actions/runner/pull/2477#issuecomment-1481459743

**Comment by ruvceskistefan** [comment] 2023-04-07 13:20
Hey @caio-eiq, since this is not a Runner bug I'll close this issue. You can reopen it on the service side if you think it's needed since they already have PR ready for it. 😄

**Closed by ruvceskistefan** 2023-04-07 13:20 UTC
Labels: bug
