### ISSUE TITLE
Conditional on a job fails if double quotes are used

### ISSUE THREAD

**Issue by djolez** [actions/runner#866] opened 2020-12-17 11:44 UTC
**Describe the bug**
Using double quotes in a conditional for a job results in
```
The workflow is not valid. <file_path>: Unexpected symbol: '"workflow_dispatch"'. Located at position 22 within expression: github.event_name != "workflow_dispatch"
```

**To Reproduce**
1. Create a job with a conditional
```
test-job:
    name: Use double quotes
    if: github.event_name != "workflow_dispatch"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
```
2. Run it
3. See above mentioned error
4. Use single quotes instead `if: github.event_name != 'workflow_dispatch'`, it works

**Expected behavior**
Job should pass regardless of type of quotes used

## Runner Version and Platform
`2.274.2`

OS of the machine running the runner? Ubuntu 18.04

## What's not working?
N/A

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by memchenko** [comment] 2021-06-09 14:31
Hi!
I got the same error with `hashFiles("**/yarn.lock")` when trying to cache `node_modules` using `actions/cache@v2`

**Comment by solarmosaic-kflorence** [comment] 2021-11-05 17:00
Ran into this as well https://github.com/actions/runner/issues/834#issuecomment-962044587 😕

**Comment by drecali** [comment] 2021-11-12 11:00
I just experienced this problem. The action fails with a status `Startup failure` Here is the error I get:

```
Invalid workflow file : .github/workflows/cypress-tests.yml#L32
The workflow is not valid. .github/workflows/cypress-tests.yml (Line: 32, Col: 13): Unexpected symbol: '"--t"'. Located at position 44 within expression: contains(github.event.head_commit.message, "--t")
```

Here is the line of code responsible:
```yml
if: contains(github.event.head_commit.message, "--t")
```

Here is the same line with single quotes. This works:
```yml
if: contains(github.event.head_commit.message, '--t')
```

**Comment by drecali** [comment] 2021-11-12 11:51
@djolez @solarmosaic-kflorence 
According to the docs it seems like this is the [intended behavior](https://docs.github.com/en/actions/learn-github-actions/expressions#:~:text=you%20must%20use%20single%20quotes.%20escape%20literal%20single-quotes%20with%20a%20single%20quote.).

> You must use single quotes. Escape literal single-quotes with a single quote.

```yml
myString: ${{ 'Mona the Octocat' }}
```

I just experienced this problem and it was quite inconvenient to debug. I thought single or double quotes didn't matter. I know actions use YAML syntax but I'm not clear what syntax Expressions use. It would be great if it's possible to allow the use of both types of quotes inside Expressions.

I'll include this in case it helps anyone debug. In my case the action failed with a status `Startup failure`. I included the errors I got below. I suspected the double quotes because the double quoted string was referred to as a `symbol` and included the double quotes. I would expect a `symbol` to be a special character like an escape sequence such as `\n`. I read this page of the YAML docs and I didn't understand clearly why double quotes might not be allowed in this case.(https://www.yaml.info/learn/quote.html). 

```
Invalid workflow file : .github/workflows/cypress-tests.yml#L32
The workflow is not valid. .github/workflows/cypress-tests.yml (Line: 32, Col: 13): Unexpected symbol: '"--t"'. Located at position 44 within expression: contains(github.event.head_commit.message, "--t")
```

Here is the line of code responsible:
```yml
if: contains(github.event.head_commit.message, "--t")
```

Here is the same line with single quotes. This works:
```yml
if: contains(github.event.head_commit.message, '--t')
```

**Comment by solarmosaic-kflorence** [comment] 2021-11-12 16:48
@drecali I'm aware that the documentation mentions only single quote is valid (after the fact, of course). However, I think that behavior is not intuitive, since double quotes are valid throughout the rest of the YAML syntax. Unless there is a good reason not to support double quotes, it should be fixed.

**Comment by drecali** [comment] 2021-11-15 01:44
@solarmosaic-kflorence 
I agree with you 100%. I didn't see a link to the specific line in the documentation or in #834 so I wanted to add it. The docs were mentioned quite far up the comment thread in #834 so that's why I added the link here and tagged you because you referred that issue here. I hope expressions become quote-agnostic soon, or at least I'd like to understand technical reasons why that may not be possible/ideal.

**Comment by ruvceskistefan** [comment] 2022-03-09 08:06
GitHub Actions only support the use of single quotes for strings in expression language, not double quotes (see [docs](https://docs.github.com/en/actions/learn-github-actions/expressions#literals)). This is an intentional limitation (at least for now) and is not something that can be fixed in the runner application. Therefore, I'm going to close this issue, and you feel free to create a feature request on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your feature request to the correct team. 😃

**Closed by ruvceskistefan** 2022-03-09 08:06 UTC
Labels: Service Bug
