### ISSUE TITLE
Self-hosted runner fails to restart after update

### ISSUE THREAD

**Issue by gasrodriguez** [actions/runner#1831] opened 2022-04-18 20:23 UTC
**Describe the bug**
After every automatic-update, the runner stops working and have to be restarted manually.

**To Reproduce**
It happens with every new update.

**Expected behavior**
After update it says will get back online in 10 sec but it doesn't.

## Runner Version and Platform
Version of your runner?
Is happening with previous versions to 2.290.1 (have to wait until 2.290.2 to see if  2.290.1 also fails ;))

OS of the machine running the runner? 
```
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel: Linux 3.10.0-1160.el7.x86_64
  Architecture: x86-64
```
## What's not working?
```
Downloading 2.290.1 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
```
After this it exit instead of restart by itself.

## Job Log Output
```
[2022-03-23 21:22:04Z INFO SelfUpdater] Update script start running
[2022-03-23 21:22:04Z INFO Terminal] WRITE LINE: Runner will exit shortly for update, should be back online within 10 seconds.
[2022-03-23 21:22:04Z INFO SelfUpdater] TotalUpdateTime: 104670ms
[2022-03-23 21:22:04Z INFO Terminal] WRITE LINE: Runner update process finished.
[2022-03-23 21:22:04Z INFO Runner] Auto update task finished at backend, an runner update is ready to apply exit the current runner instance.
[2022-03-23 21:22:04Z INFO Runner] Stop message queue looping.
[2022-03-23 21:22:04Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/0bkmVmnYDFIUdJkHMSCdWvL46hEM4ONnQ4KEHI5awWG1FQd7Z3/_apis/distributedtask/pools/2/messages?sessionId=9a52b888-0fbd-44df-8bd2-d51d719cfcaf&lastMessageId=1706 has been cancelled.
[2022-03-23 21:22:04Z INFO MessageListener] Get next message has been cancelled.
[2022-03-23 21:22:04Z INFO Runner] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
[2022-03-23 21:22:04Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-03-23 21:22:04Z INFO Listener] Runner execution has finished with return code 3
```

**Comment by Flydiverny** [comment] 2022-04-19 05:33
Seems like the same issue as in #1812

**Comment by ruvceskistefan** [comment] 2022-04-19 08:11
Hi @gasrodriguez,
This issue is a duplicate of the existing one: #1812, which we are currently working on. Therefore, I will close this issue, and you can follow up working on the existing issue.

**Closed by ruvceskistefan** 2022-04-19 08:11 UTC
Labels: bug
