### ISSUE TITLE
Github Actions runner does not automatically resume after Auto-update

### ISSUE THREAD

**Issue by TheOnlyWei** [actions/runner#1812] opened 2022-04-06 17:57 UTC
This issue has been changed to a bug, since the behavior is unexpected. See this comment for the logs:
https://github.com/actions/runner/issues/1812#issuecomment-1090780199

**Describe the enhancement**
I am using a self-hosted runner, not sure how this applies to regular runners.

After Github Actions runner auto-update, if the auto-update stopped a running Github Actions runner, it should automatically resume it after completing the update. Currently, I have to log into my VM every time there is an update to re-run run.cmd.

**Additional information**
I use self-hosted runners.

**Comment by thboop** [comment] 2022-04-06 19:46
Hey @TheOnlyWei , it should automatically resume on update, can you provide more information on your OS, how you are running the runner (as a service or run.sh) and what runner version you are seeing this on? Also, if you have the [diagnostic logs](https://github.com/actions/runner/blob/main/.github/ISSUE_TEMPLATE/bug_report.md#runner-and-workers-diagnostic-logs) for the runner, that would be very helpful, particularly the `SELFUPDATE` one

**Comment by TheOnlyWei** [comment] 2022-04-06 20:50
@thboop Messages that may be relevant.

Console:
```
Runner update in progress, do not shutdown runner.
Downloading 2.289.2 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
```

Runner log:
```
[2022-04-05 07:03:21Z INFO SelfUpdater] Update script start running
[2022-04-05 07:03:21Z INFO Terminal] WRITE LINE: Runner will exit shortly for update, should be back online within 10 seconds.
[2022-04-05 07:03:21Z INFO SelfUpdater] TotalUpdateTime: 88132ms
[2022-04-05 07:03:21Z INFO Terminal] WRITE LINE: Runner update process finished.
[2022-04-05 07:03:22Z INFO Runner] Auto update task finished at backend, an runner update is ready to apply exit the current runner instance.
[2022-04-05 07:03:22Z INFO Runner] Stop message queue looping.
[2022-04-05 07:03:22Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/<omitted>/_apis/distributedtask/pools/1/messages?sessionId=<omitted>1&lastMessageId=209 has been cancelled.
[2022-04-05 07:03:22Z INFO MessageListener] Get next message has been cancelled.
[2022-04-05 07:03:23Z INFO Runner] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
[2022-04-05 07:03:23Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-04-05 07:03:24Z INFO Listener] Runner execution has finished with return code 3
```

**Comment by lavakumar-rajanala-by** [comment] 2022-04-11 06:15
I am also facing the same issue in multiple self-hosted runners when upgrade is happening to runner and i had to run the run.cmd every time by logging to machine.

**Comment by ppamorim** [comment] 2022-04-15 22:08
Our macOS running keeps stopping after the auto update. I need to manually fix the runner every week due this issue. Please Github do something.

<img width="517" alt="Screenshot 2022-04-15 at 23 05 20" src="https://user-images.githubusercontent.com/5521682/163647098-134f0da4-1758-4f05-b836-db4a7f6e721e.png">

**Comment by scaires** [comment] 2022-04-18 22:53
I have been seeing my run.sh runners, on a self-hosted macOS machine die about once a day due to a failure to restart after an update, or every few days.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/478385/163889786-8568cbf9-8d1f-43da-99fa-978d8f387474.png">

**Comment by fhammerl** [comment] 2022-04-19 23:18
Thank you for reporting this issue. The release archives were indeed corrupted (thanks @mumoshu for the tip) and we've identified the root cause in our release process. We're working on a fix ASAP!

**Comment by bryantson** [comment] 2022-04-19 23:48
Thank you, @fhammerl Please keep us looped

**Comment by Shmiza** [comment] 2022-04-20 10:39
I had the same issue with, update the runner version to 2.289.3
It appears to be working now: 

`Current runner version: '2.289.3'
Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.290.1 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.

√ Connected to GitHub

Current runner version: '2.290.1'`

**Comment by mumoshu** [comment] 2022-04-29 03:23
@uportalis From which version did it try to auto-upgrade to 2.290.1? I believe it should be at least 2.289.2 to be able to auto-upgrade to 2.289.3, 2.290.1, etc.

**Comment by uportalis** [comment] 2022-04-29 09:19
@mumoshu I did not verify on all my self-hosted runner, but all the ones I checked performed a self-update from 2.289.2 to 2.290.1.

**Comment by fhammerl** [comment] 2022-05-03 14:45
This issue has been fixed in `v2.291.1`. However, this fix only applies to future runner upgrades from that version, not upgrading **to** that version, so you may still encounter this one last time.

Thank you for your patience while we addressed this issue.

**Comment by bryantson** [comment] 2022-05-11 16:28
@fhammerl 

One of my customers was waiting for this. I will let the customer to try it out and to verify :)

**Comment by thboop** [comment] 2022-09-19 17:00
This should be fixed now. Going to close it out unless someone sees it happen again

**Closed by thboop** 2022-09-19 17:00 UTC
Labels: bug, Runner Bug
