### ISSUE TITLE
When --platform is in options, pass it to docker pull

### ISSUE THREAD

**Issue by pmatos** [actions/runner#648] opened 2020-08-07 13:37 UTC
**Describe the enhancement**

Lets say I create a multi-platform image, for linux/amd64 and linux/386. 
I cannot run this on a hosted runner due to https://github.com/actions/virtual-environments/issues/1368 however, I thought I could setup a self-hosted runner to run this by enabling the docker service to run with experimental mode. 

I have:
```
  buildtest-linux_i386:
    runs-on: [self-hosted, Linux, X64]

    container:
      image: racket/racket-ci:latest
      options: --init --platform 'linux/386'

   ...
```

This does not work because the first step the runner does it `docker pull <image>`. This will pull the wrong image because it doesn't take into consideration the `--platform 'linux/386'` option. So on a `amd64` system, it will pull the image for `amd64` and then the `--platform` option to `docker create` is a no-op because we already pulled the wrong image.

**Comment by hross** [comment] 2021-03-30 20:25
Closing in favor of https://github.com/actions/runner/issues/320

**Closed by hross** 2021-03-30 20:25 UTC
Labels: enhancement

**Comment by molinav** [comment] 2023-06-09 09:53
I just found this closed issue because I am experiencing exactly this problem. Until May 2023, the GitHub Runner was able to fetch `linux/386` images from a `linux/amd64` host (`ubuntu-latest`) when `linux/386` was the only architecture available. The logs would show a warning, but the job could run completely without issues:
```
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

See e.g. https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160
```
Current runner version: '[2](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:2).[3](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:3)0[4](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:4).0'
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230426.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230426.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230426.1
Runner Image Provisioner
  2.0.171.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/download-artifact@v1' (SHA:18f0f[5](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:5)91fbc[6](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:7)35562c815484d[7](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:8)3b6e[8](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:9)e3[9](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:10)80482e)
Download action repository 'actions/upload-artifact@v1' (SHA:3446296876d12d4e3a0f3145a3c87e67bf0a16b5)
Complete job name: build-geos (x86)
4s
Checking docker version
  /usr/bin/docker version --format '{{.Server.APIVersion}}'
  '1.41'
  Docker daemon API version: '1.41'
  /usr/bin/docker version --format '{{.Client.APIVersion}}'
  '1.41'
  Docker client API version: '1.41'
Clean up resources from previous jobs
  /usr/bin/docker ps --all --quiet --no-trunc --filter "label=ed866e"
  /usr/bin/docker network prune --force --filter "label=ed866e"
Create local container network
  /usr/bin/docker network create --label ed866e github_network_a3e86d25a9954ca399a7fc2f5d82f62d
  a68516ada1dbf4[10](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:11)5c9c4610bd3f4a1cc14238d9d7bacaf963a4bfd18616d328
Starting job container
  /usr/bin/docker pull pylegacy/x86-python:3.6-debian-4
  3.6-debian-4: Pulling from pylegacy/x86-python
  69a8f9aa6ed9: Pulling fs layer
  abcbd93da2ba: Pulling fs layer
  7cdf4aa6770b: Pulling fs layer
  bfef4410b276: Pulling fs layer
  409178235367: Pulling fs layer
  bfef4410b276: Waiting
  409178235367: Waiting
  abcbd93da2ba: Verifying Checksum
  abcbd93da2ba: Download complete
  69a8f9aa6ed9: Verifying Checksum
  69a8f9aa6ed9: Download complete
  bfef4410b276: Verifying Checksum
  bfef4410b276: Download complete
  409178235367: Verifying Checksum
  409178235367: Download complete
  7cdf4aa6770b: Verifying Checksum
  7cdf4aa6770b: Download complete
  69a8f9aa6ed9: Pull complete
  abcbd93da2ba: Pull complete
  7cdf4aa6770b: Pull complete
  bfef4410b276: Pull complete
  409178235367: Pull complete
  Digest: sha256:0ddfa0fae32475607413b5e4bd97a6eff79b005b6aa4b8c93cd[11](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:13)ef38f2e7824
  Status: Downloaded newer image for pylegacy/x86-python:3.6-debian-4
  docker.io/pylegacy/x86-python:3.6-debian-4
  /usr/bin/docker create --name 30032b1d426149dba67ab4c6021ca724_pylegacyx86python36debian4_a925b2 --label ed866e --workdir /__w/basemap/basemap --network github_network_a3e86d25a9954ca399a7fc2f5d82f62d  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.304.0/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" pylegacy/x86-python:3.6-debian-4 "-f" "/dev/null"
  WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
  c647ad25c15b9afb36ba4796d197198e0fb15e3bff52637[12](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:14)269636d185b2ad1
  /usr/bin/docker start c647ad25c[15](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:18)b9afb36ba4796d197198e0fb15e3bff5263712269636d[18](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:21)5b2ad1
  c647ad25c15b9afb36ba4796d[19](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:22)7198e0fb15e3bff526371[22](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:25)69636d185b2ad1
  /usr/bin/docker ps --all --filter id=c647ad[25](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:28)c15b9afb36ba4796d197198e0fb15e3bff5[26](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:1:29)37[1](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:1)[2](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:2)2696[3](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:3)6d185b2ad1 --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
  c6[4](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:4)7ad2[5](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:5)c15b9afb3[6](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:6)ba4[7](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:7)96d19719[8](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:9)e0fb15e3bff526371226[9](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:10)636d185b2ad1 Up Less than a second
  /usr/bin/docker inspect --format "{{range .Config.Env}}{{println .}}{{end}}" c647ad25c15b9afb36ba4796d197198e0fb15e3bff52637[12](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:14)269636d[18](https://github.com/matplotlib/basemap/actions/runs/4890672839/jobs/8730387160#step:2:21)5b2ad1
  GITHUB_ACTIONS=true
  CI=true
  HOME=/github/home
  PATH=/opt/pyenv/shims:/opt/pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  ENV=/etc/profile
  LANG=POSIX
  LANGUAGE=POSIX
  LC_ALL=POSIX
  TZ=UTC
  PYENV_ROOT=/opt/pyenv
Waiting for all services to be ready
```

After the deployment of the new GitHub runners around mid May 2023 or start of June 2023, the same workflows now fail because `docker` is forcing to pull a `linux/amd64` image and only a (expected) `linux/386` image is available, and I cannot find a way to force the pull of the `linux/386` image because the `--platform` option is not passed to the `docker pull` call:
```
  /usr/bin/docker pull pylegacy/x86-python:3.6-debian-4
  3.6-debian-4: Pulling from pylegacy/x86-python
  no matching manifest for linux/amd64 in the manifest list entries
  Warning: Docker pull failed with exit code 1, back off 8.778 seconds before retry.
```

See e.g. https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735
```
Current runner version: '[2](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:2).[3](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:3)0[4](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:4).0'
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230[5](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:5)17.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230517.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230517.1
Runner Image Provisioner
  2.0.171.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/download-artifact@v1' (SHA:18f0f591fbc[6](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:7)35562c815484d[7](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:8)3b6e[8](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:9)e3[9](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:10)80482e)
Download action repository 'actions/upload-artifact@v1' (SHA:3446296876d[12](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:14)d4e3a0f3[14](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:17)5a3c87e67bf0a16b5)
Complete job name: build-geos (x86)
[15](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:18)s
Checking docker version
  /usr/bin/docker version --format '{{.Server.APIVersion}}'
  '1.41'
  Docker daemon API version: '1.41'
  /usr/bin/docker version --format '{{.Client.APIVersion}}'
  '1.41'
  Docker client API version: '1.41'
Clean up resources from previous jobs
  /usr/bin/docker ps --all --quiet --no-trunc --filter "label=ed866e"
  /usr/bin/docker network prune --force --filter "label=ed866e"
Create local container network
  /usr/bin/docker network create --label ed866e github_network_c8e80c60651a4a5394954933a51f7447
  f7f89b881c0fc65b5ef2faedd744fe76c[18](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:1:21)6f[1](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:1)c[2](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:2)a7b6648c6a05b65f7[3](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:3)ed0670
Starting job container
  /usr/bin/docker pull pylegacy/x86-python:3.6-debian-[4](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:4)
  3.6-debian-4: Pulling from pylegacy/x86-python
  no matching manifest for linux/amd64 in the manifest list entries
  Warning: Docker pull failed with exit code 1, back off 7.862 seconds before retry.
  /usr/bin/docker pull pylegacy/x86-python:3.6-debian-4
  3.6-debian-4: Pulling from pylegacy/x86-python
  no matching manifest for linux/amd64 in the manifest list entries
  Warning: Docker pull failed with exit code 1, back off 6.1[5](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:5)[6](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:6) seconds before retry.
  /usr/bin/docker pull pylegacy/x[8](https://github.com/matplotlib/basemap/actions/runs/5218138554/jobs/9418704735#step:2:9)6-python:3.6-debian-4
  3.6-debian-4: Pulling from pylegacy/x86-python
  no matching manifest for linux/amd64 in the manifest list entries
  Error: Docker pull failed with exit code 1
```

Is there any workaround to this problem? Usable workflows until mid May 2023 are now failing, so I would consider this as a regression.
