### ISSUE TITLE
Error when auto-upgrading runner service on MacOS - service fails to restart after upgrade

### ISSUE THREAD

**Issue by tribu** [actions/runner#1875] opened 2022-05-04 17:06 UTC
The issue I am facing is similar to  https://github.com/actions/runner/issues/743
Basically after the upgrade to latest Runner the upgraded runner fails to connect with Github. I have to manually start the run.sh script to connect.

We are running non-m1 MacOS on AWS.

![image](https://user-images.githubusercontent.com/6642495/166740987-32cec15e-c792-427d-b2c5-1559ff6b8e72.png)

**Comment by thboop** [comment] 2022-05-04 20:05
Hey @tribu , this is a dupe of #1812. Once you upgrade to `2.291.1`, you should no longer see this issue on future upgrades. For more details, please [see](https://github.com/actions/runner/issues/1812#issuecomment-1116185535)

Sorry for the churn this may have caused you.

**Closed by thboop** 2022-05-04 20:05 UTC
Labels: bug

**Comment by tribu** [comment] 2022-05-11 15:29
Thank you !!!
