### ISSUE TITLE
How to stop self-updating

### ISSUE THREAD

**Issue by summerwind** [actions/runner#431] opened 2020-04-16 08:43 UTC
Is there a good way to stop runner's self-updating behavior?

I'm running self-hosted runners as a Pod on Kubernetes. When a new version of self-hosted runner was released, runner tried to update itself. I think that this behavior may cause unintended problems as the Runner is updated even though the administrator does not want it.

**Comment by SvanBoxel** [comment] 2020-04-17 13:15
Related: https://github.com/actions/runner/issues/246

**Comment by bryanmacfarlane** [comment] 2020-04-17 13:36
This is a dupe of #246 with most of the discussion captured there.

**Closed by bryanmacfarlane** 2020-04-17 13:36 UTC
Labels: bug
