### ISSUE TITLE
298.2 actions checkout error

### ISSUE THREAD

**Issue by ashriram** [actions/runner#2191] opened 2022-10-09 18:08 UTC
**Describe the bug**

Error: Command failed: rm -rf "/home/docker/actions-runner/_work/assignment-2-mishasinitcyn/assignment-2-mishasinitcyn/.git"
rm: cannot remove '/home/docker/actions-runner/_work/assignment-2-mishasinitcyn/assignment-2-mishasinitcyn/.git/hooks': Directory not empty
rm: cannot remove '/home/docker/actions-runner/_work/assignment-2-mishasinitcyn/assignment-2-mishasinitcyn/.git/info': Directory not empty
rm: cannot remove '/home/docker/actions-runner/_work/assignment-2-mishasinitcyn/assignment-2-mishasinitcyn/.git/refs/remotes/origin': Directory not empty
rm: cannot remove '/home/docker/actions-runner/_work/assignment-2-mishasinitcyn/assignment-2-mishasinitcyn/.git/objects/pack': Directory not empty
rm: cannot remove '/home/docker/actions-runner/_work/assignment-2-mishasinitcyn/assignment-2-mishasinitcyn/.git/logs/refs/remotes/origin': Directory not empty

(node:[84](https://github.com/CMPT-295-SFU/assignment-2-mishasinitcyn/actions/runs/3214916117/jobs/5255644523#step:2:88)696) UnhandledPromiseRejectionWarning: Error: Command failed: rm -rf "/home/docker/actions-runner/_work/_temp/e977c0c9-2d91-458e-8cc5-c37ffd11e[87](https://github.com/CMPT-295-SFU/assignment-2-mishasinitcyn/actions/runs/3214916117/jobs/5255644523#step:2:91)7"
rm: cannot remove '/home/docker/actions-runner/_work/_temp/e977c0c9-2d91-458e-8cc5-c37ffd11e877': Directory not empty

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
(node:145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner? 298.2
OS of the machine running the runner? OSX/Windows/Linux/...
Linux (actions running inside docker)
## What's not working?
Please include error messages and screenshots.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
(node:145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ashriram** [comment] 2022-10-09 18:09
I am behind a university proxy but nodeJS checkouts used to work in 297. I do have http_proxy and https_proxy set up.

**Comment by nikola-jokic** [comment] 2022-10-10 13:07
Hey @ashriram,

Thank you for reporting this issue. Can you please tell me, are you running your workflow in a container? Can you provide an example workflow, so we can reproduce this bug?

**Comment by ashriram** [comment] 2022-10-10 20:12
I am running it in a container. Can be obtained here.
ashriram/cmpt295-runner:298-proxy

Container is behind university proxy (only happens behind proxy).
If I am not behind proxy it is ok. 

However, I ran run-check in actions and it appears to say nodeJS is ok.

ashriram/cmpt295-runner:297-proxy is fine. It does not report same error.

Seems similar to issue here: https://lightrun.com/answers/actions-checkout-permission-denied-when-deleting-the-contents-of

**Comment by nikola-jokic** [comment] 2022-10-11 08:39
Thanks for the response! Unfortunately, I cannot see the repo is probably private since I cannot see it. I will try to provide more context here. If you are running your runner as a user with uid `1001` for example on your system, and you execute a docker action as a user `1000` for example, files created inside the volume attached to your container will be owned by the user 1000 on your host machine. If that is the case, the runner will not be able to clean-up after itself since it does not have any permissions to do so. That might be an issue here. Please see the issue #434, and let me know it that is the source of the issue :relaxed:

**Comment by ashriram** [comment] 2022-10-13 19:01
I will give this a shot and also set up a public repo that you can investigate on. Thanks

**Comment by nikola-jokic** [comment] 2022-11-14 08:13
Hey @ashriram,

Did you manage to resolve this issue :relaxed: ?

**Comment by nikola-jokic** [comment] 2022-12-06 08:41
I will close this issue until we hear back from you. If you discover that the issue is not occurring for the reason I wrote above, feel free to re-open the issue, and please do provide the repo, so we can re-produce it.

**Closed by nikola-jokic** 2022-12-06 08:41 UTC
Labels: bug, awaiting-customer-response
