### ISSUE TITLE
OIDC server causes non-determenistic builds (AWS integration)

### ISSUE THREAD

**Issue by mariusingjer** [actions/runner#1466] opened 2021-11-05 11:58 UTC
**Describe the bug**
We have ported all our github actions to use Open Id Connect and therefore removing the need to share AWS access key as secret. Before when using access keys, our builds were stable, now we have daily interrupts because the Github OIDC server is not responding within the 5 seconds timeslot that AWS requires which means you get output like this:

![image](https://user-images.githubusercontent.com/65291983/140506732-3eef847b-4f1c-4bc7-8c33-fbe08dabc1bd.png)

We are using this action to authenticate: aws-actions/configure-aws-credentials@8eba69932f928f2bc1b9837d16a095e7e1cb0845

**To Reproduce**
1. Create a workflow with lots of parallell jobs authenticating with the aforementioned action
2. Run it

**Expected behavior**
Determenistic builds not failing due to server timeouts between github and AWS

## Runner Version and Platform

ubuntu-latest

**Comment by TingluoHuang** [comment] 2021-11-05 14:48
@mariusingjer can you share a link to your workflow run and some log around the error you see?

**Comment by mariusingjer** [comment] 2021-11-08 06:35
https://github.com/fremtind/demografiskepersondata/actions/runs/1416360117

**Comment by kchandra548** [comment] 2021-11-08 07:41
@mariusingjer I think we dont have access to that repo, getting 404 error.

**Comment by mariusingjer** [comment] 2021-11-08 07:45
Exact log from above build run at time of error (removed account and role info):
```
2021-11-03T10:54:58.9528060Z ##[group]Run aws-actions/configure-aws-credentials@8eba69932f928f2bc1b9837d16a095e7e1cb0845
2021-11-03T10:54:58.9528940Z with:
2021-11-03T10:54:58.9529504Z   role-to-assume: arn:aws:iam::12345678912:role/xxx
2021-11-03T10:54:58.9530131Z   aws-region: eu-west-1
2021-11-03T10:54:58.9530555Z ##[endgroup]
2021-11-03T10:55:02.4728044Z ##[error]Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements
```


> @mariusingjer I think we dont have access to that repo, getting 404 error.

Yes that is correct, this is a private repository, we are paying customers

**Comment by kchandra548** [comment] 2021-11-08 08:26
Thanks @mariusingjer  for the logs. By looking at the error message,  aws sts is not able to fetch keys from https://token.actions.githubusercontent.com/.well-known/jwks or it is getting timed out. I will try to reproduce same and will update the issue once I found more information.

**Comment by kchandra548** [comment] 2021-11-08 16:15
Hi @mariusingjer  I need some more information to find the root cause. 
 How many parallel jobs are running with OIDC authentication(approx)?
 How many of them are failing with this error? 
 if possible I need few more logs with timestamps from failed workflows.

**Comment by mariusingjer** [comment] 2021-11-08 17:00
More timestamps: 
```
2021-11-08T14:37:37.3184678Z ##[group]Run aws-actions/configure-aws-credentials@8eba69932f928f2bc1b9837d16a095e7e1cb0845
2021-11-08T14:37:37.3185774Z with:
2021-11-08T14:37:37.3186318Z   role-to-assume: arn:aws:iam::12345678912:role/xxxxxx
2021-11-08T14:37:37.3187451Z   aws-region: eu-west-1
2021-11-08T14:37:37.3187898Z ##[endgroup]
2021-11-08T14:37:41.2106319Z ##[error]Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements
```

In one workflow we have four parallell jobs who uses the aforementioned configure-aws-credentials. In the biggest workflow we have 7 parallell jobs, but we see failues in both workflows.

**Comment by kchandra548** [comment] 2021-11-10 12:38
Hi, @mariusingjer I am able to reproduce this with 10+ parallel jobs.
Tested similar thing GCP using 25 parallel workflows, no failures there. 
We need to check with AWS whether it is doing any rate-limiting. Found the same issue logged with AWS action here https://github.com/aws-actions/configure-aws-credentials/issues/299. I Will update here once I found more info.

**Comment by kchandra548** [comment] 2021-11-11 09:13
One more update, I wrote a small client using AWS STS Java SDK to get an access token using GH IDToken where I fired 20-300 requests in the loop, and all got succeeded.  When I tried the same thing with JS SDK got some errors similar to the above reported.
Here is the exception 
```
(node:22137) UnhandledPromiseRejectionWarning: InvalidIdentityToken: Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements
    at Request.extractError (/Users/kchandra548/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/kchandra548/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/kchandra548/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/kchandra548/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/kchandra548/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kchandra548/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kchandra548/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kchandra548/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kchandra548/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/kchandra548/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:22137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()
```

**Comment by mariusingjer** [comment] 2022-01-07 08:19
I just wrote a quick test to see if I could get the jwks endpoint to return slower than 5 seconds:

```
        [Fact]
        public async void Time_a_lof_of_requests()
        {
            var source = new TaskCompletionSource();

            var httpClient = new HttpClient();

            var tasks = Enumerable.Range(1, 1000).Select(_ => System.Threading.Tasks.Task.Factory.StartNew(async () =>
            {
                await source.Task;
                var timer = new Stopwatch();
                timer.Start();
                await httpClient.SendAsync(new HttpRequestMessage
                {
                    RequestUri = new System.Uri("https://token.actions.githubusercontent.com/.well-known/openid-configuration")
                });
                timer.Stop();
                return timer.Elapsed;
            }).Unwrap()).ToList();

            tasks.Add(Task.Run(() => {
                source.SetResult();
                return TimeSpan.Zero;
            }));

            await Task.WhenAll(tasks);

            foreach (var t in tasks.Where(t => t.Result > TimeSpan.FromSeconds(5)))
            {
                _output.WriteLine($"Time it took to call endpoint: {t.Result}");
            }
        }        
```

Output:

> Time it took to call endpoint: 00:00:07.0933388
> Time it took to call endpoint: 00:00:07.0932884
> Time it took to call endpoint: 00:00:07.1006106
> Time it took to call endpoint: 00:00:07.0975507
> Time it took to call endpoint: 00:00:07.0987544

So I was able to get a couple of requests to use more than 5 seconds when initiating 1000 requests from my machine, It could be a test-failure, in the sense that switching between the tasks is what makes up for the used time, but I am still going to ask: does Github enforce any sort of api-throttling so that tons of concurrent requests from AWS could cause this sort of behaviour?

**Comment by TingluoHuang** [comment] 2022-01-07 13:15
@kchandra548 do you know how the public endpoint `token.actions.githubusercontent.com` handles throttling?

**Comment by kchandra548** [comment] 2022-01-10 14:14
Not sure @TingluoHuang, at the time of debugging this issue I searched for this but didn't find any information on this.

**Comment by TingluoHuang** [comment] 2022-04-05 14:29
I am going to close this issue since the runner itself has no control over the problem, feel free to open ticket in https://github.community/c/code-to-cloud/github-actions/41

**Closed by TingluoHuang** 2022-04-05 14:29 UTC
Labels: bug, Service Bug
