### ISSUE TITLE
Embedded backslash in config dir name breaks Dropbox on Mac

### ISSUE THREAD

**Issue by dogweather** [actions/runner#1810] opened 2022-04-06 07:46 UTC
The runner creates a directory, `~/.config/GitHub\ActionsService/` on Mac and Linux. Dropbox chokes on this:

![DropboxError](https://user-images.githubusercontent.com/150670/161922725-8b0e9c66-bdc2-43e8-b686-64de73212b77.png)

Is the embedded backslash intended? While Dropbox ought to be able to handle it, it seems a little pathological. :-)

**Comment by ruvceskistefan** [comment] 2022-04-06 09:28
Hi @dogweather,
Thanks for reported issue! Backslash is certainly not intended here, I'll investigate the cause and we'll solve the problem.

**Comment by dogweather** [comment] 2022-04-06 10:27
@ruvceskistefan Thanks!

**Comment by ruvceskistefan** [comment] 2022-04-20 13:25
Hi @dogweather,
Can you send me more information: on which operating system does this happen to you and at what time (during config, extracting project or something else)?

**Comment by ChristopherHX** [comment] 2022-04-20 19:18
@ruvceskistefan 
I guess you already wrote an unmerged fix for this issue https://github.com/actions/runner/pull/1617, it just needs to be merged.

**Comment by ruvceskistefan** [comment] 2022-04-21 06:19
Thanks @ChristopherHX, I already forgot about that PR.

@dogweather
As @ChristopherHX said, there is PR #1617 that will fix this problem when it merges and is in production.

**Comment by dogweather** [comment] 2022-04-21 23:10
Thank you!

**Closed** 2022-04-28 02:16 UTC
Labels: bug, Runner Bug
