### ISSUE TITLE
Error in self hosted runner

### ISSUE THREAD

**Issue by vaibhavrja** [actions/runner#1366] opened 2021-09-24 07:12 UTC
I am facing a issue while try to run a github action workflow using self hosted runner. The runner is working perfectly but when I try to commit file I am getting a error Array buffer allocation failed. Some time I get error like shell cannot be started, a Error occured.
I am getting this error in run actions/checkout@v2 section.

**Comment by nikola-jokic** [comment] 2022-02-28 15:39
Hi @vaibhavrja,

This error relates to the spec of the machine not having enough memory to execute the desired action. Please see: https://github.com/Azure/azure-storage-node/issues/464#issuecomment-397144662

This problem is not related to the actions/runner itself, but I will leave this issue open just to be sure. Could you please check if this issue is still bothering you? And if yes, could you try to execute self-hosted runner on a machine with better specs?

**Comment by ruvceskistefan** [comment] 2022-03-04 10:10
Hi @vaibhavrja,

We checked and concluded that the problem is up to the specification of the machine. Therefore, I will close this issue, and if you think this is not the cause of the problem, feel free to reopen the issue.

**Closed by ruvceskistefan** 2022-03-04 10:10 UTC
Labels: awaiting-customer-response
