### ISSUE TITLE
Support Windows Containers

### ISSUE THREAD

**Issue by sirredbeard** [actions/runner#1402] opened 2021-10-04 23:00 UTC
**Describe the enhancement**

Support for Windows Containers in the GitHub Actions runner, even if only available on self-hosted runners, as in:

```
jobs:
  build:
    runs-on: windows-2022
    container:
      image: docker.pkg.github.com/sirredbeard/nim-windows-container/nimstable-ltsc2022:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
```

Currently GitHub Actions can be used to build and push Windows Containers to the GitHub Container Registry however GitHub Actions cannot *pull* Windows Containers to use for building or testing.

This is unfortunate and limits the adoption of Windows Containers for use on GitHub.

**Comment by ChristopherHX** [comment] 2021-10-05 08:02
You can try my fork of the runner https://github.com/ChristopherHX/runner.server/releases/latest

I reenabled disabled windows container support of this azure pipelines agent fork ( which has this feature ). At least it worked with docker desktop on windows.

Auto updates are disabled. ( version 3.3.2 >= actions/runner 2.xxx.x )

**Comment by ethomson** [comment] 2021-12-17 20:01
At this time, the inconsistencies in container support across different versions of Windows make this undertaking _very_ difficult.  At this time, we don't have any plans to enable Windows containers.  I'll put this on the backlog for the future.

**Comment by SS1823** [comment] 2022-04-07 17:41
Hi, I've posted a small patch in PR #1801 
I've tested it successfully, as in it compiles code using steps inside dockerized windows server 2019 with msvc 2017, cmake and conan installed

**Comment by Danielku15** [comment] 2023-11-24 08:15
@ethomson A lot of time passed since your post and times changed quite a bit since then. What would be the latest reasons to not support windows containers? And if there are concerns not to provide it (yet?) on GitHub.com, would there speak anything against an experimental opt-in for self-hosted runners? 

While I understand that there might be various implications on Windows containerization and nested virtualization with different hypervisors. Having an opt-in for testing and evaluation would be already a huge benefit for those who are able to provide an environment where windows containers are supported. 

The biggest risk I see is that people would start reporting bugs if things are not working and it might be time consuming to troubleshoot and assist those customers. 

We are using https://github.com/actions/actions-runner-controller in our GHES environment and certainly would like to use containerized workflows and steps.

**Comment by chadmyers** [comment] 2024-09-24 14:56
Is this issue a dupe of #904?

**Closed** 2024-09-25 16:35 UTC
Labels: enhancement, future
