### ISSUE TITLE
Expanded platform support: Consider porting to go or typescript

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/runner#243] opened 2019-12-20 13:28 UTC
Power PC, Solaris, IBM Mainframe, redhat 5/6 (without a new sku) etc.

Start with an ADR evaluation of platform coverage

**Comment by TingluoHuang** [comment] 2020-01-21 18:08
#296

**Comment by jbergstroem** [comment] 2020-01-29 20:00
I reckon sticking with Node.js is the way to go since most of the action landscape is written in javascript; meaning that even if you would "switch .NET for go", you would be restricted to where node.js can run.

**Comment by bryanmacfarlane** [comment] 2020-01-29 20:09
@jbergstroem - yeah, we're mostly restricted to running where node.  However, if there's a platform that go runs on but node doesn't it could still support `run:` command lines and scripts.  So I would say if we chose go, then any delta would be possible but a degraded experience.

**Comment by jbergstroem** [comment] 2020-01-30 13:09
>  So I would say if we chose go, then any delta would be possible but a degraded experience.

Makes sense but I think it would be a confusing user story. All documentation now would have to take these exception into regard; "works except here", "works only there". I would personally prefer a consistent functionality across.

**Comment by bryanmacfarlane** [comment] 2020-01-30 13:39
It would be covered in one place - the runner download experience.  That's would also be part of the design and analysis when we choose to start this work.

**Comment by TingluoHuang** [comment] 2020-01-31 03:19
`golang` supported platform: https://github.com/golang/go/wiki/MinimumRequirements
`node.js` supported platform: https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list

**Comment by myitcv** [comment] 2020-02-12 14:42
Great to see this. I've [experimented with pure Go GitHub actions](https://blog.myitcv.io/2020/02/04/portable-ci-cd-with-pure-go-github-actions.html) using a thin NodeJS wrapper - from a dependency perspective Go is a great story (as well as being cross-platform).

At the bottom of the blog post I sketched out what v1 of a pure Go solution might look like:

* `uses:` directives reference main packages, so `$package@$version`
* create a temporary Go module to reference the action
* use [proxy.golang.org](https://proxy.golang.org/) for resolution
* `go run $package` (which has the side effect of authenticating modules vs [sum.golang.org](https://sum.golang.org/) and including all module version information in the resulting binary)

This disadvantage of v1 is that it requires an uncached build step for each action. 

But that could easily be fixed in v2 where you have a simple internal GitHub service that cached and served pre-built cross-platform binaries for `$package@$version`. Then you would elide the build time, replacing it with a very fast CDN-speed binary download parameterised by `GOOS` and `GOARCH`.

**Comment by ad-m** [comment] 2020-02-13 08:22
@myitcv, in terms of providing cache for built Go modules, it is worth pointing out that in GitHub Actions currently even Docker images do not have any cache. With each use of the Docker action, the container image is built from the beginning.

**Comment by myitcv** [comment] 2020-02-13 11:47
@ad-m I'll defer to you/others on how things currently work 😄 

My suggestion re caching was, as I tried to indicate via the "v2", a suggestion of how an initial first cut "v1" could be improved further down the line. Absolutely not critical for v1.

**Comment by bryanmacfarlane** [comment] 2020-02-13 13:47
@myitcv - let's keep considerations of supporting go actions natively in another issue.  I want to keep this issue focused on the runner code.

**Comment by myitcv** [comment] 2020-02-13 13:51
@bryanmacfarlane 👍absolutely. Is there an open issue I should follow? Or would you like one created? If so, another issue in this repo or elsewhere?

**Comment by bryanmacfarlane** [comment] 2020-02-13 13:54
Go ahead and create one.  I guess here is the best place :)

**Comment by myitcv** [comment] 2020-02-13 16:47
@bryanmacfarlane raised as https://github.com/actions/runner/issues/333.

**Comment by bnoordhuis** [comment] 2020-04-03 09:53
If there are problematic platforms or architectures for Node.js, that's something I can look into.

We (the Node.js project) are interested in using Actions for our CI matrix. We already test on a fairly wide range of platforms and architectures (z/os, aix, freebsd, os390, ppc64, etc.)

**Comment by aholler** [comment] 2020-09-23 07:52
I would suggest to write a runner in C++ using e.g. Boost.Asio. This should work on almost any platfrom and architecture.

**Comment by smorimoto** [comment] 2021-01-23 00:40
Any language is fine as long as the platforms we want to support are supported. In any cases, we must make clear paths and move forward if we do this.

**Comment by smorimoto** [comment] 2021-01-23 00:41
Make a clear list of what the problem is, show a reasonable solution to that, and decide the timeline. It really doesn't matter which language we use.

**Comment by edrozenberg** [comment] 2021-03-04 23:44
Since this issue dates to 2019, curious if still planned anytime soon or years away if ever. Considered using this project but got discouraged when I saw .Net is involved. Don't want to make life tougher with unpleasant dependencies. We'll consider using Github's own runner functionality for now rather than using this self hosted project.

**Comment by hross** [comment] 2021-03-31 00:49
For now we don't have plans to take on rewriting the runner. for reference @edrozenberg this is the code for the github runner itself (hosted and self hosted).

**Closed by hross** 2021-03-31 00:49 UTC
Labels: Runner Feature

**Comment by davidchisnall** [comment] 2021-05-19 13:09
Rewriting the runner is likely to be a lot of work, but it would be beneficial if the the *protocol* that the runner talks could be cleanly documented.  This would allow for third-party implementations for self-hosted pools.

**Comment by jbergstroem** [comment] 2021-05-19 13:34
> Rewriting the runner is likely to be a lot of work, but it would be beneficial if the the _protocol_ that the runner talks could be cleanly documented. This would allow for third-party implementations for self-hosted pools.

Took the liberty of opening a new issue to track this.

**Comment by ChristopherHX** [comment] 2021-05-25 22:28
I successfully reverse engineered their undocumented protocol and used [act](https://github.com/nektos/act) to write a runner prototype in go.
https://github.com/nektos/act/issues/706
