### ISSUE TITLE
Log lines for an active step are inaccessible

### ISSUE THREAD

**Issue by etaormm** [actions/runner#2131] opened 2022-09-19 09:30 UTC
Last issue got closed without resolution -> https://github.com/actions/runner/issues/886

Describe the bug
When opening the "run" page for an active job you can see:

Gray checkmarks and expandable sections for completed steps and all of their log lines.
Yellow loading animation on any active steps.
Circles for the future steps.
The log lines for the active steps will then start streaming in, but the prior lines for that step are not there, and there appears to be no way to see them until the step completes.

To Reproduce

Run an action
Visit the run page after a few seconds and try to find the log lines for the currently running step that occurred before you loaded the page.

Expected behavior
All of the log lines that were emit before I loaded the page should be visible, then new ones stream in afterwards.

**Comment by ViacheslavKudinov** [comment] 2022-09-28 15:52
Same issue. 
It's not possible to see the previous log output if no new logs are coming.
We need the ability to see what is happening if to open Action run later and job/step is "stuck on something", but without streaming any new logs. 
Now it is impossible to troubleshoot what is happening. 
Moreover, cancelletion is not an option for some use cases just to get log outputs.

**Comment by etaormm** [comment] 2023-01-11 09:44
I don't like to bump issues, but when can we assign this to Developer?

**Comment by etaormm** [comment] 2023-01-11 09:45
@nikola-jokic I don't like to bump issues, but when can we assign this to Developer?

**Comment by mcarans** [comment] 2023-01-12 03:22
It is pretty poor that the first issue (886) got closed without any explanation. This issue has been a pain for me for a while. Whenever I have a step that runs far longer than expected, I cannot look at the log to see where it has reached. I can't determine whether it's near the finish line or stuck somewhere near the beginning. This really needs to be prioritised and fixed.

**Comment by 0xF4D3C0D3** [comment] 2023-01-12 03:41
![image](https://user-images.githubusercontent.com/19762154/211969995-d49268c5-8a37-4d2c-92ee-6e8d151c9a85.png)

I'm sure that a lot of developers are suffering due to this issue. is that technically impossible? if so, please say so, so that I don't need to mind this issue anymore

**Comment by ViacheslavKudinov** [comment] 2023-01-12 06:44
Same issue.
It's not possible to understand what is happening when open log and there is no new lines.
Is it stuck? Is it doing something? If so, should I wait or cancel? 
It is really poor experience with this behaviour of showing logs.

**Comment by umm0n** [comment] 2023-01-12 13:25
If somebody were to ask me what's my number 1 annoyance with GHA, I would point them to this issue. It would be amazing if this could get prioritised.

**Comment by ruvceskistefan** [comment] 2023-01-13 11:38
Hey @etaormm,
This is not runner issue, other team is currently working on this feature.
As mentioned in closed [ticket](https://github.com/actions/runner/issues/886#issuecomment-997039117) this repo is just for Runner bugs so I'll close this issue. You can address it on [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback)

**Closed by ruvceskistefan** 2023-01-13 11:38 UTC
Labels: bug

**Comment by etaormm** [comment] 2023-01-13 12:42
Hey @ruvceskistefan,

Okey but, this was first raised back in 2020 (someone mentioned in old ticket that this feature is in backlog) - so, 2 years ago and this issue is still present.... it is indeed a major issue, just look at GitLab - they don't have such bug with log output.

Since you're saying that other team is working on this issue (feature), is there any possibility that we can escalate this?
This should be a priority.

**Comment by ViacheslavKudinov** [comment] 2023-01-13 13:55
While ago when we asked Enterprise support, they pointed us out to address this issue in actions/runners repo.
GitLab is not the one example, I've never had this issue with Jenkins, Google Cloud build, Bamboo, DroneCI, GoCD...
It is really frustrating to have it on GitHub when we are heavily rely on the platform this days.

**Comment by mcarans** [comment] 2023-01-13 18:38
> Hey @etaormm, This is not runner issue, other team is currently working on this feature. As mentioned in closed [ticket](https://github.com/actions/runner/issues/886#issuecomment-997039117) this repo is just for Runner bugs so I'll close this issue. You can address it on [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback)

I would classify this as a bug since not displaying any output for a step that is long running is not what I would describe as normal behaviour. 

I have raised it on the GitHub Feedback Forum here: https://github.com/community/community/discussions/44250

**Comment by axel-h** [comment] 2023-04-17 00:12
@ruvceskistefan Fair point, that it's not a runner issue. But this issue (or https://github.com/actions/runner/issues/886) is what people like me find when trying to find a solution or the current status. So, where should be look instead?

**Comment by jaredsinclair** [comment] 2023-04-18 22:54
Please GitHub provide visibility into this issue. We are wasting so much time and energy canceling and rerunning logs, not to mention the total inability to have multiple teammates in a work-from-home scenario be able to view logs from active jobs. None of us are asking for the moon here. Visibility please.

**Comment by tking16** [comment] 2023-05-19 12:52
Lol closed and no fix, embarrassing...

**Comment by adamwojt** [comment] 2023-06-27 15:24
Still not fixed.

**Comment by umm0n** [comment] 2023-06-27 15:44
[This feature will soon be released](https://github.com/actions/runner/issues/886#issuecomment-1564345968). I suggest you follow issue #886 for updates.

**Comment by umm0n** [comment] 2023-06-27 16:08
> 

It's the only issue I've seen with regular dev updates on this, last one being May 31 2023.

**Comment by yuvarajselva** [comment] 2023-06-28 10:07
I'm running Packer in my GitHub Workflow (self-hosted runners) and the log never shows up. As everyone knows, if it is completed/failed, then it is available. But, it is not live. Please provide a fix soon.

**Comment by axelcoezard** [comment] 2023-07-12 07:43
I have this bug too on a Github Workflow (self-hosted runners), running Cypress tests.

**Comment by ChangeinX** [comment] 2023-07-29 00:51
Last issue got closed without resolution -> https://github.com/actions/runner/issues/886

Describe the bug
When opening the "run" page for an active job you can see:

Gray checkmarks and expandable sections for completed steps and all of their log lines.
Yellow loading animation on any active steps.
Circles for the future steps.
The log lines for the active steps will then start streaming in, but the prior lines for that step are not there, and there appears to be no way to see them until the step completes.

To Reproduce
Steps to reproduce the behavior:

Run an action
Visit the run page after a few seconds and try to find the log lines for the currently running step that occurred before you loaded the page.

Expected behavior
All of the log lines that were emit before I loaded the page should be visible, then new ones stream in afterwards.

**Comment by divmgl** [comment] 2023-08-31 20:48
Running into this issue now and it's costing me hours of my time. Killing the workflow also isn't showing me logs.

**Comment by paholg** [comment] 2023-09-19 05:36
Also running into this. Can we please have a tracking issue or something at least? It's pretty crazy that this is not fixed, yet the only issues about it are closed.

**Comment by shqear93** [comment] 2023-09-20 11:57
any updates here?? @github "engineers"!

**Comment by vmoens** [comment] 2023-09-20 16:42
Help guys! This is a real pain, help would be greatly appreciated!

**Comment by bryanmacfarlane** [comment] 2023-09-20 18:27
Since #866 was linked here, please check [the last entry there from last week](https://github.com/actions/runner/issues/886#issuecomment-1716243229)

**Comment by chtpl** [comment] 2023-09-26 09:22
This is a no-go, Microsoft. Fix it ASAP!

**Comment by ogwok** [comment] 2023-10-03 11:32
Me too, I can't really view the "errors" in the logs. Please we need a fix.

**Comment by r0b3r4** [comment] 2023-10-04 07:11
wtf this issue is just closed?

**Comment by DARKo6o6o6** [comment] 2023-10-05 00:56
Fix it you have my permission

**Comment by phact** [comment] 2023-10-06 14:43
:sob:

**Comment by omril1** [comment] 2023-11-21 07:30
This is pure evil of you to not fix and even close the issue.
Truly a dark pattern to make us waste more time on CI aborts and reruns for your greedy corp

**Comment by Dmitry1987** [comment] 2023-12-12 15:28
> This is pure evil of you to not fix and even close the issue. Truly a dark pattern to make us waste more time on CI aborts and reruns for your greedy corp

🤣  
you watch too much youtube mate, it's not evil, it's called business 👨‍💼 💼 
but yeah completely ridiculous, 3 years passed since people started complaining about that issue...

**Comment by bryanmacfarlane** [comment] 2023-12-12 15:46
Check the [comment above](https://github.com/actions/runner/issues/2131#issuecomment-1728236207) linking to the dupe with the status?  It's implemented, many customers have been flagged in and it's starting to rollout.

**Comment by philipvirtune** [comment] 2024-01-11 11:42
pls fix

**Comment by wrslatz** [comment] 2024-04-30 21:14
Looks like this has been released! 🎉 
[Blog](https://github.blog/changelog/2024-04-30-github-actions-ui-improvements/), https://github.com/github/roadmap/issues/839

**Comment by HaveAGitGat** [comment] 2024-07-29 16:35
For those like me confused that this still doesn't seem to be working: [link](https://github.com/github/roadmap/issues/839)

> will also show the previous ***1,000*** lines when visiting the logs of an actively running job.

It's still not possible to see the whole log of the active step. So I would say this feature has not been implemented, could add a UI indicator to say it's limited to the last 1000 lines. Maybe AI in 50 years will be able to solve the problem of giving a log file to the user ;).

1000 lines is an improvement though so thank you for that 😊.

**Comment by brianjmurrell** [comment] 2024-07-29 17:13
Clearly 1000 lines is a performance thing.

Maybe a compromise is to default to 1000 lines but allow the user to specify if they want more.  That way for anyone that 1000 lines is enough, the existing behaviour is maintained but for those that really do need more than 1000 they have the option, that they have to take action to achieve.

**Comment by oshri-garama-lmnd** [comment] 2025-01-06 14:03
This is not working still. still can't see the logs within the GitHub Action.

**Comment by battlesnake** [comment] 2025-09-17 17:45
I'm amazed at how bad GHA is in 2025 compared to Gitlab or Jenkins of almost a decade ago
