### ISSUE TITLE
self hosted runners not getting started with error

### ISSUE THREAD

**Issue by compliance-user** [actions/runner#1643] opened 2022-02-01 06:20 UTC
Connecting to github.

Successfull.

Runner update process finished. /_work/_update.sh: line 98: /bin/mv: No such file or directory.

√ Connected to GitHub

Current runner version: '2.286.0'
2022-01-25 06:09:45Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.286.1 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.
/_work/_update.sh: line 98: /bin/mv: No such file or directory

**Comment by nikola-jokic** [comment] 2022-02-03 10:45
Hi @compliance-user, we are trying to reproduce this issue. Could you tell me if the issue persists on the newer runner version on your machine? If the current version is 2.287.0 and an update occurs, does the same message appears?

And also, could you add machine architecture and OS information?

**Comment by compliance-user** [comment] 2022-02-04 10:26
Hi @nikola-jokic The issue still persists on the newer version which is 2.287.1. We managed to get this back to normal by disabling one of our worker node from kubernetes and restarted kubelet and other required services to bring the runner up. We still have no idea on the root cause for that particular issue.

OS Arch information
Arch - Linux 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OS - CentOS Linux release 8.2.2004 (Core)

**Comment by nikola-jokic** [comment] 2022-02-04 10:53
Hi @compliance-user,

As of version `2.287.0`, in the release [notes](https://github.com/actions/runner/blob/main/releaseNote.md), you can see that the flag `--disableupdate` is being added.

As for reproducing the issue, please file an issue following the template so we can reproduce it and fix it for you. You can file another issue following those steps, or you can comment on it here with the template provided, so I can reproduce it and start working on the fix right away.

Please, notify me if the `--disableupdate` flag fixed your problem, and if you file a new issue, I will close this one and start working on the new one

**Comment by nikola-jokic** [comment] 2022-02-15 07:55
Hi @compliance-user,

I hope this helped. Since there is no response for some time, I will close now this issue. If you experience the same issue, either file another one or re-open this one. Thanks!

**Closed by nikola-jokic** 2022-02-15 07:55 UTC
Labels: bug, Runner Auto-update :disappointed:, awaiting-customer-response
