### ISSUE TITLE
Feature request: BSD support

### ISSUE THREAD

**Issue by ghost** [actions/runner#586] opened 2020-07-13 12:00 UTC
**Describe the enhancement**
I would like to use FreeBSD and OpenBSD as my build systems which leverage GitHub Actions, however they do not appear on the supported OS list.

**Code Snippet**
n/a

**Additional information**
BSD systems are similar to Linux but have their own quirks and usage. I looked through the ports list for [FreeBSD](https://www.freebsd.org/cgi/ports.cgi?query=github&stype=all) and OpenBSD but did not see anything at this time.

**Comment by laffer1** [comment] 2020-07-24 23:02
I would love this too but I think FreeBSD only has .net core 2.x in ports and this runner requires .net core 3.  See https://www.freshports.org/lang/linux-dotnet-runtime/

Not sure about OpenBSD.

**Comment by jbeich** [comment] 2020-10-16 13:36
Duplicate of #385?

**Comment by ligurio** [comment] 2021-01-22 15:23
.net core WIP port on OpenBSD - https://github.com/rfht/coreclr-openbsd

**Comment by TingluoHuang** [comment] 2021-04-23 15:47
close... dup with https://github.com/actions/runner/issues/385

**Closed by TingluoHuang** 2021-04-23 15:47 UTC
Labels: enhancement
