### ISSUE TITLE
all github actions are stucked and can not execute

### ISSUE THREAD

**Issue by taojintianxia** [actions/runner#2197] opened 2022-10-12 11:03 UTC
hi there, recently I found that the github action in shardingsphere has something wrong. as we can see, there is only one action is `in progress` but the other 12 actions are `queued` status and pending resource to execute.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4112856/195327707-1d1172df-7d9f-497c-ad8d-84dabf6f8828.png">
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/4112856/195327759-df9a856f-9c43-42ae-b9a2-03a6987e41bc.png">

**Comment by martin-g** [comment] 2022-10-12 13:18
https://github.com/apache/shardingsphere/actions

**Comment by taojintianxia** [comment] 2022-10-13 02:51
> https://github.com/apache/shardingsphere/actions

thank you for sharing.

**Comment by taojintianxia** [comment] 2022-10-13 02:54
this appearance is a little bit "random", sometimes there will be one or two actions executing, but sometimes all actions are stucked there.
BTW, what's the maxmium of an Apache project action concurrency ?

**Comment by TingluoHuang** [comment] 2022-10-13 02:56
I can't share this info with you in the public repository, you will need to create a support ticket for requesting this info.

**Comment by taojintianxia** [comment] 2022-10-13 05:20
> I can't share this info with you in the public repository, you will need to create a support ticket for requesting this info.

I see. then how to create a support ticket ya.

**Comment by TingluoHuang** [comment] 2022-10-13 12:30
https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket

**Comment by cytopia** [comment] 2022-10-31 18:30
I am facing the same issue with ~10 projects at least. Only one or two parallel runners are working. And also quite frequently there is a huge waiting time for runner to actually start a job

**Comment by fhammerl** [comment] 2022-11-01 13:12
We're acknowledging this is affecting multiple, distinct users of Actions.
Creating a support issue is the best way to get the right attention on this.
Closing the issue as it is likely not an issue directly caused by the runner itself.

**Closed by fhammerl** 2022-11-01 13:12 UTC
Labels: bug, awaiting-customer-response
