### ISSUE TITLE
add-mask is not working when using exec nodeJS

### ISSUE THREAD

**Issue by nitzanashi** [actions/runner#741] opened 2020-10-06 11:18 UTC
**Describe the bug**
my workflow run a js file to set env variables, I'm trying to use `exec` & `execSync` to setup my env variables, since eh set-env is depercated.

There is one variable that I'm trying to mask but it won't work with `exec` but only with `console.log`.

what I want to do:
```
    execSync(`echo "::add-mask::${myToken}"`);
    execSync(`echo "MY_TOKEN=${myToken}" >> $GITHUB_ENV`);
```

what  i'm currently doing
```
    console.log(`::add-mask::${myToken}`);
    execSync(`echo "MY_TOKEN=${myToken}" >> $GITHUB_ENV`);
```

**To Reproduce**
1. Create a workflow that runs a `.js` file to set variables
2. Inside the `.js` file use `execSync` or `exec` to add a mask to a following variable then set the variable itself
3. Variable is not masked on the run itself

**Expected behavior**
I expect the value of the variable to be masked

**Comment by nikola-jokic** [comment] 2022-03-28 10:03
Hi @nitzanashi,

I have reproduced this issue. What it seems to me is that the child_process.execSync(`echo "::add-mask::${myToken}"`); never actually touches the stdout, which would be used later for add-mask. 
I created a simple index.js file:
```
const child_process = require("child_process");

const myToken = "example";
child_process.execSync(`echo "::add-mask::${myToken}"`);
child_process.execSync(`echo "MY_TOKEN=${myToken}" >> $GITHUB_ENV`);
```
If you execute it using `node index.js`, you can see that the echo is never actually streamed to the stdout. Since it is not streamed, we are not picking it up. That is not the case with console.log, which streams the output to the stdout and is picked up and masked as expected.

I am closing this issue now, but if you have any additional details or questions, please post them here.

**Closed by nikola-jokic** 2022-03-28 10:03 UTC
Labels: bug
