### ISSUE TITLE
New environment file issues with Outputs and fromJson

### ISSUE THREAD

**Issue by TheOnlyWei** [actions/runner#2245] opened 2022-11-07 20:45 UTC
**Describe the bug**
Getting deprecated "set-output" command warning, so I decided to update the notation to use github environment files, but started getting these errors in both self-hosted and GitHub-hosted servers:

`Error when evaluating 'strategy' for job 'Test_Second_Job'. .github/workflows/github-actions-demo.yml (Line: 28, Col: 21): Error parsing fromJson,.github/workflows/github-actions-demo.yml (Line: 28, Col: 21): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/github-actions-demo.yml (Line: 28, Col: 21): Unexpected type of value '', expected type: Sequence.`

I made changes according to the following link:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I created a very basic version of the workflow yaml file to try and pinpoint the issue as in the below link, but even that is giving the same errors:
https://github.com/TheOnlyWei/github_actions_test/blob/env-filetest/.github/workflows/github-actions-demo.yml
https://github.com/TheOnlyWei/github_actions_test/actions/runs/3398602911
```
name: GitHub Actions Demo
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test_First_Job:
    runs-on: windows-2019
    steps:
      - name: Convert input to JSON for matrix.
        id: matrix_json_step
        shell: pwsh
        run: |
          $jsonArrayString = "[`"test1:test2:test3`",`"test4:test5:test6`"]"
          echo "JSON_ARRAY=${jsonArrayString}" >> $GITHUB_OUTPUT

    outputs:
      JSON_ARRAY: ${{ steps.matrix_json_step.outputs.JSON_ARRAY }}

  Test_Second_Job:
    runs-on: windows-2019
    needs: Test_First_Job
    strategy:
      fail-fast: false
      matrix:
        JSON_ARRAY: ${{ fromJson(needs.Test_First_Job.outputs.JSON_ARRAY) }}
    steps:
      - name: Print JSON_ARRAY
        shell: pwsh
        run: |
          Write-Host "JSON_ARRAY VALUE IN SECOND JOB: ${{ matrix.JSON_ARRAY }}"
```
Anyone know how to fix this error? According to official document, the above should work. The above code worked fine with old "set-output" format.

According to fromJson doc, the above should work?
https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

**To Reproduce**
See above.

**Expected behavior**
Expected behavior is that using the new GitHub environment file should produce no errors like the deprecated "set-output" command, but there is an error.

## Runner Version and Platform
Version of your runner?
2.298.2

OS of the machine running the runner? OSX/Windows/Linux/...
Windows Server 2016 Datacenter

## What's not working?
See above.

## Job Log Output
See above.

## Runner and Worker's Diagnostic Logs
Not applicable.

**Comment by NPGiorgi** [comment] 2022-11-08 15:24
Same is happening to me, and the issue seems to be specific to fromJson + matrix. My process is:

- First job creates json, save it as output
- Second job grabs json from first job output, parses it and prints it (works fine, added for debugging porpuses)
- Third job uses the json from first job output to build a matrix strategy (get the same error stated above)

Error:


`Error when evaluating 'strategy' for job 'build_job_name'. .github/workflows/workflow_name.yaml (Line: 118, Col: 15): Error parsing fromJson,.github/workflows/workflow_name.yaml (Line: 118, Col: 15): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/deploy_dev.yaml (Line: 118, Col: 15): Unexpected type of value '', expected type: Mapping.`

Also I need to add this was working fine on Friday, and it was broken when I came back on Monday.

**Comment by multinegsix** [comment] 2022-11-10 06:28
I spent hours banging my head against wall util figuring out a solution.

The gist of it is to escape double quotes in your JSON string. Try something like this
```sh
echo "JSON_ARRAY=[\"test1:test2:test3\",\"test4:test5:test6\"]" >> $GITHUB_OUTPUT
```

I was originally using `fromJSON(github.event.inputs.XXX)` for the matrix value and that worked fine. Later I decided to run some string processing on the `inputs.XXX`, export it as a job `output` before feeding it to `matrix:`. But that failed miserably. I started to realize it had something to do with the way GHA converts between string and JSON, after seeing this code example in GHA's documentation: https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

There's that subtlety I failed to notice: what's stored inside `github.event.inputs.XXX` is probably an escaped JSON string, rather than the raw string I entered. `echo`ing it out somehow hides that information away.

**Comment by TheOnlyWei** [comment] 2022-11-10 23:15
@multinegsix My JSON_ARRAY string does escape the double quotes. The ``` symbol escapes in PowerShell.

**Comment by multinegsix** [comment] 2022-11-11 02:53
@TheOnlyWei Can you try the follow?
```
$jsonArrayString = "[\`"test1:test2:test3\`",\`"test4:test5:test6\`"]"
```

**Comment by TheOnlyWei** [comment] 2022-11-11 03:02
> @TheOnlyWei Can you try the following?
> 
> ```
> $jsonArrayString = "[\`"test1:test2:test3\`",\`"test4:test5:test6\`"]"
> ```
I get the same error:
https://github.com/TheOnlyWei/github_actions_test/actions/runs/3442137845

**Comment by multinegsix** [comment] 2022-11-11 04:56
Try this
```yaml
jobs:
  Test_First_Job:
    runs-on: windows-2019
    steps:
      - name: Convert input to JSON for matrix.
        id: matrix_json_step
        shell: pwsh
        run: |
          $jsonArrayString = "{`"JSON_ARRAY`":[`"test1:test2:test3`",`"test4:test5:test6`"]}"
          echo "JSON_ARRAY=${jsonArrayString}" >> $GITHUB_OUTPUT
    outputs:
      JSON_ARRAY: ${{ steps.matrix_json_step.outputs.JSON_ARRAY }}

  Test_Second_Job:
    runs-on: windows-2019
    needs: Test_First_Job
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Test_First_Job.outputs.JSON_ARRAY) }}
    steps:
      - name: Print JSON_ARRAY
        shell: pwsh
        run: |
          Write-Host "JSON_ARRAY VALUE IN SECOND JOB: ${{ matrix.JSON_ARRAY }}"
```

**Comment by TheOnlyWei** [comment] 2022-11-11 05:01
@multinegsix I get the same error:
https://github.com/TheOnlyWei/github_actions_test/actions/runs/3442611699

If you want to play around with the workflow, it's easy to copy my workflow code and try it out in your own test repository. You don't need much setup or code.

**Comment by multinegsix** [comment] 2022-11-11 05:27
@TheOnlyWei The issue in your code is actually a different one. Notice that in the error message, GHA is complaining the value of the matrix field is empty, which means the output was never set successfully in the first job.

I was able to get it working. Check out this:
https://github.com/multinegsix/test-gha/actions/runs/3442717284

I couldn't find a working way to set outputs in Windows, so translated your first job into bash, and it worked.

**Comment by TheOnlyWei** [comment] 2022-11-12 00:14
> @TheOnlyWei The issue in your code is actually a different one. Notice that in the error message, GHA is complaining the value of the matrix field is empty, which means the output was never set successfully in the first job.
> 
> I was able to get it working. Check out this: https://github.com/multinegsix/test-gha/actions/runs/3442717284
> 
> I couldn't find a working way to set outputs in Windows, so translated your first job into bash, and it worked.

Either way, that looks like an unintended breaking change that the GitHub changelog didn't discuss if you can only get previously working code to work through such a modification. Even then with the modified workflow code, it still doesn't work on windows-2019. To me it still seems like a bug is the root cause.

**Comment by nikola-jokic** [comment] 2022-11-25 12:32
Hey @TheOnlyWei,

The issue is that the shell script is written to a file and then executed with the pwsh. The issue is that $GITHUB_OUTPUT is an environment variable. So to correctly use it, you need to do: `echo "JSON_ARRAY=${jsonArrayString}" >> $Env:GITHUB_OUTPUT`

**Comment by nikola-jokic** [comment] 2022-11-25 12:44
Hey @TheOnlyWei,

Thank you for reporting this! The issue is that $GITHUB_OUTPUT is an environment variable. When invoked, pwsh will not see the GITHUB_OUTPUT variable set, but the $Env:GITHUB_OUTPUT is. So, to fix your issue, please use something like:
```powershell
echo "JSON_ARRAY=${jsonArrayString}" >> $Env:GITHUB_OUTPUT
```

**Comment by nikola-jokic** [comment] 2022-11-25 12:59
I will close this issue now, since the documentation [states](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) that `GITHUB_OUTPUT` is used as an environment variable.
If you feel like the docs should point it out more clearly, please raise this issue here [github/docs](https://github.com/github/docs) :relaxed: 
And thank you again for explaining the issue so clearly!

**Closed by nikola-jokic** 2022-11-25 12:59 UTC
Labels: bug, keep

**Comment by Motoxpro** [comment] 2022-12-19 01:47
For any googlers, the problem for me was adding too many curly brackets. So:

```
$jsonArrayString = "[`"test1:test2:test3`",`"test4:test5:test6`"]"
echo "JSON_ARRAY=${jsonArrayString}" >> $GITHUB_OUTPUT
```

becomes

```
$jsonArrayString = "[`"test1:test2:test3`",`"test4:test5:test6`"]"
echo "JSON_ARRAY=$jsonArrayString" >> $GITHUB_OUTPUT
```

Note `${jsonArrayString}` to `$jsonArrayString`

**Comment by LinqLover** [comment] 2023-06-09 10:50
For any googlers, I had a similar problem in bash because I used double quotes (`"`) instead of single quotes (`'`) when creating the output. In my case, I could fix the issue by changing

```diff
-          echo "my-array<<EOF
+          echo 'my-array<<EOF
           ${{ toJson(fromJson('["Trunk", "6.0"]')) }}
-          EOF" >> $GITHUB_OUTPUT
+          EOF' >> $GITHUB_OUTPUT
```

https://github.com/hpi-swa-lab/SqueakByExample-english/pull/137/commits/01707f0b56ac9eacc2bb003e6b354174434ceb07

**Comment by copdips** [comment] 2023-10-10 22:44
> For any googlers, I had a similar problem in bash because I used double quotes (`"`) instead of single quotes (`'`) when creating the output. In my case, I could fix the issue by changing
> 
> ```diff
> -          echo "my-array<<EOF
> +          echo 'my-array<<EOF
>            ${{ toJson(fromJson('["Trunk", "6.0"]')) }}
> -          EOF" >> $GITHUB_OUTPUT
> +          EOF' >> $GITHUB_OUTPUT
> ```
> 
> [hpi-swa-lab/SqueakByExample-english@01707f0](https://github.com/hpi-swa-lab/SqueakByExample-english/commit/01707f0b56ac9eacc2bb003e6b354174434ceb07)

my use case is that the json value is in a var, say $json_var,  we must use double quotes with echo, do you have any idea ?

**Comment by LinqLover** [comment] 2023-10-10 23:00
> > For any googlers, I had a similar problem in bash because I used double quotes (`"`) instead of single quotes (`'`) when creating the output. In my case, I could fix the issue by changing
> > 
> > ```diff
> > -          echo "my-array<<EOF
> > +          echo 'my-array<<EOF
> >            ${{ toJson(fromJson('["Trunk", "6.0"]')) }}
> > -          EOF" >> $GITHUB_OUTPUT
> > +          EOF' >> $GITHUB_OUTPUT
> > ```
> > 
> > [hpi-swa-lab/SqueakByExample-english@01707f0](https://github.com/hpi-swa-lab/SqueakByExample-english/commit/01707f0b56ac9eacc2bb003e6b354174434ceb07)
> 
> @LinqLover 
> my use case is that the json value is in a var, say $json_var,  we must use double quotes with echo, do you have any idea ?

Not sure about your concrete situation, but bash provides escaping for any kind of quotes ...

**Comment by copdips** [comment] 2023-10-11 00:03
yes you're right, I mistake was using `jq` against to to double quotes escaped json var, it's OK now, thanks,
