### ISSUE TITLE
Runner replacement is broken in 2.296.2

### ISSUE THREAD

**Issue by myoung34** [actions/runner#2119] opened 2022-09-13 16:50 UTC
**Describe the bug**

Runner registration on a node with the same name (idle) is broken in 2.296.2

config.sh now exits with non-zero (1) code and errors

```
  echo "Configuring"
  ./config.sh \
      --url "${_SHORT_URL}" \
      --token "${RUNNER_TOKEN}" \
      --name "${_RUNNER_NAME}" \
      --work "${_RUNNER_WORKDIR}" \
      --labels "${_LABELS}" \
      --runnergroup "${_RUNNER_GROUP}" \
      --unattended \
      --replace \
      ${_EPHEMERAL} \
      ${_AUTO_UPDATE}

  echo $?
```

```
A runner exists with the same name
A runner exists with the same name github-runner-EXAMPLENAME.
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.

1
```

In 2.296.1 it works fine:

```
A runner exists with the same name
√ Successfully replaced the runner
√ Runner connection is good

# Runner settings


√ Settings Saved.

0
```

**To Reproduce**
1.  Run config.sh properly with a `--name "${_RUNNER_NAME}"` on `2.296.2` for a runner name that is idle and should be replaced
2. See error

**Expected behavior**
No change in behavior from previous.. The node should be replaced and exit 0

## Runner Version and Platform

2.296.2

OS of the machine running the runner? docker (ubuntu)

## What's not working?

Agent registration

## Job Log Output

above

## Runner and Worker's Diagnostic Logs

n/a

Also see https://github.com/myoung34/docker-github-actions-runner/issues/243

**Comment by zubaya** [comment] 2022-10-03 09:56
getting the above behaviour but not on 2.296.2 but rather with 2.297.0
<img width="740" alt="Screenshot 2022-10-03 at 11 53 31" src="https://user-images.githubusercontent.com/25004839/193550076-33e948b0-dcdd-49b1-a1cc-aca302d67f91.png">

**Comment by PureWhiteWu** [comment] 2022-10-11 03:38
Hi, is there any progress about this?

**Comment by flobernd** [comment] 2022-10-11 08:10
Just found this. Might be related to my issue from here: https://github.com/myoung34/docker-github-actions-runner/issues/251

**Comment by davetapley** [comment] 2022-10-19 17:59
⚠️  There's now hard deadline on this of **31st May 2023** else it will break any actions using `save-state` and/or `set-output`.

See [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/):

> Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.
...
> If you are using self-hosted runners make sure they are updated to version 2.297.0 or greater.

**Comment by nitrocode** [comment] 2022-10-20 14:05
Here are all the changes between v2.296.2 (broken) and v2.296.1 (working)

https://github.com/actions/runner/compare/v2.296.1...v2.296.2

**Comment by myoung34** [comment] 2022-10-20 14:15
It looks as though this might have been patched behind the scenes

```
# Authentication


√ Connected to GitHub

# Runner Registration




A runner exists with the same name
√ Successfully replaced the runner
√ Runner connection is good

# Runner settings


√ Settings Saved.


√ Connected to GitHub

Current runner version: '2.296.2'
2022-10-20 14:14:29Z: Listening for Jobs

```

**Comment by nikola-jokic** [comment] 2022-11-17 09:28
Thanks for letting us know that this issue has been resolved! I tried reproducing it, and it seems to be working fine, so I am going to close the issue now :relaxed:

**Closed by nikola-jokic** 2022-11-17 09:28 UTC
Labels: bug
