### ISSUE TITLE
ARM self-hosted runner cannot be used with container 

### ISSUE THREAD

**Issue by pmatos** [actions/runner#698] opened 2020-09-10 11:47 UTC
**Describe the bug**

An ARM self-hosted runner starting a docker image won't have access to DNS.

**To Reproduce**

Create an ARM self-hosted running inside a ubuntu container and attempt to ping `google.com`.

**Expected behavior**

There is a problem in docker on ARM see: https://github.com/moby/moby/issues/41217
This is not a `runner` bug so strictly this is FYI but it was suggested to open this here https://github.community/t/any-luck-from-anyone-using-actions-on-arm/131310/2?u=pmatos

**Comment by hross** [comment] 2020-09-14 10:07
Appreciate the FYI on this issue. I am going to close it since it's not a bug, but people should be able to find it in the repo if they his this issue. Thank you @pmatos

**Closed by hross** 2020-09-14 10:07 UTC
Labels: bug
