### ISSUE TITLE
Composite Actions fail to overwrite env if it is already set

### ISSUE THREAD

**Issue by thboop** [actions/runner#1899] opened 2022-05-17 17:55 UTC
**Describe the bug**
Setting an env that is already set in a composite action causes the value to not be set as expected.
**To Reproduce**
Setup a composite action
```
  using: "composite"
  steps:
    - name: set env
      shell: bash
      run: |
        VAR1=$RANDOM
        echo "MY_VAR1=$(echo $VAR1)" >> $GITHUB_ENV
        echo $VAR1
        echo 'create finished'
  
    # Show ref information
    - name: Show ref information
      run: |
          echo 'random1'
          echo $MY_VAR1
          echo 'env-random1'
          echo "${{ env.MY_VAR1 }}"
          echo 'read finished'
      shell: bash
```
Call it twice locally using `uses: ./{path}`
Notice the second time the value it reads is incorrect.
**Expected behavior**

## Runner Version and Platform
2.291.1 linux

**Comment by ChristopherHX** [comment] 2022-05-17 22:42
I believe this is a duplicate of https://github.com/actions/runner/issues/789, which could be fixed by https://github.com/actions/runner/pull/1794.

**Closed** 2022-06-29 00:50 UTC
Labels: bug, Runner Bug
