### ISSUE TITLE
Error in Extracting Zip File

### ISSUE THREAD

**Issue by Mohit09091999** [actions/runner#1880] opened 2022-05-10 05:21 UTC
I am getting the error while I am extracting the file through powershell an manually also. While I was extracting it manually the error I got in copy file is Error 0x80004005: Unspecified error.

While I was extracting through powershell with the command in github docs is A local file header is corrupt.

**Comment by ruvceskistefan** [comment] 2022-05-10 07:09
Hi @Mohit09091999,

This really isn't a runner problem, it's a problem locally on your Windows machine. Are you sure that you have downloaded the appropriate version of the runner, that is that you have chosen Windows as OS?

I will send you some links where you can find the causes and solutions to such a problem:
https://www.lifewire.com/how-to-fix-error-code-0x80004005-4689559
https://www.winhelponline.com/blog/zip-error-0x80004005-extract-copy-unspecified-error/

I hope these links help, and I'm going to close this issue as it isn't related to the runner. If you have any more questions, feel free to ask :)

**Closed by ruvceskistefan** 2022-05-10 07:09 UTC
Labels: bug
